objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMN_CountryOfIncorporation__c</fullName>
        <description>Used for integration to populate client&apos;s Country of Incorporation from source systems.</description>
        <label>Country of Incorporation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_DateOfIncorporation__c</fullName>
        <description>Used for integration to populate client&apos;s Date of Incorporation from source systems.</description>
        <label>Date of Incorporation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMN_OrganisationType__c</fullName>
        <description>Used for integration to populate client&apos;s Organization Type from source systems.</description>
        <label>Organisation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BANK</fullName>
                    <label>Bank</label>
                </value>
                <value>
                    <fullName>CC</fullName>
                    <label>Closed Corporation</label>
                </value>
                <value>
                    <fullName>COMM</fullName>
                    <label>Commercial Bank</label>
                </value>
                <value>
                    <fullName>CO</fullName>
                    <label>Company</label>
                </value>
                <value>
                    <fullName>COR</fullName>
                    <label>Corporate</label>
                </value>
                <value>
                    <fullName>FOR_CO</fullName>
                    <label>Foreign Company</label>
                </value>
                <value>
                    <fullName>Foreign Trust</fullName>
                </value>
                <value>
                    <fullName>JOINT</fullName>
                    <label>Joint Company</label>
                </value>
                <value>
                    <fullName>LTD_PVT_CO</fullName>
                    <label>Limited Private Company</label>
                </value>
                <value>
                    <fullName>NON_COMM</fullName>
                    <label>Non-Commercial Bank</label>
                </value>
                <value>
                    <fullName>NPC</fullName>
                    <label>Non Profit Company</label>
                </value>
                <value>
                    <fullName>NPO</fullName>
                    <label>Non Profit Organisation</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PERS</fullName>
                    <label>Person</label>
                </value>
                <value>
                    <fullName>INC</fullName>
                    <label>Personal Liability Company</label>
                </value>
                <value>
                    <fullName>PVT_CO</fullName>
                    <label>Private Company</label>
                </value>
                <value>
                    <fullName>PUB_CO</fullName>
                    <label>Public Company</label>
                </value>
                <value>
                    <fullName>SOC</fullName>
                    <label>State Owned Company</label>
                </value>
                <value>
                    <fullName>TRUST</fullName>
                    <label>Trust</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/InsurancePolicy.object
<CustomObject>
    <fields>
        <fullName>CMN_ExpiryDate__c</fullName>
        <description>Used for integration to populate Expiry Date from source systems (Compass/Lifestyle).</description>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMN_IssueDate__c</fullName>
        <description>Used for integration to populate Issue Date from source systems (Compass/Lifestyle).</description>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/InsurancePolicyParticipant.object
<CustomObject>
    <fields>
        <fullName>AW_ConsultantCode__c</fullName>
        <label>Consultant Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_DateofBirth__c</fullName>
        <description>Date of Birth of Policy Participant</description>
        <label>Date of Birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_FirstName__c</fullName>
        <description>First Name of Policy Participant</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Gender__c</fullName>
        <description>Gender of Policy Participant</description>
        <label>Gender</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_IdentificationNumber__c</fullName>
        <description>Identification Number of Policy Participant</description>
        <label>Identification Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Initials__c</fullName>
        <description>Initials of Policy Participant</description>
        <label>Initials</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_LastName__c</fullName>
        <description>Last Name of Policy Participant</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_MaritalStatus__c</fullName>
        <description>Marital Status of Policy Participant</description>
        <label>Marital Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Occupation__c</fullName>
        <description>Occupation of Policy Participant</description>
        <label>Occupation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_PDBID__c</fullName>
        <description>PDBID of Policy Participant</description>
        <label>PDB ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_PercentageSplit__c</fullName>
        <description>Percentage Split</description>
        <label>Percentage Split</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_RelationshipToLifeAssured__c</fullName>
        <label>Relationship to Life Assured</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adopted Brother</fullName>
                </value>
                <value>
                    <fullName>Adopted Daughter</fullName>
                </value>
                <value>
                    <fullName>Adopted Mother</fullName>
                </value>
                <value>
                    <fullName>Adopted Sister</fullName>
                </value>
                <value>
                    <fullName>Adopted Son</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Brother-In-Law</fullName>
                </value>
                <value>
                    <fullName>Business Associate</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Co-Director</fullName>
                </value>
                <value>
                    <fullName>Co-Shareholder</fullName>
                </value>
                <value>
                    <fullName>Common Law Spouse</fullName>
                </value>
                <value>
                    <fullName>Common-Law-Husband</fullName>
                </value>
                <value>
                    <fullName>Common-Law-Wife</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Creditor</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Daughter-In-Law</fullName>
                </value>
                <value>
                    <fullName>Debtor</fullName>
                </value>
                <value>
                    <fullName>Domestic Helper</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Ex-Husband</fullName>
                </value>
                <value>
                    <fullName>Ex-Wife</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Father-In-Law</fullName>
                </value>
                <value>
                    <fullName>Fiance (Male)</fullName>
                </value>
                <value>
                    <fullName>Fiancee (Female)</fullName>
                </value>
                <value>
                    <fullName>Foster Daughter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_RoleCode__c</fullName>
        <description>Role Code of Policy Participant</description>
        <label>Role Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Salutation__c</fullName>
        <description>Salutation of Policy Participant</description>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_SecondName__c</fullName>
        <description>Second Name of Policy Participant</description>
        <label>Second Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_CountryOfCitizenship__c</fullName>
        <description>Used for integration to populate Country of Citizenship from source systems (Compass/Lifestyle)</description>
        <label>Country of Citizenship</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_CountryOfIncorporation__c</fullName>
        <description>Used for integration to populate Country of Incorporation from source systems (Compass/Lifestyle)</description>
        <label>Country of Incorporation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_CountryOfIssue__c</fullName>
        <description>Used for integration to populate Country of Issue from source systems (Compass/Lifestyle)</description>
        <label>Country of Issue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_DateOfIncorporation__c</fullName>
        <description>Used for integration to populate Date of Incorporation from source systems (Compass/Lifestyle)</description>
        <label>Date of Incorporation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMN_Email__c</fullName>
        <description>Used for integration to populate Email from source systems (Compass/Lifestyle)</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CMN_ExpiryDate__c</fullName>
        <description>Used for integration to populate Expiry Date from source systems (Compass/Lifestyle)</description>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMN_FifthName__c</fullName>
        <description>Used for integration to populate Fifth Name from source systems (Compass/Lifestyle)</description>
        <label>Fifth Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_FourthName__c</fullName>
        <description>Used for integration to populate Fourth Name from source systems (Compass/Lifestyle)</description>
        <label>Fourth Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ImmediateExpenseBenefit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for integration to populate Immediate Expense Benefit Indicator from source systems (Compass/Lifestyle)</description>
        <inlineHelpText>The Immediate Expenses Benefit will accelerate a proportion of the Life Cover. R 50000.00 of the Death Value will be paid to the Client on the death of the First Life Assured. A 2-year waiting period from the date that the Life Cover benefit was taken out applies to the Immediate Expenses Benefit.</inlineHelpText>
        <label>Immediate Expense Benefit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CMN_IssueDate__c</fullName>
        <description>Used for integration to populate Issue Date from source systems (Compass/Lifestyle)</description>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMN_Mobile__c</fullName>
        <description>Used for integration to populate Mobile Number from source systems (Compass/Lifestyle)</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CMN_OccupationRiskCategory__c</fullName>
        <description>Used for integration to populate Occupation Risk Category from source systems (Compass/Lifestyle)</description>
        <label>Occupation Risk Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CMN_LibertyInsurancePolicyParticipant</fullName>
        <active>true</active>
        <description>Record type to be used for Integration with Compass &amp; Lifestyle.</description>
        <label>Liberty Insurance Policy Participant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AW_DAL_InsurancePolicyParticipant.cls
/**
 * @description Public class to return the records of Insurance Policy Participant
 *
 * @author jayanth.kumar.s@accenture.com rajpal.singh@accenture.com
 *
 * @date 2021, October 2022
 */
public inherited sharing class AW_DAL_InsurancePolicyParticipant
{
	private static final String FIELD_INSURANCE_POLICY_ID = 'InsurancePolicyId';
	private static final String FIELD_NAME_INSURED_ID = 'InsurancePolicy.NameInsured.Id';
	@TestVisible
	private static final String FIELD_ROLE = InsurancePolicyParticipant.Role.getDescribe().getLocalName();
	private static final String OBJECT_NAME = InsurancePolicyParticipant.SObjectType.getDescribe().getLocalName();

	/**
	 * @description The primary life assured for a policy
	 */
	public static final String PRIMARY_LIFE_ASSURED = 'Primary Life Assured';
	/**
	 * @description The primary life assured's beneficiary of a policy
	 */
	public static final String PRIMARY_LIFE_ASSURED_BENEFICIARY = 'Primary Life Assured Beneficiary';
	/**
	 * @description The secondary life assured for a policy
	 */
	public static final String SECONDARY_LIFE_ASSURED = 'Secondary Life Assured';
	/**
	 * @description The secondary's life assured beneficiary
	 */
	public static final String SECONDARY_LIFE_ASSURED_BENEFICIARY = 'Secondary Life Assured Beneficiary';

	/**
	 * @description Used when linking Insurance Policy Participants to a Insurance Policy
	 */
	@TestVisible
	private static final String LIFE_ASSURED_ROLE_TYPES = PRIMARY_LIFE_ASSURED + ','
			+ PRIMARY_LIFE_ASSURED_BENEFICIARY + ',' + SECONDARY_LIFE_ASSURED + ',' + SECONDARY_LIFE_ASSURED_BENEFICIARY;
			
	/**
	 * @description The record type is being used when creating Insurance Policy Participant records
	 */
	public static final String RT_LIBERTY_INSURANCE_POLICY_PARTICIPANT = 'CMN_LibertyInsurancePolicyParticipant';

	/**
	 * @description Method to set the fields using Insurance Policy Participants
	 *
	 * @return A set of the standard fields used by queries when returning Insurance Policy Participants
	 */
	public static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				FIELD_INSURANCE_POLICY_ID,
				FIELD_ROLE,
				InsurancePolicyParticipant.AW_ConsultantCode__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_DateofBirth__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_FirstName__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_Gender__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_IdentificationNumber__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_Initials__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_LastName__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_MaritalStatus__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_Occupation__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_PDBID__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_PercentageSplit__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_RelationshipToLifeAssured__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_RoleCode__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_Salutation__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.AW_SecondName__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_CountryOfCitizenship__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_CountryOfIncorporation__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_CountryOfIssue__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_DateOfIncorporation__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_Email__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_ExpiryDate__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_FifthName__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_FourthName__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_ImmediateExpenseBenefit__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_IssueDate__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_Mobile__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_OccupationRiskCategory__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_OrganisationType__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_OrganizationName__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_PassportNumber__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_PhoneNumber__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_PreferredLanguage__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_Qualification__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_Race__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_RegistrationNumber__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_RelationshipToOwner__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_Smoker__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_SouthAfricanResidentIndicator__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_Suffix__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_ThirdName__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_WeddingAnniversary__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.CMN_WorkPhoneNumber__c.getDescribe().getLocalName(),
				InsurancePolicyParticipant.RelatedParticipantContactId.getDescribe().getLocalName()
		};
	}

	/**
	 * @description Method to retrieve Insurance Policy Participant based on account linked to related Insurance Policy and Role
	 *
	 * @param accountId the Id of account linked to Related Insurance Policy
	 * @param roles the roles for which records are being queried
	 *
	 * @return A list of Insurance Policy Participants
	 */
	public static List<InsurancePolicyParticipant> findByAccountIdAndRole(String accountId, List<String> roles)
	{
		CMN_DAL_Search.SOQLSearchParameters searchParameters =
				CMN_DAL_SObjectSelector.initialiseParameters(OBJECT_NAME, FIELD_NAME_INSURED_ID, new Set<String> {accountId}, getDefaultFields());
		searchParameters.searchConditions.inX(FIELD_ROLE, roles);

		return CMN_DAL_Search.getObjects(searchParameters);
	}

	/**
	 * @description Method to retrieve Financial Account Roles based on PolicyID and Array of Roles
	 *
	 * @param policyId the Id of insurance policy
	 * @param roles the list of roles for which records are being queried
	 *
	 * @return A list of Insurance Policy Participants
	 */
	public static List<InsurancePolicyParticipant> findByPolicyIdAndListOfRoles(Id policyId, List<String> roles)
	{
		CMN_DAL_Search.SOQLSearchParameters searchParameters =
				CMN_DAL_SObjectSelector.initialiseParameters(OBJECT_NAME, FIELD_INSURANCE_POLICY_ID, new Set<String> {policyId}, getDefaultFields());
		searchParameters.searchConditions.inX(FIELD_ROLE, roles);
		return CMN_DAL_Search.getObjects(searchParameters);
	}
}