objects/Account.object
<CustomObject>
    <fields>
        <fullName>AW_Last_Synch_Date__c</fullName>
        <description>The date that the client account record was synchronised across systems</description>
        <label>Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>AW_SKF_Id__c</fullName>
        <description>The unique identifier of the client record on SKF  which is used to store the SKF ID of a Master account</description>
        <externalId>true</externalId>
        <label>SKF Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_SyncErrorMessage__c</fullName>
        <description>This field helps to notify of any errors when an adviser creates or updates my Prospect Client Account
So that adviser can raise the issue timelessly with Liberty Support.</description>
        <inlineHelpText>The error message is to be quoted when raising an issue with the Liberty Support Team.</inlineHelpText>
        <label>Sync Error Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AW_Synch_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that a Sync error has been identified with the clients record, the sync error message will be required to be quoted when raising an issue with the Liberty support team</description>
        <label>Sync Error</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMN_WebserviceCallQueue__c.object
<CustomObject>
    <description>A object which is used to orchestrate and track webservices (inbound and outbound). By injecting an item into this object will asynchronously manage a call to external web service.</description>
    <fields>
        <fullName>CMN_Response__c</fullName>
        <description>Response for webservice call queue</description>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMN_Status__c</fullName>
        <description>Select status of webservice call queue</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                    <label>Queued</label>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Retry</fullName>
                </value>
                <value>
                    <fullName>Retrying</fullName>
                </value>
                <value>
                    <fullName>Web Service Call Completed</fullName>
                </value>
                <value>
                    <fullName>Batched</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMN_TriggeringObjectId__c</fullName>
        <description>Triggering Object ID</description>
        <label>Triggering Object Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Webservice Call Queue</label>
    <nameField>
        <displayFormat>WCQ-{0000000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Calls Queue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CMN_FLOW_ProspectResponse_TEST.cls
/**
 * @description Test class for CMN_FLOW_ProspectResponse
 *
 * @see CMN_FLOW_ProspectResponse
 *
 * @author vishakha.saini@accenture.com safwan.h.mohammed@accenture.com
 *
 * @date February 2022, June 2022
 */
@IsTest(SeeAllData=false IsParallel=true)
private class CMN_FLOW_ProspectResponse_TEST
{
	@IsTest
	private static void checkProspectResponse()
	{
		Id accountFailureTriggerId;
		Id accountSuccessTriggerId;
		List<Account> newAccounts;
		List<CMN_WebserviceCallQueue__c> queueItems = new List<CMN_WebserviceCallQueue__c>();
		Set<Id> accountIds = new Set<Id>();
		final String completedStatus = 'Completed';
		final String failedStatus = 'Failed';
		final String globalKeyValue = CMN_DAL_SObjectDomain.generateRandomNumber();
		final String validResponseBody =
				'{ "Message": "Persons Added successfully", "stateId": "8AAC3638-845C-44E0-A7C5-64111B2D2D7A", "globalKey": "' + globalKeyValue + '" }';

		newAccounts = AW_DAL_TestDataFactory.createClientAccount(2);

		accountSuccessTriggerId = newAccounts.get(0).Id;
		accountFailureTriggerId = newAccounts.get(1).Id;

		// Success
		CMN_WebserviceCallQueue__c successQueueItem = new CMN_WebserviceCallQueue__c();
		successQueueItem.CMN_TriggeringObjectId__c = accountSuccessTriggerId;
		successQueueItem.CMN_Status__c = completedStatus;
		successQueueItem.CMN_Response__c = validResponseBody;
		queueItems.add(successQueueItem);

		// Failed
		CMN_WebserviceCallQueue__c failedQueueItem = new CMN_WebserviceCallQueue__c();
		failedQueueItem.CMN_TriggeringObjectId__c = accountFailureTriggerId;
		failedQueueItem.CMN_Status__c = failedStatus;
		failedQueueItem.CMN_Response__c = '{"error":{"errorMessage":"Prospect sync did not execute as expected."}}';
		queueItems.add(failedQueueItem);

		Test.startTest();
		CMN_FLOW_ProspectResponse.updateProspect(queueItems);
		Test.stopTest();

		accountIds.add(accountSuccessTriggerId);
		accountIds.add(accountFailureTriggerId);
		Map<Id, Account> accountByIds = new Map<Id, Account>(AW_DAL_Account.findById(accountIds)); // Re-query accounts to get updated values
		Account successAccount = accountByIds.get(accountSuccessTriggerId);
		Account failedAccount = accountByIds.get(accountFailureTriggerId);

		System.assertEquals(false, successAccount.AW_Synch_Error__c, 'Sync Error flag not set correctly on success Account');
		System.assertNotEquals(null, successAccount.AW_Last_Synch_Date__c, 'Last Sync Date not set correctly on success Account');
		System.assertEquals(globalKeyValue, successAccount.AW_SKF_Id__c, 'SKF Id not set correctly on success Account');

		System.assertEquals(true, failedAccount.AW_Synch_Error__c, 'Sync Error flag not set correctly on failed Account');
		System.assertNotEquals(null, failedAccount.AW_SyncErrorMessage__c, 'Sync Error message did not load as expected');
	}
}