objects/Account.object
<CustomObject>
    <fields>
        <fullName>SLC_IDNumber__c</fullName>
        <label>ID Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__FinancialAccountNumber__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SLC_DAL_Account.cls
/**
 * @description Public class to return the records of Accounts
 *
 * @author Futureform
 *
 * @date January 2023
 */
public with sharing class SLC_DAL_Account {

    public static final String FIELD_PHONE_NUMBER = Account.Phone.getDescribe().getLocalName();
    public static final String OBJECT_NAME = Account.SObjectType.getDescribe().getLocalName();
    public static final String RT_BUSINESS_ACCOUNT = 'IndustriesBusiness';

    /**
     * @description The default fields to query from the Account Object
     *
     * @return A list of Account fields
     */
    public static Set<String> getDefaultFields()
    {
        return new Set<String>
        {
                Account.AccountNumber.getDescribe().getLocalName(),
                Account.AccountSource.getDescribe().getLocalName(),
                Account.AnnualRevenue.getDescribe().getLocalName(),
                Account.BillingCity.getDescribe().getLocalName(),
                Account.BillingCountry.getDescribe().getLocalName(),
                Account.BillingGeocodeAccuracy.getDescribe().getLocalName(),
                Account.BillingLatitude.getDescribe().getLocalName(),
                Account.BillingLongitude.getDescribe().getLocalName(),
                Account.BillingPostalCode.getDescribe().getLocalName(),
                Account.BillingState.getDescribe().getLocalName(),
                Account.BillingStreet.getDescribe().getLocalName(),
                Account.Description.getDescribe().getLocalName(),
                Account.Id.getDescribe().getLocalName(),
                Account.Industry.getDescribe().getLocalName(),
                Account.IsDeleted.getDescribe().getLocalName(),
                Account.IsPersonAccount.getDescribe().getLocalName(),
                Account.Name.getDescribe().getLocalName(),
                Account.NumberOfEmployees.getDescribe().getLocalName(),
                Account.OwnerId.getDescribe().getLocalName(),
                Account.ShippingCity.getDescribe().getLocalName(),
                Account.ShippingCountry.getDescribe().getLocalName(),
                Account.ShippingGeocodeAccuracy.getDescribe().getLocalName(),
                Account.ShippingLatitude.getDescribe().getLocalName(),
                Account.ShippingLongitude.getDescribe().getLocalName(),
                Account.ShippingPostalCode.getDescribe().getLocalName(),
                Account.ShippingState.getDescribe().getLocalName(),
                Account.ShippingStreet.getDescribe().getLocalName(),
                Account.Sic.getDescribe().getLocalName(),
                Account.SicDesc.getDescribe().getLocalName(),
                Account.Site.getDescribe().getLocalName(),
                Account.SystemModstamp.getDescribe().getLocalName(),
                Account.TickerSymbol.getDescribe().getLocalName(),
                Account.Type.getDescribe().getLocalName(),
                Account.Website.getDescribe().getLocalName(),
                Account.SLC_IDNumber__c.getDescribe().getLocalName(),
                FIELD_PHONE_NUMBER
        };
    }

    public static final String ACCOUNT_ID = FinServ__FinancialAccount__c.FinServ__PrimaryOwner__c.getDescribe().getLocalName();

    public static List<FinServ__FinancialAccount__c> findChildFinancialAccounts(Id accountId, Boolean isExternal) {
        if (isExternal) {
            return [
                    SELECT Id, Name, FinServ__PrimaryOwner__c, FinServ__FinancialAccountNumber__c
                    FROM FinServ__FinancialAccount__c
                    WHERE FinServ__PrimaryOwner__c IN (
                            SELECT AccountId
                            FROM AccountContactRelation
                            WHERE Contact.AccountId = :accountId
                            OR AccountId = :accountId
                    )
            ];
        } else {
            return [
                    SELECT
                            Id, Name, FinServ__PrimaryOwner__c, FinServ__FinancialAccountNumber__c
                    FROM FinServ__FinancialAccount__c
                    WHERE FinServ__PrimaryOwner__c = :accountId
            ];
        }
    }

    public static Account findById(Id accountId){
        return (Account)CMN_DAL_SObjectSelector.findById(OBJECT_NAME, accountId, getDefaultFields());
    }
    
    public static List<Account> findACRAccounts(Id accountId){
        List<AccountContactRelation> acrAccounts = [SELECT Id, AccountId, Account.Name FROM AccountContactRelation WHERE Contact.AccountId =: accountId]; 
        
        Set<Id> accIds = new Set<Id>();
        for(AccountContactRelation acr : acrAccounts){
            accIds.add(acr.AccountId);
        }
        
        List<Account> relatedAccounts = [SELECT Id, Name, AccountNumber, IsPersonAccount, SLC_IDNumber__c FROM Account WHERE Id IN : accIds];

        return relatedAccounts;
    }
}