objects/Account.object
<CustomObject>
    <fields>
        <fullName>AW_UACFID__c</fullName>
        <description>The UACF ID of the owner of the record (if they have one). This field&apos;s sole purpose if for use with Account duplicate rule so that we can differentiate accounts with same Id number across two owners and not consider them duplicates.</description>
        <label>UACF ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AW_AdviserPerformance__c.object
<CustomObject>
    <description>Various measures used to track activity by  advisers and sales leaders. The information is drawn from external systems as well as activity within Salesforce. The activity measures are collected weekly and aggregated to a parent object monthly.</description>
    <fields>
        <fullName>AW_AP_CompositeID__c</fullName>
        <description>Used as a foreign key to uniquely identify AP rows. 
Format: WW-YYYY-ConsultantCode</description>
        <externalId>true</externalId>
        <label>AP CompositeID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AW_AdviserTarget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Targeted set for the Adviser</description>
        <label>Activity Measure Total</label>
        <referenceTo>AW_AdviserTarget__c</referenceTo>
        <relationshipLabel>Activity Measure Actuals</relationshipLabel>
        <relationshipName>Adviser_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_AverageFAVP__c</fullName>
        <description>This is used to store average FAVP value</description>
        <label>AQC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_ClientSatisfactionScore__c</fullName>
        <description>Year average rating based on clients surveys</description>
        <label>Client Satisfaction Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_ConsultantCode__c</fullName>
        <description>13 Digit Consultant Code</description>
        <externalId>true</externalId>
        <label>Consultant Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_LAPExpTenure__c</fullName>
        <description>This  is used to store LAP Experience Tenure</description>
        <label>Tenure</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_LastYearsProductionClubStatus__c</fullName>
        <description>Status of Last Year&apos;s Production Club</description>
        <label>Production Club based on previous year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_LeadConversionRate__c</fullName>
        <description>This is a calculated value where Lead Conversion Rate is a percent of lead converted of the total number of leads</description>
        <formula>AW_NumberOfLeadConverted__c /  (AW_NumberOfOpenLeads__c +  AW_NumberOfLeadConverted__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Lead Conversion Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_NumberOfLeadConverted__c</fullName>
        <description>Number of leads converted by adviser</description>
        <label>Number of Lead Converted</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_NumberOfNewLeads__c</fullName>
        <description>This indicates the number of new leads for the month</description>
        <label>Number of New Leads</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_NumberOfNewOpportunities__c</fullName>
        <description>Count of number of new opportunities</description>
        <label>Number of New Opportunities</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_NumberOfOpenLeads__c</fullName>
        <description>This indicates the number of open leads for the month</description>
        <label>Number of Open Leads</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_NumberOfOpportunitiesOpen__c</fullName>
        <description>Number of Opportunities Open for Adviser</description>
        <label>Number of Open Opportunities</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_NumberOfOpportunitiesWon__c</fullName>
        <description>Number of Opportunities Won by Adviser</description>
        <label>Number of Opportunities Won</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_OpportunityWinRate__c</fullName>
        <description>Opportunity Win rate of Adviser shown as a percentage</description>
        <formula>AW_NumberOfOpportunitiesWon__c /(  AW_NumberOfOpportunitiesWon__c + AW_NumberOfOpportunitiesOpen__c )</formula>
        <label>Actual Opportunity Win Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_StartDate__c</fullName>
        <description>Start Date of the data  record</description>
        <formula>IF
(
	DATE(VALUE(AW_Year__c),1,1)&gt; DATE(VALUE(AW_Year__c),1,1)- WEEKDAY(DATE(VALUE(AW_Year__c),1,1))+( AW_WeekNumber__c -1)*7+1,
	DATE(VALUE(AW_Year__c),1,1),
	DATE(VALUE(AW_Year__c),1,1)- WEEKDAY(DATE(VALUE(AW_Year__c),1,1))+( AW_WeekNumber__c -1)*7+2
)</formula>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AW_UACFID__c</fullName>
        <description>owner will be assigned based on UACFID</description>
        <label>UACFID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_WeekNumber__c</fullName>
        <description>This field stores the week number.</description>
        <label>Week Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_Year__c</fullName>
        <description>This is used to store year in which the calculation was done</description>
        <label>Year</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Activity Measure Actual</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Measure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Measure Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AW_AdviserTarget__c.object
<CustomObject>
    <description>Aggregates the weekly activity measures and also stores the targets set and year to date numbers</description>
    <fields>
        <fullName>AW_ActualLeadConversionRate__c</fullName>
        <description>Actual Lead Conversion Rate</description>
        <formula>IF(

	OR(
		AND
		(
			ISBLANK(AW_ActualNumberOfLeadConverted__c),
			ISBLANK(AW_ActualNumberOfLeadOpen__c)
		),
		AW_ActualNumberOfLeadConverted__c+AW_ActualNumberOfLeadOpen__c=0
	),
	NULL,
	AW_ActualNumberOfLeadConverted__c /( AW_ActualNumberOfLeadConverted__c + AW_ActualNumberOfLeadOpen__c )
)</formula>
        <label>Actual Lead Conversion Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_ActualOpportunityWinRate__c</fullName>
        <description>Actual Opportunity Win Rate</description>
        <formula>IF(

	OR(
		AND
		(
			ISBLANK(AW_ActualOpportunitiesWon__c),
			ISBLANK(AW_ActualOpportunitiesOpen__c)
		),
		AW_ActualOpportunitiesWon__c+AW_ActualOpportunitiesOpen__c=0
	),
	NULL,
	AW_ActualOpportunitiesWon__c /( AW_ActualOpportunitiesWon__c + AW_ActualOpportunitiesOpen__c )
)</formula>
        <label>Actual Opportunity Win Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_LeadConversionRate__c</fullName>
        <description>Lead Conversion set as target</description>
        <label>Target Lead Conversion Rate</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_OpportunityWinRate__c</fullName>
        <description>This indicates the win rate for number of opportunities won per period</description>
        <label>Target Opportunity Win Rate</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_Year__c</fullName>
        <description>This indicates the year in which the calculation was done</description>
        <label>Year</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Activity Measure Total</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Measure Total Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Measure Totals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AW_ConsultantCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Users consultant code</description>
        <externalId>true</externalId>
        <label>Consultant Code</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AW_UACFID__c</fullName>
        <description>Users unique Liberty ID</description>
        <externalId>true</externalId>
        <label>UACF ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AW_DAL_AdviserPerformance.cls
/**
 * @description Public class to return the Performance Record
 *
 * @author Accenture
 *
 * @date 2019
 */
public inherited sharing class AW_DAL_AdviserPerformance
{
	private static final String FIELD_AVERAGE_FAP = AW_AdviserPerformance__c.AW_AverageFAVP__c.getDescribe().getLocalName();
	private static final String FIELD_EXP_TENURE = AW_AdviserPerformance__c.AW_LAPExpTenure__c.getDescribe().getLocalName();
	private static final String FIELD_PRODUCTION_CLUB_STATUS = AW_AdviserPerformance__c.AW_LastYearsProductionClubStatus__c.getDescribe().getLocalName();
	private static final String FIELD_START_DATE = AW_AdviserPerformance__c.AW_StartDate__c.getDescribe().getLocalName();
	private static final String OBJECT_NAME = AW_AdviserPerformance__c.SObjectType.getDescribe().getLocalName();
	public static final String ACHIEVER_PRODUCTION_CLUB_STATUS = 'ACHIEVER';
	public static final String FIELD_COMPOSITE_KEY = AW_AdviserPerformance__c.AW_AP_CompositeID__c.getDescribe().getName();
	public static final String FIELD_LEAD_CONVERSION_RATE = 'AW_AdviserTarget__r.AW_ActualLeadConversionRate__c';
	public static final String FIELD_OPPORTUNITY_WIN_RATE = 'AW_AdviserTarget__r.AW_ActualOpportunityWinRate__c';
	public static final String FIELD_UACF_ID = AW_AdviserPerformance__c.AW_UACFID__c.getDescribe().getLocalName();

	/**
	 * @description Method to define the fields to retrieve Account Team Members
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				AW_AdviserPerformance__c.AW_AdviserTarget__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_ClientSatisfactionScore__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_ConsultantCode__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_LastYearsProductionClubStatus__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_LeadConversionRate__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_NumberOfLeadConverted__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_NumberOfNewLeads__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_NumberOfNewOpportunities__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_NumberOfOpenLeads__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_NumberOfOpportunitiesOpen__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_NumberOfOpportunitiesWon__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_OpportunityWinRate__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_WeekNumber__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.AW_Year__c.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.CreatedDate.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.Id.getDescribe().getLocalName(),
				AW_AdviserPerformance__c.OwnerId.getDescribe().getLocalName(),
				FIELD_AVERAGE_FAP,
				FIELD_COMPOSITE_KEY,
				FIELD_EXP_TENURE,
				FIELD_LEAD_CONVERSION_RATE,
				FIELD_OPPORTUNITY_WIN_RATE,
				FIELD_PRODUCTION_CLUB_STATUS,
				FIELD_START_DATE,
				FIELD_UACF_ID
		};
	}

	/**
	 * @description This method is use to return the list of Adviser Performance
	 *
	 * @param performanceIds A set of performance ids
	 *
	 * @return A list of items
	 */
	public static List<AW_AdviserPerformance__c> findById(Set<Id> performanceIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, performanceIds, getDefaultFields());
	}

	/**
	 * @description This method is use to return the list of Adviser Performance with composite key
	 *
	 * @param compositeKeys A set of keys
	 *
	 * @return List of found items
	 */
	public static List<AW_AdviserPerformance__c> findByCompositeId(Set<String> compositeKeys)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_COMPOSITE_KEY, compositeKeys, getDefaultFields());
	}

	/**
	 * @description This method is use to return the an Adviser Performance with given composite key
	 *
	 * @param compositeKey the key against which to search
	 *
	 * @return Null of Item
	 */
	@TestVisible
	private static AW_AdviserPerformance__c findByCompositeId(String compositeKey)
	{
		return (AW_AdviserPerformance__c)CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_COMPOSITE_KEY, compositeKey, getDefaultFields(), false);
	}

	@TestVisible
	private static String generateCompositeKey(User adviser)
	{
		String week = String.valueOf(CMN_UTIL_Date.weekNumberFromDate(Date.today()));
		String year = String.valueOf(Date.today().year());

		return week + year + CMN_UTIL_String.upperCase(adviser.AW_UACFID__c);
	}

	/**
	 * @description This method is return the record Adviser Performance based on composite key and consultant code
	 *
	 * @param obj SObject to store the Adviser performance
	 * @param compositeKey To store the value of compositeKey
	 * @param fieldName To store the name of the field
	 * @param uacfIdFieldName To store the consultant code
	 *
	 * @return Adviser performance record
	 */
	public static AW_AdviserPerformance__c newAdviserPerformance(SObject obj, String compositeKey, String fieldName, String uacfIdFieldName)
	{
		//TODO: Can we move this to the data factory class?
		AW_AdviserPerformance__c performance = new AW_AdviserPerformance__c();

		performance.OwnerId = (Id)obj.get(CMN_DAL_SObjectDomain.FIELD_OWNER_ID);
		performance.AW_UACFID__c = (String)obj.get(uacfIdFieldName);
		Datetime dt = (Datetime)obj.get(fieldName);

		performance.AW_AP_CompositeID__c = compositeKey;

		performance.AW_WeekNumber__c = Decimal.valueOf(CMN_UTIL_Date.weekNumberFromDate(dt.date()));
		performance.AW_Year__c = String.valueOf(dt.year());

		return performance;
	}

	/**
	 * @description This method is return the composite key and consultant code
	 *
	 * @param obj To store the SObject
	 * @param dateFieldName To store the date field
	 * @param uacfIdAPIName To store the consultant code
	 *
	 * @return Adviser performance record
	 */
	public static String getCompositeKey(SObject obj, String dateFieldName, String uacfIdAPIName)
	{
		String year;
		Integer weekNumber;
		String compositeKey = CMN_UTIL_String.EMPTY;

		Datetime objectDate = (Datetime)obj.get(dateFieldName);
		String uacfId = (String)obj.get(uacfIdAPIName);

		if(uacfId != null && objectDate != null)
		{
			year = String.valueOf(objectDate.date().year());
			weekNumber = CMN_UTIL_Date.weekNumberFromDate(objectDate.date());

			compositeKey = constructPerformanceCompositeKey(weekNumber, year, uacfId);
		}

		return compositeKey;
	}

	/**
	 * @description This method is uses to return the Composite Key
	 *
	 * @param weekNumber Week Number
	 * @param year Year
	 * @param uacfId UACF Id
	 *
	 * @return compositeKey
	 */
	public static String constructPerformanceCompositeKey(Integer weekNumber, String year, String uacfId)
	{
		String compositeKey = weekNumber + year + CMN_UTIL_String.upperCase(uacfId);
		return compositeKey;
	}

	/**
	 * @description This method is use to return the list of Adviser Performance by uacfId
	 *
	 * @param uacfIds List of items to search against
	 *
	 * @return adviser's performance record sorted by Start Date
	 */
	public static List<AW_AdviserPerformance__c> findByUACFIDs(Set<String> uacfIds)
	{
		CMN_DAL_Search.SOQLSearchParameters searchParameters = CMN_DAL_SObjectSelector.initialiseParameters(OBJECT_NAME, FIELD_UACF_ID, uacfIds, getDefaultFields());
		searchParameters.addOrderByField(FIELD_START_DATE);
		return CMN_DAL_Search.getObjects(searchParameters);
	}

	/**
	 * @description Finds the latest Adviser Performance by looking for a field that's not null sorted by start date
	 *
	 * @param uacfId the uacfid against which to filter
	 * @param latestByField The field that shouldn't be empty
	 *
	 * @return null or an adviser performance
	 */
	private static AW_AdviserPerformance__c findLatestByUacfId(String uacfId, String latestByField)
	{
		CMN_DAL_Search.SOQLSearchParameters searchParameters = CMN_DAL_SObjectSelector.initialiseParameters(OBJECT_NAME, FIELD_UACF_ID, new Set<String> {uacfId}, getDefaultFields());

		CMN_SOQL_Query.AndCondition andCondition = new CMN_SOQL_Query.AndCondition();

		andCondition.add(new CMN_SOQL_Query.FieldCondition(latestByField, CMN_SOQL_Query.Operator.NOT_EQUALS, CMN_UTIL_String.EMPTY));

		searchParameters.addSearchCondition(andCondition);

		searchParameters.addOrderByField(FIELD_START_DATE, true);
		searchParameters.pageSize = 1;
		List<AW_AdviserPerformance__c> performances = CMN_DAL_Search.getObjects(searchParameters);

		return performances.isEmpty() ? null : performances.iterator().next();
	}

	/**
	 * @description This method is use to retrieve the latest adviser performance record
	 *
	 * @param uacfId UACF Id
	 *
	 * @return AW_AdviserPerformance__c
	 */
	public static AW_AdviserPerformance__c findLatestByUACFID(String uacfId)
	{
		return findLatestByUacfId(uacfId, FIELD_UACF_ID);
	}

	/**
	 * @description This method is use to retrieve the latest adviser performance record with a Production Club Status
	 *
	 * @param uacfId UACF Id
	 *
	 * @return AW_AdviserPerformance__c
	 */
	public static AW_AdviserPerformance__c findLatestWithProductionClubStatusByUACFID(String uacfId)
	{
		return findLatestByUacfId(uacfId, FIELD_PRODUCTION_CLUB_STATUS);
	}

	/**
	 * @description This method is use to retrieve the latest adviser performance record with a Tenure
	 *
	 * @param uacfId UACF Id
	 *
	 * @return AW_AdviserPerformance__c
	 */
	public static AW_AdviserPerformance__c findLatestWithTenureByUACFID(String uacfId)
	{
		return findLatestByUacfId(uacfId, FIELD_EXP_TENURE);
	}

	/**
	 * @description This method is use to retrieve the latest adviser performance record with a AQC
	 *
	 * @param uacfId UACF Id
	 *
	 * @return AW_AdviserPerformance__c
	 */
	public static AW_AdviserPerformance__c findLatestWithAQCByUACFID(String uacfId)
	{
		return findLatestByUacfId(uacfId, FIELD_AVERAGE_FAP);
	}
}