objects/Account.object
<CustomObject>
    <fields>
        <fullName>AW_ClientId__c</fullName>
        <description>The unique client identifier</description>
        <externalId>true</externalId>
        <inlineHelpText>atWork Client ID</inlineHelpText>
        <label>Client ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Country_Of_Birth__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to identify the clients country of birth</description>
        <label>Country of Birth</label>
        <referenceTo>AW_Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Growth_Strategy__c</fullName>
        <description>The strategy the entity will adopt to enable growth to reach their target or goal</description>
        <label>Growth Strategy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_SKF_Id__c</fullName>
        <description>The unique identifier of the client record on SKF  which is used to store the SKF ID of a Master account</description>
        <externalId>true</externalId>
        <label>SKF Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AW_Planned_Solution__c.object
<CustomObject>
    <fields>
        <fullName>AW_CPI__c</fullName>
        <description>The CPI Percentage</description>
        <label>CPI</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_Financial_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related to Financial Goal</description>
        <label>Goal Name</label>
        <referenceTo>FinServ__FinancialGoal__c</referenceTo>
        <relationshipLabel>Planned Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Growth_Strategy__c</fullName>
        <description>The growth strategy in brief</description>
        <label>Growth Strategy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Lumpsum_Amount__c</fullName>
        <description>The lumpsum amount of solution</description>
        <label>Lump Sum Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_Opportunity_Name__c</fullName>
        <description>The related opportunity</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Planned Solutions</relationshipLabel>
        <relationshipName>Planned_Solutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AW_PremiumFrequency__c</fullName>
        <description>How often the premium will be charged of the planned solution</description>
        <label>Premium Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AW_Frequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Premium_Amount__c</fullName>
        <description>Premium amount of the planned solution</description>
        <label>Premium Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_Product_Name__c</fullName>
        <description>Product name of the planned solution</description>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_RecommendedMultiStratPortfolio__c</fullName>
        <description>Recommended Multi Strat Portfolio based on Growth Strategy , CPI and Target Return</description>
        <formula>IF((AW_Target_Return__c - AW_CPI__c) &gt;= 0.01 &amp;&amp; (AW_Target_Return__c - AW_CPI__c) &lt; 0.02 , &quot;Multi-strategy 1&quot;,
			IF((AW_Target_Return__c - AW_CPI__c) &gt;= 0.02 &amp;&amp; (AW_Target_Return__c - AW_CPI__c) &lt; 0.03, &quot;Multi-strategy 2&quot;,	
						IF((AW_Target_Return__c - AW_CPI__c) &gt;= 0.03 &amp;&amp; (AW_Target_Return__c - AW_CPI__c) &lt; 0.04, &quot;Multi-strategy 3&quot;,
									IF((AW_Target_Return__c - AW_CPI__c) &gt;= 0.04 &amp;&amp; (AW_Target_Return__c - AW_CPI__c) &lt; 0.05, &quot;Multi-strategy 4&quot;,
												IF((AW_Target_Return__c - AW_CPI__c) &gt;= 0.05 &amp;&amp; (AW_Target_Return__c - AW_CPI__c) &lt;= 0.06, &quot;Multi-strategy 5&quot;, &quot;&quot;
														)
											)
								) 
					)
		)</formula>
        <label>Recommended Multi Strat Portfolio</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_SourceSystemId__c</fullName>
        <description>External ID of the Source System</description>
        <externalId>true</externalId>
        <label>Source System Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AW_Target_Return__c</fullName>
        <description>The targeted return percentage of solution</description>
        <label>Target Return</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_Term_Months__c</fullName>
        <description>Number of Months</description>
        <label>Term (Months)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Planned Solution</label>
    <nameField>
        <label>Planned Solution Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planned Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>AW_Goal_Type__c</fullName>
        <description>Select Goal Type</description>
        <label>Goal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Growth_Strategy__c</fullName>
        <description>Short description of Growth Strategy</description>
        <label>Growth Strategy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Shortfall__c</fullName>
        <description>This field calculates the Shortfall/Surplus value which is the Target Value - Actual Value. The amount required to meet the target amount/ the amount exceeding the target amount</description>
        <formula>FinServ__ActualValue__c - FinServ__TargetValue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shortfall/Surplus</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/AW_Frequency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <customValue>
        <fullName>BiAnnually</fullName>
        <label>Bi-Annually</label>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <description>This picklist contains the Frequency values sets used by the premium frequency fields.</description>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

classes/AW_DAL_PlannedSolution.cls
/**
 * @description Public class to return the records of a Planned Solution
 *
 * @author pavan.thammali@liberty.co.za, kiran.kumaryelisetti@lntinfotech.com
 *
 * @date June 2022, March 2023
 */
public inherited sharing class AW_DAL_PlannedSolution
{
	private static final String FIELD_ACCOUNT_CLIENT_ID = 'AW_Opportunity_Name__r.Account.AW_ClientId__c';
	private static final String FIELD_ACCOUNT_COUNTRY_OF_BIRTH = 'AW_Opportunity_Name__r.Account.AW_Country_Of_Birth__c';
	private static final String FIELD_ACCOUNT_FINSERV_GENDER = 'AW_Opportunity_Name__r.Account.FinServ__Gender__pc';
	private static final String FIELD_ACCOUNT_FIRST_NAME = 'AW_Opportunity_Name__r.Account.FirstName';
	private static final String FIELD_ACCOUNT_IDENTIFICATION_NUMBER = 'AW_Opportunity_Name__r.Account.AW_IdentificationNumber__pc';
	private static final String FIELD_ACCOUNT_IDENTIFICATION_TYPE = 'AW_Opportunity_Name__r.Account.AW_IdentificationType__pc';
	private static final String FIELD_ACCOUNT_LAST_NAME = 'AW_Opportunity_Name__r.Account.LastName';
	private static final String FIELD_ACCOUNT_PASSPORT_COUNTRY_OF_ISSUE = 'AW_Opportunity_Name__r.Account.AW_PassportCountryOfIssue__pr.AW_CountryCode__c';
	private static final String FIELD_ACCOUNT_PERSON_BIRTH_DATE = 'AW_Opportunity_Name__r.Account.PersonBirthdate';
	private static final String FIELD_ACCOUNT_RETIREMENT_AGE = 'AW_Opportunity_Name__r.Account.Retirement_Age__pc';
	private static final String FIELD_ACCOUNT_SALUTATION = 'AW_Opportunity_Name__r.Account.Salutation';
	private static final String FIELD_ACCOUNT_SKF_ID = 'AW_Opportunity_Name__r.Account.AW_SKF_Id__c';
	private static final String FIELD_FINANCIAL_GOAL = AW_Planned_Solution__c.AW_Financial_Goal__c.getDescribe().getLocalName();
	private static final String FIELD_FINANCIAL_GOAL_GOAL_TYPE = 'AW_Financial_Goal__r.AW_Goal_Type__c';
	private static final String FIELD_FINANCIAL_GOAL_SHORTFALL= 'AW_Financial_Goal__r.AW_Shortfall__c';
	private static final String FIELD_OPPORTUNITY = AW_Planned_Solution__c.AW_Opportunity_Name__c.getDescribe().getLocalName();
	private static final String FIELD_OPPORTUNITY_ID = 'AW_Opportunity_Name__r.Id';
	private static final String OBJECT_NAME = AW_Planned_Solution__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				AW_Planned_Solution__c.AW_CPI__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.AW_Growth_Strategy__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.AW_Lumpsum_Amount__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.AW_PremiumFrequency__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.AW_Premium_Amount__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.AW_Product_Name__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.AW_RecommendedMultiStratPortfolio__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.AW_SourceSystemId__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.AW_Target_Return__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.AW_Term_Months__c.getDescribe().getLocalName(),
				AW_Planned_Solution__c.Name.getDescribe().getLocalName(),
				FIELD_ACCOUNT_CLIENT_ID,
				FIELD_ACCOUNT_COUNTRY_OF_BIRTH,
				FIELD_ACCOUNT_FINSERV_GENDER,
				FIELD_ACCOUNT_FIRST_NAME,
				FIELD_ACCOUNT_IDENTIFICATION_NUMBER,
				FIELD_ACCOUNT_IDENTIFICATION_TYPE,
				FIELD_ACCOUNT_LAST_NAME,
				FIELD_ACCOUNT_PASSPORT_COUNTRY_OF_ISSUE,
				FIELD_ACCOUNT_PERSON_BIRTH_DATE,
				FIELD_ACCOUNT_RETIREMENT_AGE,
				FIELD_ACCOUNT_SALUTATION,
				FIELD_ACCOUNT_SKF_ID,
				FIELD_FINANCIAL_GOAL_GOAL_TYPE,
				FIELD_FINANCIAL_GOAL_SHORTFALL,
				FIELD_OPPORTUNITY,
				FIELD_OPPORTUNITY_ID
		};
	}

	/**
	 * @description Retrieves the planned solution having the given id.
	 *
	 * @param plannedSolutionId a planned solution id
	 *
	 * @return null or item
	 */
	public static AW_Planned_Solution__c findById(Id plannedSolutionId)
	{
		return (AW_Planned_Solution__c)CMN_DAL_SObjectSelector.findById(OBJECT_NAME, plannedSolutionId, getDefaultFields());
	}

	/**
	 * @description Will return all Planned Solution records created by unit tests
	 *
	 * @return A list of Planned Solutions
	 */
	@TestVisible
	private static List<AW_Planned_Solution__c> getAll()
	{
		return CMN_DAL_Search.getAll(OBJECT_NAME, getDefaultFields());
	}

	/**
	 * @description Retrieves the planned solution having the given financial goal id.
	 *
	 * @param financialGoalIds a financial goal id
	 *
	 * @return null or item
	 */
	public static List<AW_Planned_Solution__c> findByFinancialGoalId(Set<Id> financialGoalIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_FINANCIAL_GOAL, financialGoalIds, getDefaultFields());
	}

	/**
	 * @description Retrieves the planned solution having the given opportunity id.
	 *
	 * @param opportunityIds a opportunity id
	 *
	 * @return null or item
	 */
	public static List<AW_Planned_Solution__c> findByOpportunityId(Set<Id> opportunityIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_OPPORTUNITY, opportunityIds, getDefaultFields());
	}
}