objects/Account.object
<CustomObject>
    <fields>
        <fullName>AW_Last_Synch_Date__c</fullName>
        <description>The date that the client account record was synchronised across systems</description>
        <label>Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>AW_SKF_Id__c</fullName>
        <description>The unique identifier of the client record on SKF  which is used to store the SKF ID of a Master account</description>
        <externalId>true</externalId>
        <label>SKF Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_SyncErrorMessage__c</fullName>
        <description>This field helps to notify of any errors when an adviser creates or updates my Prospect Client Account
So that adviser can raise the issue timelessly with Liberty Support.</description>
        <inlineHelpText>The error message is to be quoted when raising an issue with the Liberty Support Team.</inlineHelpText>
        <label>Sync Error Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AW_Synch_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that a Sync error has been identified with the clients record, the sync error message will be required to be quoted when raising an issue with the Liberty support team</description>
        <label>Sync Error</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMN_WebserviceCallQueue__c.object
<CustomObject>
    <description>A object which is used to orchestrate and track webservices (inbound and outbound). By injecting an item into this object will asynchronously manage a call to external web service.</description>
    <fields>
        <fullName>CMN_Errors__c</fullName>
        <description>If any errors were encountered whilst processing a request these will be logged in this field</description>
        <label>Errors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMN_Response__c</fullName>
        <description>Response for webservice call queue</description>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMN_Status__c</fullName>
        <description>Select status of webservice call queue</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queued</fullName>
                    <default>true</default>
                    <label>Queued</label>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Retry</fullName>
                </value>
                <value>
                    <fullName>Retrying</fullName>
                </value>
                <value>
                    <fullName>Web Service Call Completed</fullName>
                </value>
                <value>
                    <fullName>Batched</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMN_TriggeringObjectId__c</fullName>
        <description>Triggering Object ID</description>
        <label>Triggering Object Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Webservice Call Queue</label>
    <nameField>
        <displayFormat>WCQ-{0000000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Calls Queue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CMN_FLOW_ProspectResponse.cls
/**
 * @description This class is used to update prospect response from the external systems
 *
 * @see CMN_FLOW_ProspectResponse_TEST
 *
 * @author Rohith Ballal (Deloitte), safwan.h.mohammed@accenture.com
 *
 * @date October 2020, June 2022
 */
public inherited sharing class CMN_FLOW_ProspectResponse
{
	/**
	 * @description Method to update a prospect based on response from external systems
	 *
	 * @param queueItems List of queue items
	 */
	@InvocableMethod(Label='Fetch and Update Prospect Response' Description='Method to update a prospect based on response from external systems')
	public static void updateProspect(List<CMN_WebserviceCallQueue__c> queueItems)
	{
		String statusCompleted = 'Completed';
		List<Account> accountsList = new List<Account>();

		for(CMN_WebserviceCallQueue__c webCallQueue : queueItems)
		{
			Account updateAccount = new Account(Id = webCallQueue.CMN_TriggeringObjectId__c);

			if(webCallQueue.CMN_Status__c == statusCompleted)
			{
				updateAccount.AW_Synch_Error__c = false;
				updateAccount.AW_SyncErrorMessage__c=CMN_UTIL_String.EMPTY;
				updateAccount.AW_Last_Synch_Date__c = Datetime.now();

				if(webCallQueue.CMN_Response__c != null && webCallQueue.CMN_Response__c.contains('globalKey'))
				{
					Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(webCallQueue.CMN_Response__c);
					updateAccount.AW_SKF_Id__c = String.valueOf(m.get('globalKey'));
				}
			}
			else
			{
				updateAccount.AW_Synch_Error__c = true;
				updateAccount.AW_SyncErrorMessage__c = webCallQueue.CMN_Errors__c != null ?
						webCallQueue.CMN_Errors__c :
						((DTO_ErrorResponse)JSON.deserialize(webCallQueue.CMN_Response__c, DTO_ErrorResponse.class)).error.errorMessage;
			}
			accountsList.add(updateAccount);
		}

		CMN_DAL_SObjectDomain.updateDBObjects(accountsList);
	}
	/**
 * @description Used to parse an error response
 */
	private class DTO_ErrorResponse
	{
		public DTO_Error error;
	}

	/**
	 * @description Detail of error received
	 */
	private class DTO_Error
	{
		public String errorMessage;
	}
}