objects/Account.object
<CustomObject>
    <fields>
        <fullName>FinServ__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>AW_MasterAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the Master Account Details</description>
        <label>MasterAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts (MasterAccount)</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMN_MasterAccountRecordTypeName__c</fullName>
        <description>A field created to hold the master account record type. This field will be used to share the contract with all service console users to have a read only access to the contract.</description>
        <label>Master Account Record Type Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccountNumber__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccountType__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Endowment</fullName>
                </value>
                <value>
                    <fullName>Fixed Annuity</fullName>
                </value>
                <value>
                    <fullName>LISP</fullName>
                </value>
                <value>
                    <fullName>Living Annuity</fullName>
                </value>
                <value>
                    <fullName>Pension Preserver</fullName>
                </value>
                <value>
                    <fullName>Provident Preserver</fullName>
                </value>
                <value>
                    <fullName>Retirement Annuity (RA)</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
                <value>
                    <fullName>Unit trust</fullName>
                </value>
                <value>
                    <fullName>Variable Annuity</fullName>
                </value>
                <value>
                    <fullName>Scrip</fullName>
                </value>
                <value>
                    <fullName>Client Cash</fullName>
                </value>
                <value>
                    <fullName>Withdrawal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__OpenDate__c</fullName>
        <label>Date Opened</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__Premium__c</fullName>
        <label>Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IN FORCE</fullName>
                    <label>In Force</label>
                </value>
                <value>
                    <fullName>UNISSUED</fullName>
                    <label>Unissued</label>
                </value>
                <value>
                    <fullName>NOT TAKEN UP</fullName>
                    <label>Not Taken Up</label>
                </value>
                <value>
                    <fullName>SETTLEMENT PENDING</fullName>
                    <label>Settlement Pending</label>
                </value>
                <value>
                    <fullName>SUSPENSE</fullName>
                    <label>Suspense</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>OUT OF FORCE</fullName>
                    <label>Out of Force</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SC_DAL_FinancialAccount.cls
/**
 * @description Public class to return the record of Financial Account
 *
 * @author aakriti.a.goyal@accenture.com darrion.james.singh@accenture.com jason.van.beukering@accenture.com
 *
 * @date August 2021, April 2022
 */
public inherited sharing class SC_DAL_FinancialAccount
{
	private static final String FIELD_MASTER_ACCOUNT = FinServ__FinancialAccount__c.AW_MasterAccount__c.getDescribe().getLocalName();

	/**
	 * @description Financial Account Number field API name
	 */
	public static final String FIELD_FINANCIAL_ACCOUNT_NUMBER = FinServ__FinancialAccount__c.FinServ__FinancialAccountNumber__c.getDescribe().getLocalName();

	/**
	 * @description Financial Account SObject API Name
	 */
	public static final String OBJECT_NAME = FinServ__FinancialAccount__c.SObjectType.getDescribe().getLocalName();

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				FIELD_FINANCIAL_ACCOUNT_NUMBER,
				FIELD_MASTER_ACCOUNT,
				FinServ__FinancialAccount__c.CMN_MasterAccountRecordTypeName__c.getDescribe().getLocalName(),
				FinServ__FinancialAccount__c.FinServ__FinancialAccountType__c.getDescribe().getLocalName(),
				FinServ__FinancialAccount__c.FinServ__OpenDate__c.getDescribe().getLocalName(),
				FinServ__FinancialAccount__c.FinServ__Premium__c.getDescribe().getLocalName(),
				FinServ__FinancialAccount__c.FinServ__PrimaryOwner__c.getDescribe().getLocalName(),
				FinServ__FinancialAccount__c.FinServ__Status__c.getDescribe().getLocalName(),
				FinServ__FinancialAccount__c.Name.getDescribe().getLocalName()
		};
	}

	/**
	 * @description Retrieves the financial accounts corresponding to the given contract numbers.
	 *
	 * @param accountNumbers a set of contract numbers
	 *
	 * @return a list of items
	 */
	public static List<FinServ__FinancialAccount__c> findByAccountNumber(Set<String> accountNumbers)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_FINANCIAL_ACCOUNT_NUMBER, accountNumbers, getDefaultFields());
	}

	/**
	 * @description Retrieves a financial account corresponding to the given account number
	 *
	 * @param accountNumber Number against which to search
	 *
	 * @return Null or found Item
	 */
	public static FinServ__FinancialAccount__c findByAccountNumber(String accountNumber)
	{
		return (FinServ__FinancialAccount__c)CMN_DAL_SObjectSelector.findByField
				(OBJECT_NAME, FIELD_FINANCIAL_ACCOUNT_NUMBER, accountNumber, getDefaultFields(), true);
	}

	/**
	 * @description Retrieves the financial accounts corresponding to the given AccountID.
	 *
	 * @param accountId The account to filter financial accounts against
	 *
	 * @return a list of items
	 */
	public static List<FinServ__FinancialAccount__c> findByMasterAccountId(Id accountId)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_MASTER_ACCOUNT, new Set<Id> {accountId}, getDefaultFields());
	}

	/**
	 * @description Will return all FinancialAccounts created by unit tests
	 *
	 * @return A list of FinancialAccounts
	 */
	@TestVisible
	private static List<FinServ__FinancialAccount__c> getAll()
	{
		return CMN_DAL_Search.getAll(OBJECT_NAME, getDefaultFields());
	}

	/**
	 * @description Retrieves the Financial Account by Id.
	 *
	 * @param financialAccountIds a set of policy ids
	 *
	 * @return a list of items
	 */
	public static List<FinServ__FinancialAccount__c> findById(Set<Id> financialAccountIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, financialAccountIds, getDefaultFields());
	}

	/**
	 * @description Will find a financial account by Id
	 *
	 * @param financialAccountId The Id of the account
	 *
	 * @return Either the item found or null
	 */
	public static FinServ__FinancialAccount__c findById(Id financialAccountId)
	{
		return (FinServ__FinancialAccount__c)CMN_DAL_SObjectSelector.findById(OBJECT_NAME, financialAccountId, getDefaultFields());
	}
}