objects/Account.object
<CustomObject>
    <fields>
        <fullName>SLI_KnowYourCustomerCategory__c</fullName>
        <description>Account Know Your Customer Category</description>
        <label>KYC Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RSA Citizen</fullName>
                </value>
                <value>
                    <fullName>Permanent Resident</fullName>
                </value>
                <value>
                    <fullName>Emigrant</fullName>
                </value>
                <value>
                    <fullName>Foreign Citizen</fullName>
                </value>
                <value>
                    <fullName>RSA Close Corporation</fullName>
                </value>
                <value>
                    <fullName>RSA Company</fullName>
                </value>
                <value>
                    <fullName>Foreign Company</fullName>
                </value>
                <value>
                    <fullName>Other Legal Person</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Retirement Fund</fullName>
                </value>
                <value>
                    <fullName>Medical Scheme</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Public Entity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>RSC_ServiceType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the type of service requested</description>
        <label>Service Type</label>
        <referenceTo>SC_ServiceType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMN_WebserviceCallQueue__c.object
<CustomObject>
    <description>A object which is used to orchestrate and track webservices (inbound and outbound). By injecting an item into this object will asynchronously manage a call to external web service.</description>
    <label>Webservice Call Queue</label>
    <nameField>
        <displayFormat>WCQ-{0000000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Calls Queue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DocumentChecklistItem.object
<CustomObject>
    <fields>
        <fullName>AW_DateVaulted__c</fullName>
        <description>This field will indicate the date the documents had been vaulted</description>
        <label>Date Vaulted</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SC_ServiceType__c.object
<CustomObject>
    <description>Custom object created for Servicing Console app for the various service types</description>
    <fields>
        <fullName>SC_ServiceType__c</fullName>
        <description>This field stores the Service Type Code</description>
        <label>Service Type</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SLC_API_UploadDocumentToVault_TEST.cls
/**
 * @description Test class for SLC_API_UploadDocumentToVault
 *
 * @author Futureform
 *
 * @date October 2022
 */
@IsTest
private class SLC_API_UploadDocumentToVault_TEST {
    private static final Integer NUMBER_OF_ITEMS_TO_CREATE = 1;

    /**
     * @description Create data required for the unit test
     *
     * @param aUser the user with which data should be created
     *
     * @return a newly inserted item
     */
    private static DocumentChecklistItem createData(User aUser)
    {
        Account personMasterAccount = AW_DAL_TestDataFactory.createMasterPersonAccount().iterator().next();

        Account newAccount = new Account();
        newAccount.Id = personMasterAccount.Id;
        newAccount.OwnerId = aUser.Id;
        update newAccount;
        
        DocumentChecklistItem checklistItem;
        SC_ServiceType__c newServiceType = SC_DAL_DataFactory.createServiceTypesWithAssignableValue(NUMBER_OF_ITEMS_TO_CREATE, true).iterator().next();
        System.runAs(aUser)
        {
            Case caseRecord = SC_DAL_DataFactory.newCase(personMasterAccount.Id);
            caseRecord.RSC_ServiceType__c = newServiceType.Id;
            insert caseRecord;

            checklistItem =  SC_DAL_DataFactory.newDocumentCheckListItems(personMasterAccount.Id, NUMBER_OF_ITEMS_TO_CREATE).iterator().next();
            checklistItem.OwnerId = aUser.Id;
            insert checklistItem;
        }

        return checklistItem;
    }

    /**
     * @description Check successfull Call
     *
     * @see SLC_API_UploadDocumentToVault.populate
     */
    @IsTest
    private static void successfulCall1()
    {
        Account newAccount = AW_DAL_TestDataFactory.createMasterPersonAccount().iterator().next();
        DocumentChecklistItem checklistItem = SC_DAL_DataFactory.insertDocumentCheckListItems(newAccount.Id, NUMBER_OF_ITEMS_TO_CREATE).iterator().next();
        RSC_DAL_TestDataFactory.createNewContentVersion(NUMBER_OF_ITEMS_TO_CREATE, checklistItem.Id);

        CMN_API_RestBaseOutboundTestHelper.successfulCall(SLC_API_UploadDocumentToVault.SERVICE_NAME, checklistItem.Id);
    }
    
    /**
     * @description Check successfull Call
     *
     * @see SLC_API_UploadDocumentToVault.populate
     */
    @IsTest
    private static void successfulCall2()
    {
        Account newAccount = AW_DAL_TestDataFactory.createMasterPersonAccount().iterator().next();
        DocumentChecklistItem checklistItem = SC_DAL_DataFactory.insertDocumentCheckListItems(newAccount.Id, NUMBER_OF_ITEMS_TO_CREATE).iterator().next();
        checklistItem.AW_DateVaulted__c = null;
        update checklistItem;
        RSC_DAL_TestDataFactory.createNewContentVersion(NUMBER_OF_ITEMS_TO_CREATE, checklistItem.Id);

        CMN_API_RestBaseOutboundTestHelper.successfulCall(SLC_API_UploadDocumentToVault.SERVICE_NAME, checklistItem.Id);
    }
    
    /**
     * @description Check successfull Call
     *
     * @see SLC_API_UploadDocumentToVault.populate
     */
    @IsTest
    private static void successfulCall3()
    {
        Id busAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Stanlib Institutional Account').getRecordTypeId();        
        Account busAcc = new Account(
        	Name = 'TestBusAcc123',
            RecordTypeId = busAccRecordTypeId,
            SLI_KnowYourCustomerCategory__c = 'RSA Company',
            AccountNumber='4474'
        );
        insert busAcc;
        
        DocumentChecklistItem checklistItem = SC_DAL_DataFactory.insertDocumentCheckListItems(busAcc.Id, NUMBER_OF_ITEMS_TO_CREATE).iterator().next();

        RSC_DAL_TestDataFactory.createNewContentVersion(NUMBER_OF_ITEMS_TO_CREATE, checklistItem.Id);

        CMN_API_RestBaseOutboundTestHelper.successfulCall(SLC_API_UploadDocumentToVault.SERVICE_NAME, checklistItem.Id);
    }

    /**
     * @description Check that the service abort if the ContentVersion is not linked to the documentChecklistItem
     *
     * @see SLC_API_UploadDocumentToVault.abortRequest
     */
    @IsTest
    private static void abortedCallForNoContentVersion()
    {
        Account newAccount = AW_DAL_TestDataFactory.createMasterPersonAccount().iterator().next();
        DocumentChecklistItem checklistItem = SC_DAL_DataFactory.insertDocumentCheckListItems(newAccount.Id, NUMBER_OF_ITEMS_TO_CREATE).iterator().next();

        CMN_API_RestBaseOutboundTestHelper.abortedCall(SLC_API_UploadDocumentToVault.SERVICE_NAME, checklistItem.Id);
    }

    /**
     * @description Check that the service abort if the Id provided does not find a documentChecklistItem
     *
     * @see SLC_API_UploadDocumentToVault.abortRequest
     */
    @IsTest
    private static void abortedCallNoItemFound()
    {
        CMN_API_RestBaseOutboundTestHelper.abortedCall(SLC_API_UploadDocumentToVault.SERVICE_NAME, UserInfo.getUserId());
    }

   /**
     * @description Emulates a failed call and checks that error message is not blank
     */
    @IsTest
    private static void failedCall()
    {
        User foundUser = AW_DAL_TestDataFactory.createTestUser(SC_DAL_Profile.PROFILE_SERVICE_AGENT, true);
        DocumentChecklistItem checklistItem = createData(foundUser);

        System.runAs(foundUser)
        {
            RSC_DAL_TestDataFactory.createNewContentVersion(NUMBER_OF_ITEMS_TO_CREATE, checklistItem.Id);
            CMN_WebserviceCallQueue__c queueItem = CMN_DAL_DataFactory.newOutboundWebserviceQueue
                    (
                            SLC_API_UploadDocumentToVault.SERVICE_NAME,
                            checklistItem.Id
                    );

            Test.startTest();

            CMN_API_HttpBaseOutboundMock.returnErrorResponse = true;

            SLC_API_UploadDocumentToVault handler =
                    (SLC_API_UploadDocumentToVault)CMN_FACTORY_WebserviceManager.execute(new List<CMN_WebserviceCallQueue__c> {queueItem}).iterator().next();

            Test.stopTest();

            System.assertEquals(true, handler.callResult.failed, 'Status invalid. Response Call Result JSON: ' + JSON.serialize(handler.callResult));
        }
    }
}