objects/Account.object
<CustomObject>
    <fields>
        <fullName>AW_Growth_Strategy__c</fullName>
        <description>The strategy the entity will adopt to enable growth to reach their target or goal</description>
        <label>Growth Strategy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AW_FNA__c.object
<CustomObject>
    <label>FNA</label>
    <nameField>
        <displayFormat>FNA-{0000}</displayFormat>
        <label>FNA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FNA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AW_Planned_Solution__c.object
<CustomObject>
    <fields>
        <fullName>AW_Financial_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related to Financial Goal</description>
        <label>Goal Name</label>
        <referenceTo>FinServ__FinancialGoal__c</referenceTo>
        <relationshipLabel>Planned Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Growth_Strategy__c</fullName>
        <description>The growth strategy in brief</description>
        <label>Growth Strategy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Lumpsum_Amount__c</fullName>
        <description>The lumpsum amount of solution</description>
        <label>Lump Sum Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_Opportunity_Name__c</fullName>
        <description>The related opportunity</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Planned Solutions</relationshipLabel>
        <relationshipName>Planned_Solutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AW_PremiumFrequency__c</fullName>
        <description>How often the premium will be charged of the planned solution</description>
        <label>Premium Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AW_Frequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Premium_Amount__c</fullName>
        <description>Premium amount of the planned solution</description>
        <label>Premium Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Planned Solution</label>
    <nameField>
        <label>Planned Solution Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planned Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>AW_FNA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related FNA</description>
        <label>FNA</label>
        <referenceTo>AW_FNA__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Goal_Type__c</fullName>
        <description>Select Goal Type</description>
        <label>Goal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Growth_Strategy__c</fullName>
        <description>Short description of Growth Strategy</description>
        <label>Growth Strategy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Shortfall__c</fullName>
        <description>This field calculates the Shortfall/Surplus value which is the Target Value - Actual Value. The amount required to meet the target amount/ the amount exceeding the target amount</description>
        <formula>FinServ__ActualValue__c - FinServ__TargetValue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shortfall/Surplus</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__ActualValue__c</fullName>
        <inlineHelpText>The value of the asset allocated to the Goal - This is pre-populated when linking a Financial Account to a goal.</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetValue__c</fullName>
        <inlineHelpText>The target value that you would like to reach for this specific goal.</inlineHelpText>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>AW_Planned_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planned Solution</label>
        <referenceTo>AW_Planned_Solution__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>436</fullName>
                    <label>GateWay ProductGroup</label>
                </value>
                <value>
                    <fullName>445</fullName>
                    <label>Liberty Retirement Annuity</label>
                </value>
                <value>
                    <fullName>432</fullName>
                    <label>Evolve Investment Plan</label>
                </value>
                <value>
                    <fullName>433</fullName>
                    <label>Evolve Retirement Annuity</label>
                </value>
                <value>
                    <fullName>435</fullName>
                    <label>Evolve Investment Plan(Sinking Fund)</label>
                </value>
                <value>
                    <fullName>405</fullName>
                    <label>Flexible Investment Plan</label>
                </value>
                <value>
                    <fullName>406</fullName>
                    <label>Flexible Investment Plan Sinking Fund</label>
                </value>
                <value>
                    <fullName>251</fullName>
                    <label>Investment Plan</label>
                </value>
                <value>
                    <fullName>252</fullName>
                    <label>Investment Plan with Income</label>
                </value>
                <value>
                    <fullName>258</fullName>
                    <label>Offshore Investment Plan</label>
                </value>
                <value>
                    <fullName>412</fullName>
                    <label>Investment Builder</label>
                </value>
                <value>
                    <fullName>413</fullName>
                    <label>Investment Linked Repayment Option</label>
                </value>
                <value>
                    <fullName>415</fullName>
                    <label>Retirement Annuity Builder</label>
                </value>
                <value>
                    <fullName>414</fullName>
                    <label>Education Builder</label>
                </value>
                <value>
                    <fullName>264</fullName>
                    <label>Lifestyle Protector</label>
                </value>
                <value>
                    <fullName>446</fullName>
                    <label>Liberty Pension/Provident Preserver</label>
                </value>
                <value>
                    <fullName>434</fullName>
                    <label>Evolve Pension/Provident Preserver</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Guaranteed Income Annuity</label>
                </value>
                <value>
                    <fullName>186</fullName>
                    <label>Guaranteed Investment Plan with Income</label>
                </value>
                <value>
                    <fullName>47</fullName>
                    <label>Life Annuity</label>
                </value>
                <value>
                    <fullName>239</fullName>
                    <label>Life Annuity with Inflation Protection</label>
                </value>
                <value>
                    <fullName>185</fullName>
                    <label>Guaranteed Investment Plan</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Quote_Solution_Number__c</fullName>
        <externalId>true</externalId>
        <label>Quote Solution Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/AW_Frequency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <customValue>
        <fullName>BiAnnually</fullName>
        <label>Bi-Annually</label>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <description>This picklist contains the Frequency values sets used by the premium frequency fields.</description>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

classes/AW_BPOCanvasLifecycleHandler_TEST.cls
/**
 * @description This class is the apex test class for the class AW_BPOCanvasLifecycleHandler
 *
 * @see AW_BPOCanvasLifecycleHandler
 *
 * @author pavan.t@lntinfotech.com kiran.kumaryelisetti@lntinfotech.com vishakha.saini@accenture.com
 *
 * @date November 2020, March 2023, July 2023
 */
@IsTest(SeeAllData=false IsParallel=true)
private class AW_BPOCanvasLifecycleHandler_TEST
{
	private static final String QUOTE_EXTERNAL_ID = '123456789';
	private static final String RISK_FINANCIAL_GOAL_NAME = 'Life Cover';
	private static final String PRODUCT_TYPE_LIFE_ANNUITY = '47';

	/**
	 * @description This setup test method prepares the data for the test methods
	 */
	@TestSetup
	private static void testSetup()
	{
		Account newAccount = AW_DAL_TestDataFactory.createClientAccount().iterator().next();

		AW_DAL_TestDataFactory.createDefaultOpportunities(newAccount, 1);

		List<AW_FNA__c> listFNA = AW_DAL_TestDataFactory.createFNA(newAccount.Id, 1);

		FinServ__FinancialGoal__c goal = AW_DAL_TestDataFactory.createGoals(newAccount.Id, 1).iterator().next();
		goal.AW_FNA__c = listFNA.iterator().next().Id;
		update goal;

		AW_DAL_TestDataFactory.createSolutions(goal.Id, 1);
	}

	/**
	 * @description This test method tests the Canvas Lifecycle Handler with overwritten app values and
	 * overwritten environment values
	 */
	@IsTest
	@SuppressWarnings('ApexScopeAgreement, PMD.ApexUnitTestClassShouldHaveRunAs')
	private static void testCanvasLifecycleHandlerOverriddenValues()
	{
		AW_Planned_Solution__c plannedSolution = AW_DAL_PlannedSolution.getAll().iterator().next();
		Quote newQuote = AW_DAL_TestDataFactory.createQuoteWithQuoteNumber(plannedSolution.AW_Opportunity_Name__r.Id, QUOTE_EXTERNAL_ID, true);
		newQuote.AW_Product_Type__c = PRODUCT_TYPE_LIFE_ANNUITY;
		update newQuote;

		//        Set some application context data in a Map
		Map<String, String> appValues = new Map<String, String>();
		appValues.put(Canvas.Test.KEY_NAMESPACE, 'alternateNamespace');
		appValues.put(Canvas.Test.KEY_VERSION, '3.0');

		//        Set some environment context data in a Map
		Map<String, String> envValues = new Map<String, String>();
		envValues.put(Canvas.Test.KEY_DISPLAY_LOCATION, 'Chatter');
		envValues.put(Canvas.Test.KEY_LOCATION_URL, 'https://yourInstance.salesforce.com/_ui/core/chatter/ui/ChatterPage');

		AW_BPOCanvasLifecycleHandler handler = new AW_BPOCanvasLifecycleHandler();
		//        Create a mock RenderContext using the test application and environment context data Maps
		Canvas.RenderContext mock = Canvas.Test.mockRenderContext(appValues, envValues);

		//        Set custom params on the mock RenderContext
		Map<String, Object> mockParams = new Map<String, String>();
		mockParams.put('plannedSolutionId', plannedSolution.Id);
		mockParams.put('quoteSolutionNumber', newQuote.AW_Quote_Solution_Number__c);
		mock.getEnvironmentContext().setParametersAsJSON(JSON.serialize(mockParams));
		Canvas.Test.testCanvasLifecycle(handler, mock);

		Map<String, Object> finalParams = (Map<String, Object>)JSON.deserializeUntyped(mock.getEnvironmentContext().getParametersAsJSON());

		Assert.areEqual(finalParams.get('clientFirstName'), plannedSolution.AW_Opportunity_Name__r.Account.FirstName, 'Client first name should be equal');
		Assert.areEqual(finalParams.get('clientLastName'), plannedSolution.AW_Opportunity_Name__r.Account.LastName, 'Client last name should be equal');
		Assert.areEqual(finalParams.get('clientRetirementAge'), plannedSolution.AW_Opportunity_Name__r.Account.Retirement_Age__pc, 'Client retirement age should be equal');
		Assert.areEqual(finalParams.get('clientIdPassportNumber'),
				plannedSolution.AW_Opportunity_Name__r.Account.AW_IdentificationNumber__pc, 'Client identification number shoulld be equal');
		Assert.areEqual(finalParams.get('solutionLumpsumAmount'), plannedSolution.AW_Lumpsum_Amount__c, 'Lumpsum amount should be equal');
		Assert.areEqual(finalParams.get('solutionGrowthStrategy'), plannedSolution.AW_Growth_Strategy__c, 'Growth Strategy should be equal');
		Assert.areEqual(finalParams.get('solutionPremiumAmount'), plannedSolution.AW_Premium_Amount__c, 'Premium amount should be equal');
		Assert.areEqual(finalParams.get('solutionPremiumFrequency'), plannedSolution.AW_PremiumFrequency__c, 'Premium frequency should be equal');

	}

	@IsTest
	@SuppressWarnings('ApexScopeAgreement, PMD.ApexUnitTestClassShouldHaveRunAs')
	private static void testCanvasLifecycleHandlerForNullQuoteSolutionNumber()
	{
		AW_Planned_Solution__c plannedSolution = AW_DAL_PlannedSolution.getAll().iterator().next();
		AW_DAL_TestDataFactory.createQuoteWithQuoteNumber(plannedSolution.AW_Opportunity_Name__r.Id, QUOTE_EXTERNAL_ID, true);
		FinServ__FinancialGoal__c financialGoal = AW_DAL_FinancialGoal.findById(plannedSolution.AW_Financial_Goal__c);
		financialGoal.Name = RISK_FINANCIAL_GOAL_NAME;
		financialGoal.AW_Goal_Type__c = AW_DAL_FinancialGoal.PICK_RISK_GOAL_TYPE;
		financialGoal.FinServ__ActualValue__c = Decimal.valueOf(CMN_DAL_SObjectDomain.generateRandomNumber(4));
		financialGoal.FinServ__TargetValue__c = Decimal.valueOf(CMN_DAL_SObjectDomain.generateRandomNumber(5));
		update financialGoal;
		//        Set some application context data in a Map
		Map<String, String> appValues = new Map<String, String>();
		appValues.put(Canvas.Test.KEY_NAMESPACE, 'alternateNamespace');
		appValues.put(Canvas.Test.KEY_VERSION, '3.0');

		//        Set some environment context data in a Map
		Map<String, String> envValues = new Map<String, String>();
		envValues.put(Canvas.Test.KEY_DISPLAY_LOCATION, 'Chatter');
		envValues.put(Canvas.Test.KEY_LOCATION_URL, 'https://yourInstance.salesforce.com/_ui/core/chatter/ui/ChatterPage');

		AW_BPOCanvasLifecycleHandler handler = new AW_BPOCanvasLifecycleHandler();
		//        Create a mock RenderContext using the test application and environment context data Maps
		Canvas.RenderContext mock = Canvas.Test.mockRenderContext(appValues, envValues);

		//        Set custom params on the mock RenderContext
		Map<String, Object> mockParams = new Map<String, String>();
		mockParams.put('plannedSolutionId', plannedSolution.Id);
		mockParams.put('quoteSolutionNumber', null);
		mock.getEnvironmentContext().setParametersAsJSON(JSON.serialize(mockParams));
		Canvas.Test.testCanvasLifecycle(handler, mock);
		Set<Canvas.ContextTypeEnum> excludedAttributes = handler.excludeContextTypes();

		Map<String, Object> finalParams = (Map<String, Object>)JSON.deserializeUntyped(mock.getEnvironmentContext().getParametersAsJSON());
		Assert.areEqual(finalParams.get('isRiskGoalSync'), true, 'Risk goal sync flag should be true');
		Assert.areEqual(finalParams.get('quoteSolutionNumber'), '0', 'Quote solutinon number should be 0');
		FinServ__FinancialGoal__c foundGoal = AW_DAL_FinancialGoal.findById(financialGoal.Id);
		Assert.areEqual(finalParams.get('shortFallorSurpLusAmount'), foundGoal.AW_Shortfall__c < 0 ?
				'' + foundGoal.Name.deleteWhitespace() + ':' + foundGoal.AW_Shortfall__c + '' : '0', 'Shortfall/Surplus amount should match');
		Assert.areEqual(0, excludedAttributes.size(), 'Excluded attributes should be empty');

	}
}