objects/Account.object
<CustomObject>
    <fields>
        <fullName>AW_ParentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the clients master record</description>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLI_AlternateOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates alternate Client Fund Manager responsible for servicing the Institutional Account.</description>
        <label>Alternate Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLI_ClientClassification__c</fullName>
        <description>Institutional client classification eg. &quot;Multi Manager, Africa-Unit Trust&quot;</description>
        <label>Client Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Africa – Segregated</fullName>
                </value>
                <value>
                    <fullName>Africa – Unit Trust</fullName>
                </value>
                <value>
                    <fullName>CCS - Segregated</fullName>
                </value>
                <value>
                    <fullName>CCS - Unit Trust – Money Market</fullName>
                </value>
                <value>
                    <fullName>CCS - Unit Trust – Non-Money Market</fullName>
                </value>
                <value>
                    <fullName>ID - Segregated</fullName>
                </value>
                <value>
                    <fullName>ID - Unit Trust – Money Market</fullName>
                </value>
                <value>
                    <fullName>ID - Unit Trust – Non-Money Market</fullName>
                </value>
                <value>
                    <fullName>Liberty</fullName>
                </value>
                <value>
                    <fullName>Multi-Manager</fullName>
                </value>
                <value>
                    <fullName>Retail - Wholesale</fullName>
                </value>
                <value>
                    <fullName>White Label - Noble</fullName>
                </value>
                <value>
                    <fullName>White Label - Melville Douglas</fullName>
                </value>
                <value>
                    <fullName>ID - Recognition</fullName>
                </value>
                <value>
                    <fullName>Corporate Cash</fullName>
                </value>
                <value>
                    <fullName>Institutional</fullName>
                </value>
                <value>
                    <fullName>DFM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLR_Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Independent Financial Advisor</fullName>
                </value>
                <value>
                    <fullName>Liberty Agent</fullName>
                </value>
                <value>
                    <fullName>Liberty Entrepreneurs</fullName>
                </value>
                <value>
                    <fullName>Linked Companies</fullName>
                </value>
                <value>
                    <fullName>Other Bank Branches</fullName>
                </value>
                <value>
                    <fullName>SBSA Bank Branches</fullName>
                </value>
                <value>
                    <fullName>Standard Bank Financial Consultant (SBFC)</fullName>
                </value>
                <value>
                    <fullName>Stanfin Africa</fullName>
                </value>
                <value>
                    <fullName>Wealth and Investments</fullName>
                </value>
                <value>
                    <fullName>SBFC Call Centre</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
                <value>
                    <fullName>Strategic Partners</fullName>
                </value>
                <value>
                    <fullName>CRM Contact Types/Channels</fullName>
                    <isActive>false</isActive>
                    <label>CRM Contact Types/Channels</label>
                </value>
                <value>
                    <fullName>IFA Broker Division</fullName>
                    <isActive>false</isActive>
                    <label>IFA Broker Division</label>
                </value>
                <value>
                    <fullName>LISP</fullName>
                    <isActive>false</isActive>
                    <label>LISP</label>
                </value>
                <value>
                    <fullName>Liberty Agency</fullName>
                    <isActive>false</isActive>
                    <label>Liberty Agency</label>
                </value>
                <value>
                    <fullName>Liberty Franchise</fullName>
                    <isActive>false</isActive>
                    <label>Liberty Franchise</label>
                </value>
                <value>
                    <fullName>Wholesale - FOF</fullName>
                    <isActive>false</isActive>
                    <label>Wholesale - FOF</label>
                </value>
                <value>
                    <fullName>Wholesale -IFA</fullName>
                    <isActive>false</isActive>
                    <label>Wholesale -IFA</label>
                </value>
                <value>
                    <fullName>Wholeseale - Corporate</fullName>
                    <isActive>false</isActive>
                    <label>Wholeseale - Corporate</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLR_MannedUnmanned__c</fullName>
        <description>STANLIB BDM Advisor has Manned or Unmanned status</description>
        <label>Manned/Unmanned</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manned</fullName>
                </value>
                <value>
                    <fullName>Unmanned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SLC_Client_Experience_Teams__mdt.object
<CustomObject>
    <description>DFM, Institutional and Corporate Cash servicing teams (Your Client Experience Team section)</description>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <label>Client Classification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Cash</fullName>
                    <default>true</default>
                    <label>Corporate Cash</label>
                </value>
                <value>
                    <fullName>Institutional</fullName>
                </value>
                <value>
                    <fullName>DFM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_User_Id__c</fullName>
        <description>The user id of the member</description>
        <inlineHelpText>The user id of the member</inlineHelpText>
        <label>Member User Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client Experience Team</label>
    <pluralLabel>Client Experience Teams</pluralLabel>
</CustomObject>

objects/SLC_Escalation_Teams__mdt.object
<CustomObject>
    <description>DFM, Institutional and Corporate Cash servicing teams (Your Escalation Team section)</description>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <label>Client Classification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <default>true</default>
                    <label>Institutional</label>
                </value>
                <value>
                    <fullName>Corporate Cash</fullName>
                </value>
                <value>
                    <fullName>DFM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_User_Id__c</fullName>
        <description>The user id of the member</description>
        <inlineHelpText>The user id of the member</inlineHelpText>
        <label>Member User Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Escalation Teams</label>
    <pluralLabel>Escalation Teams</pluralLabel>
</CustomObject>

objects/SLC_Unmanned_Contact__mdt.object
<CustomObject>
    <description>If portal user is unmanned, display these users in portal</description>
    <fields>
        <fullName>Member_User_Id__c</fullName>
        <label>Member User Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Unmanned Contact</label>
    <pluralLabel>Unmanned Contacts</pluralLabel>
</CustomObject>

classes/SLC_CTRL_YourServicingTeam.cls
/**
 * @description Controller for the Your Servicing Team LWC
 *
 * @author Futureform
 *
 * @date October 2022
 */
public without sharing class SLC_CTRL_YourServicingTeam {
    
    @AuraEnabled
    public static Account getAccountDetails(String userAccountId){
        Account personAccount = [SELECT Id, Name, SLR_Channel__c, SLR_MannedUnmanned__c,AW_ParentAccount__c, OwnerId,
                                 Owner.FirstName, Owner.LastName, Owner.FullPhotoUrl, Owner.Email, Owner.Phone, Owner.Title,
                                 AW_ParentAccount__r.SLI_ClientClassification__c, AW_ParentAccount__r.SLI_AlternateOwner__c,
                                 AW_ParentAccount__r.SLI_AlternateOwner__r.FirstName, AW_ParentAccount__r.SLI_AlternateOwner__r.LastName,
                                 AW_ParentAccount__r.SLI_AlternateOwner__r.FullPhotoUrl, AW_ParentAccount__r.SLI_AlternateOwner__r.Email,
                                 AW_ParentAccount__r.SLI_AlternateOwner__r.Phone, AW_ParentAccount__r.SLI_AlternateOwner__r.Title
                                 FROM Account WHERE Id =: userAccountId];        
        return personAccount;
    }
    
    @AuraEnabled
    public static List<User> getUnmannedContacts(){   
        List<SLC_Unmanned_Contact__mdt> members = [SELECT Id, Member_User_Id__c FROM SLC_Unmanned_Contact__mdt];
        
        List<String> userIds = new List<String>();        
        for(SLC_Unmanned_Contact__mdt membs : members){
            userIds.add(membs.Member_User_Id__c);
        }
        
        List<User> unmannedUsers = [SELECT Id, FirstName, LastName, Name, FullPhotoUrl, Email, Title, Phone FROM User
                                	WHERE Id IN : userIds ORDER BY FirstName];
		        
        return unmannedUsers;        
    }   
         
    @AuraEnabled
    public static List<User> getClientExpTeam(String teamName){   
        List<SLC_Client_Experience_Teams__mdt> teammembers = [SELECT Id, Client_Classification__c, Member_User_Id__c 
                                                  FROM SLC_Client_Experience_Teams__mdt  
                                                  WHERE Client_Classification__c =: teamName];
        
        List<String> userIds = new List<String>();        
        for(SLC_Client_Experience_Teams__mdt membs : teammembers){
            userIds.add(membs.Member_User_Id__c);
        }
        
        List<User> teamUsers = [SELECT Id, FirstName, LastName, Name, FullPhotoUrl, Email, Title, Phone FROM User
                                WHERE Id IN : userIds ORDER BY FirstName];
		        
        return teamUsers;        
    }   
    
    @AuraEnabled
    public static List<User> getEscalationTeam(String teamName){   
        List<SLC_Escalation_Teams__mdt> teammembers = [SELECT Id, Client_Classification__c, Member_User_Id__c 
                                                    FROM SLC_Escalation_Teams__mdt
                                                    WHERE Client_Classification__c =: teamName];
        
        List<String> userIds = new List<String>();        
        for(SLC_Escalation_Teams__mdt membs : teammembers){
            userIds.add(membs.Member_User_Id__c);
        }
        
        List<User> teamUsers = [SELECT Id, FirstName, LastName, Name, FullPhotoUrl, Email, Title, Phone FROM User
                                WHERE Id IN : userIds ORDER BY FirstName];      
		        
        return teamUsers;        
    }   

}