objects/Account.object
<CustomObject>
    <fields>
        <fullName>AW_ParentAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the clients master record</description>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLI_KnowYourCustomerCategory__c</fullName>
        <description>Account Know Your Customer Category</description>
        <label>KYC Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RSA Citizen</fullName>
                </value>
                <value>
                    <fullName>Permanent Resident</fullName>
                </value>
                <value>
                    <fullName>Emigrant</fullName>
                </value>
                <value>
                    <fullName>Foreign Citizen</fullName>
                </value>
                <value>
                    <fullName>RSA Close Corporation</fullName>
                </value>
                <value>
                    <fullName>RSA Company</fullName>
                </value>
                <value>
                    <fullName>Foreign Company</fullName>
                </value>
                <value>
                    <fullName>Other Legal Person</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Retirement Fund</fullName>
                </value>
                <value>
                    <fullName>Medical Scheme</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Public Entity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLR_MannedUnmanned__c</fullName>
        <description>STANLIB BDM Advisor has Manned or Unmanned status</description>
        <label>Manned/Unmanned</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manned</fullName>
                </value>
                <value>
                    <fullName>Unmanned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SLC_Client_Experience_Teams__mdt.object
<CustomObject>
    <description>DFM, Institutional and Corporate Cash servicing teams (Your Client Experience Team section)</description>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <label>Client Classification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate Cash</fullName>
                    <default>true</default>
                    <label>Corporate Cash</label>
                </value>
                <value>
                    <fullName>Institutional</fullName>
                </value>
                <value>
                    <fullName>DFM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_User_Id__c</fullName>
        <description>The user id of the member</description>
        <inlineHelpText>The user id of the member</inlineHelpText>
        <label>Member User Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Client Experience Team</label>
    <pluralLabel>Client Experience Teams</pluralLabel>
</CustomObject>

objects/SLC_Escalation_Teams__mdt.object
<CustomObject>
    <description>DFM, Institutional and Corporate Cash servicing teams (Your Escalation Team section)</description>
    <fields>
        <fullName>Client_Classification__c</fullName>
        <label>Client Classification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Institutional</fullName>
                    <default>true</default>
                    <label>Institutional</label>
                </value>
                <value>
                    <fullName>Corporate Cash</fullName>
                </value>
                <value>
                    <fullName>DFM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_User_Id__c</fullName>
        <description>The user id of the member</description>
        <inlineHelpText>The user id of the member</inlineHelpText>
        <label>Member User Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Escalation Teams</label>
    <pluralLabel>Escalation Teams</pluralLabel>
</CustomObject>

objects/SLC_Unmanned_Contact__mdt.object
<CustomObject>
    <description>If portal user is unmanned, display these users in portal</description>
    <fields>
        <fullName>Member_User_Id__c</fullName>
        <label>Member User Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Unmanned Contact</label>
    <pluralLabel>Unmanned Contacts</pluralLabel>
</CustomObject>

classes/SLC_CTRL_YourServicingTeam_TEST.cls
/**
 * @description Test class for the controller of the Your Servicing Team LWC
 *
 * @see SLC_CTRL_YourServicingTeam
 *
 * @author Futureform
 *
 * @date October 2022
 */
@isTest
private class SLC_CTRL_YourServicingTeam_TEST {
    
    @IsTest
    private static void testGetAccountDetails(){
        Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Stanlib Institutional Person Account').getRecordTypeId();
        Id busAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Stanlib Institutional Account').getRecordTypeId();
        
        Account busAcc = new Account(
        	Name = 'Test Parent Acc 123',
            RecordTypeId = busAccRecordTypeId,
            SLI_KnowYourCustomerCategory__c = 'RSA Company'
        );
        insert busAcc;
        
        Account personAcc = new Account(
            LastName = 'Test', 
            RecordTypeId = personAccRecordTypeId, 
            SLR_MannedUnmanned__c = 'Manned',
            AW_ParentAccount__c = busAcc.Id
        );
        insert personAcc;
        
        test.startTest();
        Account personAccount = SLC_CTRL_YourServicingTeam.getAccountDetails(personAcc.Id);
        test.stopTest();
        
        System.assertEquals(busAcc.Id, personAccount.AW_ParentAccount__c, 'Correct Account details not returned');
             
    }
    
    @IsTest
    private static void testGetUnmannedContacts(){
        List<User> unmannedList = SLC_CTRL_YourServicingTeam.getUnmannedContacts();
        
        if(unmannedList.size() > 0){
            List<SLC_Unmanned_Contact__mdt> members = [SELECT Id, Member_User_Id__c FROM SLC_Unmanned_Contact__mdt WHERE Member_User_Id__c =: unmannedList[0].Id];
            
            System.assertEquals(1, members.size(), 'No records in SLC_Unmanned_Contact__mdt');
        }   
                   
    }
    
    @IsTest
    private static void testGetClientExpTeam(){
        List<User> servicingList = SLC_CTRL_YourServicingTeam.getClientExpTeam('Institutional');
        
        if(servicingList.size() > 0){
            List<SLC_Client_Experience_Teams__mdt> members = [SELECT Id, Member_User_Id__c FROM SLC_Client_Experience_Teams__mdt WHERE Member_User_Id__c =: servicingList[0].Id AND Client_Classification__c = 'Institutional'];
            
            System.assertEquals(1, members.size(), 'No Institutional team in SLC_Client_Experience_Teams__mdt');            
        }
    }
    
    
    @IsTest
    private static void testGetEscalationTeam(){
        List<User> escalationList = SLC_CTRL_YourServicingTeam.getEscalationTeam('Institutional');
        
        if(escalationList.size() > 0){
            List<SLC_Escalation_Teams__mdt> members = [SELECT Id, Member_User_Id__c FROM SLC_Escalation_Teams__mdt WHERE Member_User_Id__c =: escalationList[0].Id AND Client_Classification__c = 'Institutional'];
            
            system.assertEquals(1, members.size(), 'No Institutional team in SLC_Escalation_Teams__mdt');            
        }        
    }

}