objects/Account.object
<CustomObject>
    <fields>
        <fullName>AW_AUMSourceExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The external ID of the Assets Under Management source system</description>
        <externalId>true</externalId>
        <label>AUM Source External Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>AW_AUMSourceExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Asset Under Management Unique External ID</description>
        <externalId>true</externalId>
        <label>AUM Source External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AW_CurrentValue__c</fullName>
        <description>This indicates the current value of the financial account</description>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_NetContribution__c</fullName>
        <description>Net amount of contribution</description>
        <label>Net Contribution</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_ValueAsAt__c</fullName>
        <description>This field is used to capture the date time for the Current Value from Full View</description>
        <label>Value As At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FinServ__Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Household that this financial account rolls up to.</description>
        <label>Household</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Household Financial Accounts</relationshipLabel>
        <relationshipName>HouseholdFinancialAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__LastUpdated__c</fullName>
        <label>Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLSC_EntityNumber__c</fullName>
        <label>Entity Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialHolding__c.object
<CustomObject>
    <description>A holding within a client&apos;s investment account.</description>
    <fields>
        <fullName>AW_AUMSourceExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The external ID of the Assets Under Management source system</description>
        <externalId>true</externalId>
        <label>AUM Source External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AW_CurrentValue__c</fullName>
        <description>This field is used to track and store the monetary value associated with a particular financial holding record</description>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_NetContribution__c</fullName>
        <description>This field is used to store the net contribution amount associated with a particular financial holding or investment</description>
        <label>Net Contribution</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_Product_Code__c</fullName>
        <description>This field is designed to store a specific product code or identifier associated with the financial holding</description>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_SellingPrice__c</fullName>
        <description>This field is designed to store monetary values such as the price at which a financial holding is being sold or transferred</description>
        <label>Selling Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_SharePercentage__c</fullName>
        <description>This field is used to store and track the percentage of share that is attributed to a specific entity or individual within the financial holding record</description>
        <label>Share Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_ValueAsAt__c</fullName>
        <description>This field is used to capture the date time for the current value from Full View.</description>
        <label>Value As At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FinServ__AssetCategoryName__c</fullName>
        <description>Market capitalization and investing style</description>
        <label>Asset Category Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Growth</fullName>
                </value>
                <value>
                    <fullName>Large Value</fullName>
                </value>
                <value>
                    <fullName>Large Blend</fullName>
                </value>
                <value>
                    <fullName>Small Growth</fullName>
                </value>
                <value>
                    <fullName>Small Value</fullName>
                </value>
                <value>
                    <fullName>Small Blend</fullName>
                </value>
                <value>
                    <fullName>Mid-Cap Growth</fullName>
                </value>
                <value>
                    <fullName>Mid-Cap Value</fullName>
                </value>
                <value>
                    <fullName>Mid-Cap Blend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__AssetCategory__c</fullName>
        <description>Subcategory of asset type.</description>
        <label>Asset Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U.S. Equity</fullName>
                </value>
                <value>
                    <fullName>Sector Equity</fullName>
                </value>
                <value>
                    <fullName>Allocation</fullName>
                </value>
                <value>
                    <fullName>International Equity</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                </value>
                <value>
                    <fullName>Commodities</fullName>
                </value>
                <value>
                    <fullName>Taxable Bond</fullName>
                </value>
                <value>
                    <fullName>Municipal Bond</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__AssetClass__c</fullName>
        <description>Major category of asset type.</description>
        <label>Asset Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equities</fullName>
                </value>
                <value>
                    <fullName>Fixed Income</fullName>
                </value>
                <value>
                    <fullName>Cash Equivalents</fullName>
                </value>
                <value>
                    <fullName>Alternative Investments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Holdings</relationshipLabel>
        <relationshipName>FinancialHoldings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FinServ__GainLoss__c</fullName>
        <description>Change in value since purchase.</description>
        <inlineHelpText>Change in value since purchase.</inlineHelpText>
        <label>Gain/Loss</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Household Financial Holdings</relationshipLabel>
        <relationshipName>HouseholdFinancialHoldings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__LastUpdated__c</fullName>
        <label>Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Holdings</relationshipLabel>
        <relationshipName>ClientFinancialHoldings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Holding</label>
    <nameField>
        <label>Financial Holding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Holdings</pluralLabel>
    <recordTypes>
        <fullName>CMN_LibertyFinancialHolding</fullName>
        <active>true</active>
        <description>Record type to be used for Integration with Compass &amp; Lifestyle.</description>
        <label>Liberty Financial Holding</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinServ__Securities__c.object
<CustomObject>
    <description>An asset that is part of a client&apos;s financial holding.</description>
    <fields>
        <fullName>FinServ__AssetCategoryName__c</fullName>
        <description>Market capitalization and investing style</description>
        <label>Asset Category Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Large Growth</fullName>
                </value>
                <value>
                    <fullName>Large Value</fullName>
                </value>
                <value>
                    <fullName>Large Blend</fullName>
                </value>
                <value>
                    <fullName>Small Growth</fullName>
                </value>
                <value>
                    <fullName>Small Value</fullName>
                </value>
                <value>
                    <fullName>Small Blend</fullName>
                </value>
                <value>
                    <fullName>Mid-Cap Growth</fullName>
                </value>
                <value>
                    <fullName>Mid-Cap Value</fullName>
                </value>
                <value>
                    <fullName>Mid-Cap Blend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__AssetCategory__c</fullName>
        <description>Subcategory of asset type.</description>
        <label>Asset Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U.S. Equity</fullName>
                </value>
                <value>
                    <fullName>Sector Equity</fullName>
                </value>
                <value>
                    <fullName>Allocation</fullName>
                </value>
                <value>
                    <fullName>International Equity</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                </value>
                <value>
                    <fullName>Commodities</fullName>
                </value>
                <value>
                    <fullName>Taxable Bond</fullName>
                </value>
                <value>
                    <fullName>Municipal Bond</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__AssetClass__c</fullName>
        <description>Major category of asset type.</description>
        <label>Asset Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equities</fullName>
                </value>
                <value>
                    <fullName>Fixed Income</fullName>
                </value>
                <value>
                    <fullName>Cash Equivalents</fullName>
                </value>
                <value>
                    <fullName>Alternative Investments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__LastUpdated__c</fullName>
        <label>Last Updated</label>
        <type>Date</type>
    </fields>
    <label>Securities</label>
    <nameField>
        <label>Symbol</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AW_DAL_FinancialHolding.cls
/**
 * @description Public class to return the record of Financial Holding
 *
 * @author jayanth.kumar.s@accenture.com jason.van.beukering@accenture.com
 *
 * @date 2019, January 2023
 */
public inherited sharing class AW_DAL_FinancialHolding
{
	private static final String FIELD_CURRENT_VALUE = FinServ__FinancialHolding__c.AW_CurrentValue__c.getDescribe().getLocalName();
	//TODO: Remove to SL DAL Class
	private static final String FIELD_FINANCIAL_ACCOUNT_ENTITY_NUMBER = 'FinServ__FinancialAccount__r.SLSC_EntityNumber__c';
	private static final String FIELD_FINANCIAL_ACCOUNT_PARENT_ACCOUNT_ID = 'FinServ__FinancialAccount__r.FinServ__PrimaryOwner__c';
	private static final String OBJECT_NAME = FinServ__FinancialHolding__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();

	/**
	 * @description stores the fieldAPIName of Product Code
	 */
	public static final String FIELD_PRODUCT_CODE = FinServ__FinancialHolding__c.AW_Product_Code__c.getDescribe().getLocalName();
	/**
	 * @description stores the aliased name of Current Value Field
	 */
	public static final String FIELD_SUM_CURRENT_VALUE = CMN_UTIL_String.lowerCase('Sum') + '_' + FIELD_CURRENT_VALUE;
	/**
	 * @description The record type is being used when creating financial holding records
	 */
	public static final String RT_LIBERTY_FINANCIAL_HOLDING = 'CMN_LibertyFinancialHolding';
	/**
	 * @description Liberty Financial Holding record type id that should be used
	 */
	public static final Id RT_LIBERTY_FINANCIAL_HOLDING_ID =
			CMN_DAL_SObjectDomain.getRecordTypeByDeveloperName(FinServ__FinancialHolding__c.SObjectType, AW_DAL_FinancialHolding.RT_LIBERTY_FINANCIAL_HOLDING);

	/**
	 * @description Method to set the fields using in financial holding
	 *
	 * @return A set of the standard fields used by queries when returning financial holdings
	 */
	public static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				FIELD_CURRENT_VALUE,
				FIELD_FINANCIAL_ACCOUNT_ENTITY_NUMBER,
				FinServ__FinancialHolding__c.AW_AUMSourceExternalId__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.AW_NetContribution__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.AW_Product_Code__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.AW_SellingPrice__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.AW_SharePercentage__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.AW_ValueAsAt__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__AssetCategoryName__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__AssetCategory__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__AssetClass__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__FinancialAccount__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__GainLoss__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__Household__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__LastUpdated__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__MarketValue__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__PercentChange__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__Price__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__PrimaryOwner__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__PurchasePrice__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__Securities__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__Shares__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__SourceSystemId__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.FinServ__Symbol__c.getDescribe().getLocalName(),
				FinServ__FinancialHolding__c.Name.getDescribe().getLocalName(),
				//TODO: Remove to SL DAL Class
				FinServ__FinancialHolding__c.SLSC_FundAccNumber__c.getDescribe().getLocalName()
		};
	}

	/**
	 * @description Gets an Financial Holding based on Id
	 *
	 * @param finHoldingId Id of the financial holding
	 *
	 * @return Null or Item
	 */
	public static FinServ__FinancialHolding__c findById(Id finHoldingId)
	{
		return (FinServ__FinancialHolding__c) CMN_DAL_SObjectSelector.findById(OBJECT_NAME, finHoldingId, getDefaultFields());
	}

	/**
	 * @description This method is use to get the Financial Holding Names along with the grouped Current Values
	 *
	 * @param accountId Master Account Id
	 *
	 * @return list of found items
	 */
	public static List<AggregateResult> sumCurrentValuePerHoldingName(Id accountId)
	{
		CMN_SOQL_Query.AndCondition andCondition = new CMN_SOQL_Query.AndCondition();

		andCondition.notEquals(FIELD_PRODUCT_CODE, null);
		andCondition.equalsX(FIELD_FINANCIAL_ACCOUNT_PARENT_ACCOUNT_ID, accountId);

		CMN_SOQL_Builder builder =
				new CMN_SOQL_Builder()
						.selectSumX(FIELD_CURRENT_VALUE)
						.fromX(OBJECT_NAME)
						.whereX(andCondition)
						.groupByX(FIELD_PRODUCT_CODE)
						.limitX(CMN_DAL_SObjectDomain.MAXIMUM_BATCH_SIZE);

		return Database.query(builder.toSoql());
	}
}