objects/Account.object
<CustomObject>
    <fields>
        <fullName>FinServ__SourceSystemId__c</fullName>
        <externalId>true</externalId>
        <label>Source System ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FinServ__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AW_FNA__c.object
<CustomObject>
    <fields>
        <fullName>AW_MasterAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the Master Account Details</description>
        <label>MasterAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FNA (MasterAccount)</relationshipLabel>
        <relationshipName>FNA1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FNA</label>
    <nameField>
        <displayFormat>FNA-{0000}</displayFormat>
        <label>FNA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FNA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>AW_AssetsAndLiabilities__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ability to Link/manually add a product</description>
        <label>Assets and Liabilities</label>
        <referenceTo>FinServ__AssetsAndLiabilities__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_FNA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related FNA</description>
        <label>FNA</label>
        <referenceTo>AW_FNA__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_GoalTypeIfOther__c</fullName>
        <description>Type Goal if selected Others</description>
        <label>Goal Type if Other</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Goal_Type__c</fullName>
        <description>Select Goal Type</description>
        <label>Goal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_IsCreator__c</fullName>
        <description>Used to identify if the logged in user is the creator</description>
        <formula>CreatedById = $User.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Creator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AW_IsInvestmentGoal__c</fullName>
        <description>Check if this is an investment is a financial goal</description>
        <formula>ISPICKVAL(AW_ProductType__c, &apos;Investment&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Investment Goal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AW_IsProtectionGoal__c</fullName>
        <description>Is this a protection goal?</description>
        <formula>ISPICKVAL(AW_ProductType__c, &apos;Protection&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Protection Goal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AW_MasterAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the Master Account Details</description>
        <label>MasterAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Goals (MasterAccount)</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_PercentageComplete__c</fullName>
        <description>The percentage completion of financial goal</description>
        <formula>IF(FinServ__TargetValue__c=0,0,FinServ__ActualValue__c / FinServ__TargetValue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percentage Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AW_PriorityLevel__c</fullName>
        <description>Select the Priority Level</description>
        <label>Priority Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_ProductType__c</fullName>
        <description>Select Product Type</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Investment</fullName>
                </value>
                <value>
                    <fullName>Protection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_RelatedOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field provides a way to link a specific &apos;Financial Goal&apos; record to a related &apos;Opportunity&apos; record</description>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Shortfall__c</fullName>
        <description>This field calculates the Shortfall/Surplus value which is the Target Value - Actual Value. The amount required to meet the target amount/ the amount exceeding the target amount</description>
        <formula>FinServ__ActualValue__c - FinServ__TargetValue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shortfall/Surplus</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_SortingDate__c</fullName>
        <description>Used by lightning component to sort life events and goals</description>
        <formula>FinServ__TargetDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sorting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AW_TotalFinancialAmount__c</fullName>
        <description>This field will be rolled up of current value on Financial Account</description>
        <label>Total Financial Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_TotalInsuranceAmount__c</fullName>
        <description>This field will be rolled up of current value on Insurance Policy</description>
        <label>Total Insurance Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AW_Total_Current_Market_Value__c</fullName>
        <description>The current market value</description>
        <label>Recommended Lumpsum Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__ActualValue__c</fullName>
        <inlineHelpText>The value of the asset allocated to the Goal - This is pre-populated when linking a Financial Account to a goal.</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__CompletionDate__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__Description__c</fullName>
        <label>Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FinServ__Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Household that this goal is associated with.</description>
        <label>Household</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Household Financial Goals</relationshipLabel>
        <relationshipName>HouseholdFinancialGoals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__InitialValue__c</fullName>
        <label>Initial Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <filterItems>
                <field>Account.FinServ__IndividualType__c</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Goals</relationshipLabel>
        <relationshipName>ClientFinancialGoals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__SourceSystemId__c</fullName>
        <externalId>true</externalId>
        <label>Source System ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__TargetDate__c</fullName>
        <inlineHelpText>The date at which you want to reach a 100% completion on the goal.</inlineHelpText>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__TargetValue__c</fullName>
        <inlineHelpText>The target value that you would like to reach for this specific goal.</inlineHelpText>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AW_ProductType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Retirement</fullName>
                </value>
                <value>
                    <fullName>Saving for a rainy day</fullName>
                </value>
                <value>
                    <fullName>Lifestyle goals</fullName>
                </value>
                <value>
                    <fullName>Self-Improvement goals</fullName>
                </value>
                <value>
                    <fullName>Life Cover - Lump sum</fullName>
                </value>
                <value>
                    <fullName>Critical Illness - Lump sum</fullName>
                </value>
                <value>
                    <fullName>Disability Cover - Lump sum</fullName>
                </value>
                <value>
                    <fullName>Temporary Sickness - Income</fullName>
                </value>
                <value>
                    <fullName>Disability Cover - Income</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AW_DAL_FinancialGoal.cls
/**
 * @description Public class to return the records of Financial Goal
 *
 * @author jason.van.beukering@accenture.com safwan.h.mohammed@accenture.com
 *
 * @date 2019, October 2022
 */
public inherited sharing class AW_DAL_FinancialGoal
{
	private static final String FIELD_GOAL_TYPE = FinServ__FinancialGoal__c.AW_Goal_Type__c.getDescribe().getLocalName();
	private static final String FIELD_PRIMARY_OWNER_ID = 'FinServ__PrimaryOwner__r.Id';
	private static final String FIELD_TARGET_DATE = FinServ__FinancialGoal__c.FinServ__TargetDate__c.getDescribe().getLocalName();

	/**
	 * @description The API name of the primary owner field
	 */
	public static final String FIELD_PRIMARY_OWNER = FinServ__FinancialGoal__c.FinServ__PrimaryOwner__c.getDescribe().getLocalName();
	/**
	 * @description The API name of the object
	 */
	public static final String OBJECT_NAME = FinServ__FinancialGoal__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();
	/**
	 * @description The picklist value for "Risk" Goals
	 */
	public static final String PICK_RISK_GOAL_TYPE = 'Risk';
	/**
	 * @description The picklist value for "Risk" Goals
	 */
	public static final String PICK_INVESTMENT_GOAL_TYPE = 'Investment';

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				FIELD_GOAL_TYPE,
				FIELD_PRIMARY_OWNER,
				FIELD_PRIMARY_OWNER_ID,
				FIELD_TARGET_DATE,
				FinServ__FinancialGoal__c.AW_AssetsAndLiabilities__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_FNA__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_GoalTypeIfOther__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_IsCreator__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_IsInvestmentGoal__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_IsProtectionGoal__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_PercentageComplete__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_PriorityLevel__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_ProductType__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_RelatedOpportunity__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_Shortfall__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_SortingDate__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_TotalFinancialAmount__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_TotalInsuranceAmount__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_MasterAccount__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.AW_Total_Current_Market_Value__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.CreatedDate.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__ActualValue__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__CompletionDate__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__Description__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__Household__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__InitialValue__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__SourceSystemId__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__Status__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__TargetDate__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__TargetValue__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.FinServ__Type__c.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.Id.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.Name.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.OwnerId.getDescribe().getLocalName(),
				FinServ__FinancialGoal__c.RecordTypeId.getDescribe().getLocalName()
		};
	}

	/**
	 * @description Method to return the List of Financial Goals sorted by target date
	 *
	 * @param accountId The primary owner of the Goal
	 *
	 * @return List of sorted items
	 */
	public static List<FinServ__FinancialGoal__c> findByPrimaryOwner(Id accountId)
	{
		CMN_DAL_Search.SOQLSearchParameters searchParameters =
				CMN_DAL_SObjectSelector.initialiseParameters(OBJECT_NAME, FIELD_PRIMARY_OWNER, new Set<String> {String.valueOf(accountId)}, getDefaultFields());

		CMN_SOQL_Query.OrderBy orderBy = searchParameters.addOrderByField(FIELD_TARGET_DATE);
		orderBy.nullsFirst = true;

		return CMN_DAL_Search.getObjects(searchParameters);
	}
	/**
	 * @description Method to return the List of Financial Goals byt the Goal Type
	 *
	 * @param accountId The primary owner of the Goal
	 * @param goalType The goal type to filter the items
	 *
	 * @return List of found Items
	 */
	public static List<FinServ__FinancialGoal__c> findByAccountIdAndGoalType(Id accountId, String goalType)
	{
		CMN_DAL_Search.SOQLSearchParameters searchParameters = new CMN_DAL_Search.SOQLSearchParameters(OBJECT_NAME, getDefaultFields());

		searchParameters.searchConditions.equalsX(FIELD_PRIMARY_OWNER, accountId);
		searchParameters.searchConditions.equalsX(FIELD_GOAL_TYPE, goalType);

		return CMN_DAL_Search.getObjects(searchParameters);
	}

	/**
	 * @description Method to return the List of Financial Goal by Id
	 *
	 * @param accountIds Id to store the financial goal Id
	 *
	 * @return Null or Item
	 */
	public static List<FinServ__FinancialGoal__c> findByAccountId(Set<Id> accountIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_PRIMARY_OWNER, accountIds, getDefaultFields());
	}

	/**
	 * @description Method to return the List of Financial Goal by Id
	 *
	 * @param financialGoalId Id to store the financial goal Id
	 *
	 * @return Null or Item
	 */
	public static FinServ__FinancialGoal__c findById(Id financialGoalId)
	{
		return (FinServ__FinancialGoal__c)CMN_DAL_SObjectSelector.findById(OBJECT_NAME, financialGoalId, getDefaultFields());
	}

	/**
	 * @description Method to return the List of Financial Goal by Id
	 *
	 * @param financialGoalIds Id to store the financial goal Id
	 *
	 * @return Null or Item
	 */
	public static List<FinServ__FinancialGoal__c> findById(Set<Id> financialGoalIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, financialGoalIds, getDefaultFields());
	}

	/**
	 * @description This method will return map of FNA Ids and Goals
	 *
	 * @param financialGoalIds Id to store the financial goal Id
	 *
	 * @return populated map
	 */
	public static Map<Id, List<FinServ__FinancialGoal__c>> getFnaToGoalMap(Set<Id> financialGoalIds)
	{
		List<FinServ__FinancialGoal__c> foundGoals = findById(financialGoalIds);

		Map<Id, List<FinServ__FinancialGoal__c>> fnaToGoalMap = new Map<Id, List<FinServ__FinancialGoal__c>>();

		for(FinServ__FinancialGoal__c foundGoal : foundGoals)
		{
			List<FinServ__FinancialGoal__c> goals = fnaToGoalMap.get(foundGoal.AW_FNA__c);

			if(goals == null)
			{
				goals = new List<FinServ__FinancialGoal__c>();
				fnaToGoalMap.put(foundGoal.AW_FNA__c, goals);
			}

			goals.add(foundGoal);
		}

		return fnaToGoalMap;
	}

	/**
	 * @description retrieves all financial goals in the system
	 *
	 * @return A list of items
	 */
	@TestVisible
	private static List<FinServ__FinancialGoal__c> getAll()
	{
		return CMN_DAL_Search.getAll(OBJECT_NAME, getDefaultFields());
	}
}