objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMN_CountryOfIncorporation__c</fullName>
        <description>Used for integration to populate client&apos;s Country of Incorporation from source systems.</description>
        <label>Country of Incorporation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_DateOfIncorporation__c</fullName>
        <description>Used for integration to populate client&apos;s Date of Incorporation from source systems.</description>
        <label>Date of Incorporation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMN_OrganisationType__c</fullName>
        <description>Used for integration to populate client&apos;s Organization Type from source systems.</description>
        <label>Organisation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BANK</fullName>
                    <label>Bank</label>
                </value>
                <value>
                    <fullName>CC</fullName>
                    <label>Closed Corporation</label>
                </value>
                <value>
                    <fullName>COMM</fullName>
                    <label>Commercial Bank</label>
                </value>
                <value>
                    <fullName>CO</fullName>
                    <label>Company</label>
                </value>
                <value>
                    <fullName>COR</fullName>
                    <label>Corporate</label>
                </value>
                <value>
                    <fullName>FOR_CO</fullName>
                    <label>Foreign Company</label>
                </value>
                <value>
                    <fullName>Foreign Trust</fullName>
                </value>
                <value>
                    <fullName>JOINT</fullName>
                    <label>Joint Company</label>
                </value>
                <value>
                    <fullName>LTD_PVT_CO</fullName>
                    <label>Limited Private Company</label>
                </value>
                <value>
                    <fullName>NON_COMM</fullName>
                    <label>Non-Commercial Bank</label>
                </value>
                <value>
                    <fullName>NPC</fullName>
                    <label>Non Profit Company</label>
                </value>
                <value>
                    <fullName>NPO</fullName>
                    <label>Non Profit Organisation</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PERS</fullName>
                    <label>Person</label>
                </value>
                <value>
                    <fullName>INC</fullName>
                    <label>Personal Liability Company</label>
                </value>
                <value>
                    <fullName>PVT_CO</fullName>
                    <label>Private Company</label>
                </value>
                <value>
                    <fullName>PUB_CO</fullName>
                    <label>Public Company</label>
                </value>
                <value>
                    <fullName>SOC</fullName>
                    <label>State Owned Company</label>
                </value>
                <value>
                    <fullName>TRUST</fullName>
                    <label>Trust</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccountRole__c.object
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <fields>
        <fullName>AW_RoleDOB__c</fullName>
        <description>Date of Birth of the Person Involved</description>
        <label>Birth Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AW_RoleFirstName__c</fullName>
        <description>This field is used to capture the first name associated with a financial account role</description>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_RoleIdentificationNumber__c</fullName>
        <description>Identification of the Role</description>
        <label>Identification Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_RoleInitials__c</fullName>
        <description>Initials of the person who is assigned the role</description>
        <label>Initials</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_RoleLastName__c</fullName>
        <description>This field stores the last name associated with a financial account role</description>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_RoleTitle__c</fullName>
        <description>This field represents the title or role associated with a financial account role</description>
        <label>Title</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ConsultantCode__c</fullName>
        <description>Used for integration to populate Consultant Code from source systems (Compass/Lifestyle)</description>
        <label>Consultant Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_CountryOfCitizenship__c</fullName>
        <description>Used for integration to populate Country of Citizenship from source systems (Compass/Lifestyle)</description>
        <label>Country of Citizenship</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_CountryOfIncorporation__c</fullName>
        <description>Used for integration to populate Country of Incorporation from source systems (Compass/Lifestyle)</description>
        <label>Country of Incorporation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_CountryOfIssue__c</fullName>
        <description>Used for integration to populate Country of Issue from source systems (Compass/Lifestyle)</description>
        <label>Country of Issue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_DateOfIncorporation__c</fullName>
        <description>Used for integration to populate Date of Incorporation from source systems (Compass/Lifestyle)</description>
        <label>Date of Incorporation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMN_Email__c</fullName>
        <description>Used for integration to populate Email from source systems (Compass/Lifestyle)</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CMN_ExpiryDate__c</fullName>
        <description>Used for integration to populate Expiry Date from source systems (Compass/Lifestyle)</description>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMN_FifthName__c</fullName>
        <description>Used for integration to populate Fifth Name from source systems (Compass/Lifestyle)</description>
        <label>Fifth Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_FourthName__c</fullName>
        <description>Used for integration to populate Fourth Name from source systems (Compass/Lifestyle)</description>
        <label>Fourth Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Gender__c</fullName>
        <description>Used for integration to populate Gender from source systems (Compass/Lifestyle)</description>
        <label>Gender</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_IssueDate__c</fullName>
        <description>Used for integration to populate Issue Date from source systems (Compass/Lifestyle)</description>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMN_MaritalStatus__c</fullName>
        <description>Used for integration to populate Marital Status from source systems (Compass/Lifestyle)</description>
        <label>Marital Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Mobile__c</fullName>
        <description>Used for integration to populate Mobile Number from source systems (Compass/Lifestyle)</description>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CMN_OccupationRiskCategory__c</fullName>
        <description>Used for integration to populate Occupation Risk Category from source systems (Compass/Lifestyle)</description>
        <label>Occupation Risk Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Occupation__c</fullName>
        <description>Used for integration to populate Occupation from source systems (Compass/Lifestyle)</description>
        <label>Occupation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <description>Financial account that this role is related to.</description>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Roles</relationshipLabel>
        <relationshipName>FinancialAccountRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FinServ__Role__c</fullName>
        <description>Role that describes how the organizational entity or person is involved with the financial account.</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Absolute Cessionary</fullName>
                </value>
                <value>
                    <fullName>Antenuptial Cession</fullName>
                </value>
                <value>
                    <fullName>Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Child Life Assured</fullName>
                </value>
                <value>
                    <fullName>Collateral Cessionary</fullName>
                </value>
                <value>
                    <fullName>Educator - Child Life Assured</fullName>
                </value>
                <value>
                    <fullName>Extended Life</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                    <label>Financial Advisor</label>
                </value>
                <value>
                    <fullName>Joint Life</fullName>
                </value>
                <value>
                    <fullName>Joint Owner</fullName>
                </value>
                <value>
                    <fullName>Life Assured</fullName>
                </value>
                <value>
                    <fullName>Main Life</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Other Cessionary</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Payee</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
                <value>
                    <fullName>Payor</fullName>
                </value>
                <value>
                    <fullName>Policy Holder</fullName>
                </value>
                <value>
                    <fullName>Primary Life Assured</fullName>
                </value>
                <value>
                    <fullName>Primary Life Assured Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Secondary Life Assured</fullName>
                </value>
                <value>
                    <fullName>Secondary Life Assured Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <recordTypes>
        <fullName>AW_LibertyFinancialAccountRole</fullName>
        <active>true</active>
        <description>Record type to be used for Integration with Compass, Lifestyle and Ilanga</description>
        <label>Liberty Financial Account Role</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AW_DAL_FinancialAccountRole.cls
/**
 * @description Public class to return the records of Financial Account Role
 *
 * @author bhaskar.arora@accenture.com jayanth.kumar.s@accenture.com
 *
 * @date 2021, July 2022
 */
public inherited sharing class AW_DAL_FinancialAccountRole
{
	private static final String FIELD_FINANCIAL_ACCOUNT_ID = 'FinServ__FinancialAccount__r.Id';
	private static final String FIELD_PRIMARY_OWNER_ID = 'FinServ__FinancialAccount__r.FinServ__PrimaryOwner__r.Id';
	@TestVisible
	private static final String FIELD_ROLE = FinServ__FinancialAccountRole__c.FinServ__Role__c.getDescribe().getLocalName();
	private static final String OBJECT_NAME = FinServ__FinancialAccountRole__c.SObjectType.getDescribe().getLocalName();

	/**
	 * @description The name of the  owner role used when linking party to a financial account
	 */
	public static final String PICK_OWNER = 'Owner';
	/**
	 * @description The name of the Consultant role used when linking party to a financial account
	 */
	public static final String PICK_FINANCIAL_ADVISOR = 'Consultant';
	/**
	 * @description The default record type used being used by workbench application when creating financial account roles
	 */
	public static final String RT_LIBERTY_FINANCIAL_ACCOUNT_ROLE = 'AW_LibertyFinancialAccountRole';

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	public static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				FinServ__FinancialAccountRole__c.AW_RoleDOB__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.AW_RoleFirstName__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.AW_RoleIdentificationNumber__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.AW_RoleInitials__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.AW_RoleLastName__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.AW_RoleTitle__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_ConsultantCode__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_CountryOfCitizenship__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_CountryOfIncorporation__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_CountryOfIssue__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_DateOfIncorporation__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_Email__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_ExpiryDate__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_FifthName__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_FourthName__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_Gender__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_IssueDate__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_MaritalStatus__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_Mobile__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_OccupationRiskCategory__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_Occupation__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_OrganisationType__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_OrganizationName__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_PassportNumber__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_PercentageSplit__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_PhoneNumber__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_Race__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_RegistrationNumber__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_RelationshipToLifeAssured__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_RelationshipToOwner__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_SecondName__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_Suffix__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_ThirdName__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_WeddingAnniversary__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.CMN_WorkPhoneNumber__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.FinServ__Active__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.FinServ__FinancialAccount__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.FinServ__RelatedContact__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.FinServ__Role__c.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.Id.getDescribe().getLocalName(),
				FinServ__FinancialAccountRole__c.RecordTypeId.getDescribe().getLocalName()
		};
	}

	/**
	 * @description Method to retrieve Financial Account Roles based on account linked to related Financial Account and Role
	 *
	 * @param accountId the Id of account linked to Related Financial Account
	 * @param roles the roles for which records are being queried
	 *
	 * @return A list of Financial Account Roles
	 */
	public static List<FinServ__FinancialAccountRole__c> findByAccountIdAndRole(Id accountId, List<String> roles)
	{
		CMN_DAL_Search.SOQLSearchParameters searchParameters =
				CMN_DAL_SObjectSelector.initialiseParameters(OBJECT_NAME, FIELD_PRIMARY_OWNER_ID, new Set<String> {accountId}, getDefaultFields());
		searchParameters.searchConditions.inX(FIELD_ROLE, roles);

		return CMN_DAL_Search.getObjects(searchParameters);

	}

	/**
	 * @description Method to retrieve Financial Account Roles based on PolicyID and Array of Roles
	 *
	 * @param policyId the Id of account linked to Related Financial Account
	 * @param roles the role for which records are being queried
	 *
	 * @return A list of items
	 */
	public static List<FinServ__FinancialAccountRole__c> findByPolicyIdAndListOfRoles(Id policyId, List<String> roles)
	{
		CMN_DAL_Search.SOQLSearchParameters searchParameters =
				CMN_DAL_SObjectSelector.initialiseParameters(OBJECT_NAME, FIELD_FINANCIAL_ACCOUNT_ID, new Set<String> {policyId}, getDefaultFields());
		searchParameters.searchConditions.inX(FIELD_ROLE, roles);
		return CMN_DAL_Search.getObjects(searchParameters);
	}
}