objects/AW_AdviserPerformance__c.object
<CustomObject>
    <description>Various measures used to track activity by  advisers and sales leaders. The information is drawn from external systems as well as activity within Salesforce. The activity measures are collected weekly and aggregated to a parent object monthly.</description>
    <fields>
        <fullName>AW_AverageFAVP__c</fullName>
        <description>This is used to store average FAVP value</description>
        <label>AQC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_ClientSatisfactionScore__c</fullName>
        <description>Year average rating based on clients surveys</description>
        <label>Client Satisfaction Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AW_LAPExpTenure__c</fullName>
        <description>This  is used to store LAP Experience Tenure</description>
        <label>Tenure</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_LastYearsProductionClubStatus__c</fullName>
        <description>Status of Last Year&apos;s Production Club</description>
        <label>Production Club based on previous year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_UACFID__c</fullName>
        <description>owner will be assigned based on UACFID</description>
        <label>UACFID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Activity Measure Actual</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Measure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Measure Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AW_UACFID__c</fullName>
        <description>Users unique Liberty ID</description>
        <externalId>true</externalId>
        <label>UACF ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AW_CTR_ProductionMeasures.cls
/**
* @description Used by Lightning Component to retrieve Activity Measure info
 *
 * @see AW_TEST_CTR_ProductionMeasures @story ST-3928
 *
 * @author Accenture
 *
* @date 2020
*/
public inherited sharing class AW_CTR_ProductionMeasures
{
	@TestVisible
	private static final String RECORD_AVAILABLE_LABEL = 'Not Available';

    /**
	* @description   	Used by LWC to retrieve the latest production measures linked to the logged in user.
	*					Seperate queries done due to data issues.
    *
	* @return       	Returns DTO_ProductionMeasure 
	*/
	@AuraEnabled(Cacheable=true)
	public static DTO_ProductionMeasure getLatestAdviserPerformance()
	{
		String currentUserUACFID = AW_DAL_User.getCurrentUser().AW_UACFID__c;
		DTO_ProductionMeasure dtoProductionMeasure = new DTO_ProductionMeasure();

		AW_AdviserPerformance__c latestId = AW_DAL_AdviserPerformance.findLatestByUACFID(currentUserUACFID);
		AW_AdviserPerformance__c latestClubStatus = AW_DAL_AdviserPerformance.findLatestWithProductionClubStatusByUACFID(currentUserUACFID);
		AW_AdviserPerformance__c latestTenure = AW_DAL_AdviserPerformance.findLatestWithTenureByUACFID(currentUserUACFID);
		AW_AdviserPerformance__c latestAQC = AW_DAL_AdviserPerformance.findLatestWithAQCByUACFID(currentUserUACFID);


		AW_AdviserPerformance__c latestSatisfactionScore = AW_DAL_AdviserPerformance.findLatestByUACFID(currentUserUACFID);


		
        dtoProductionMeasure.productionMeasureId = latestId == null ? RECORD_AVAILABLE_LABEL :latestId.Id;
        dtoProductionMeasure.productionMeasureClubStatus = latestClubStatus == null ? RECORD_AVAILABLE_LABEL : latestClubStatus.AW_LastYearsProductionClubStatus__c;
        dtoProductionMeasure.productionMeasureTenure = latestTenure == null ? RECORD_AVAILABLE_LABEL : latestTenure.AW_LAPExpTenure__c;
        dtoProductionMeasure.productionMeasureAQC = latestAQC == null ? RECORD_AVAILABLE_LABEL : latestAQC.AW_AverageFAVP__c;
		dtoProductionMeasure.productionMeasureSatisfactionScore = latestSatisfactionScore.AW_ClientSatisfactionScore__c;

		return dtoProductionMeasure;
	}
    
 	/**
	* @description Wrapper class is use to store the Production Measure values required by the LWC component
	*/
	public class DTO_ProductionMeasure
	{
		@AuraEnabled
		public String productionMeasureId;
		@AuraEnabled
		public String productionMeasureClubStatus;
		@AuraEnabled
		public String productionMeasureTenure;
		@AuraEnabled
		public String productionMeasureAQC;
		@AuraEnabled
		public Decimal productionMeasureSatisfactionScore;
	}

}