objects/AW_AdviserPerformanceAPISetting__mdt.object
<CustomObject>
    <description>This metadata holds the Adviser Performance API Setting</description>
    <fields>
        <fullName>AW_StartDate__c</fullName>
        <description>This holds the start date to consider for performance API call.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Adviser Performance API Setting</label>
    <pluralLabel>Adviser Performance API Settings</pluralLabel>
</CustomObject>

classes/AW_DAL_AdviserPerformanceAPISetting.cls
/**
 * @description Public class to perform DAP operation for metadata
 *
 * @author Accenture
 *
 * @date 2019
 */
public class AW_DAL_AdviserPerformanceAPISetting
{

	/**
	 * @description This method is use to return the list of metadata
	 *
	 * @param configName
	 *
	 * @return
	 */
	public static List<AW_AdviserPerformanceAPISetting__mdt> getMetadata(String configName)
	{
		return
		[
				SELECT
						Id,
						AW_StartDate__c
				FROM AW_AdviserPerformanceAPISetting__mdt
				WHERE DeveloperName = :configName
		];
	}

}