objects/AW_AdviserPerformance__c.object
<CustomObject>
    <description>Various measures used to track activity by  advisers and sales leaders. The information is drawn from external systems as well as activity within Salesforce. The activity measures are collected weekly and aggregated to a parent object monthly.</description>
    <fields>
        <fullName>AW_UACFID__c</fullName>
        <description>owner will be assigned based on UACFID</description>
        <label>UACFID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Activity Measure Actual</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Measure Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Measure Actuals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AW_UACFID__c</fullName>
        <description>Users unique Liberty ID</description>
        <externalId>true</externalId>
        <label>UACF ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AW_TEST_CTR_ProductionMeasures.cls
/**
 * @description Test class for AW_CTR_ProductionMeasures
 *
 * @see AW_CTR_ProductionMeasures
 *
 * @author Accenture
 *
 * @date 2019
 */
@IsTest(SeeAllData=false IsParallel=true)
private class AW_TEST_CTR_ProductionMeasures
{
	/**
	 * @description Method use to setup the test data .
	 */
	@TestSetup
	private static void insertTestData()
	{
		AW_DAL_TestDataFactory.createFeatureSwitch();
	}

	@IsTest
	private static void findLatestAdviserPerformance()
	{
		User adviser = AW_DAL_User.findRandomActiveAdviser();

		AW_AdviserPerformance__c newPerformance = AW_DAL_TestDataFactory.createAdviserPerformances(new Set<String> {adviser.AW_UACFID__c}).iterator().next();

		AW_CTR_ProductionMeasures.DTO_ProductionMeasure dtoPerformance = new AW_CTR_ProductionMeasures.DTO_ProductionMeasure();

		System.runAs(adviser)
		{
			Test.startTest();

			dtoPerformance = AW_CTR_ProductionMeasures.getLatestAdviserPerformance();

			Test.stopTest();
		}

		System.assertEquals(newPerformance.Id, dtoPerformance.productionMeasureId, 'Incorrect adviser performance record retrieved');
		//TODO: We should check that values on performance is actually what we expect
	}

}