objects/AW_AdviserTarget__c.object
<CustomObject>
    <description>Aggregates the weekly activity measures and also stores the targets set and year to date numbers</description>
    <fields>
        <fullName>AW_AT_CompositeID__c</fullName>
        <description>Used as a foreign key to uniquely identify AT rows. 
Format: WW-YYYY-ConsultantCode</description>
        <externalId>true</externalId>
        <label>AW AT CompositeID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AW_Month__c</fullName>
        <description>This indicates the month in which the activity was calculated</description>
        <label>Month</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Year__c</fullName>
        <description>This indicates the year in which the calculation was done</description>
        <label>Year</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Activity Measure Total</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Measure Total Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Measure Totals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>AW_UACFID__c</fullName>
        <description>Users unique Liberty ID</description>
        <externalId>true</externalId>
        <label>UACF ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AW_TH_AdviserTarget.cls
/**
 * @description Trigger handler for the trigger AW_TRG_AdviserTarget.
 *
 * @author Accenture
 *
 * @date 23 July 2019
@story ST-2226
 */
public inherited sharing class AW_TH_AdviserTarget extends CMN_TRH_BaseObject
{
	@TestVisible
	private static final String ERROR_MESSAGE = 'Please enter Month, Year';

	Set<Id> userIds = new Set<Id>();

	/**
	 * @description : Context method overrides will be called before insertion of Object.
	 *
	 * @param so
	 */
	public override void beforeInsert(SObject so)
	{
		if(AW_DAL_FeatureSwitches.adviserTargetsEnabled)
		{

			AW_AdviserTarget__c target = (AW_AdviserTarget__c)so;

			userIds.add(target.OwnerId);
		}
	}

	/**
	 * @description : Context method overrides will be called after the end of trigger executions .
	 */
	public override void andFinally()
	{

		if(Trigger.isBefore && Trigger.isInsert && AW_DAL_FeatureSwitches.adviserTargetsEnabled)
		{
			List<User> users = AW_DAL_User.findById(userIds);
			Map<Id, SObject> userId2User = new Map<Id, SObject>(users);

			for(SObject advTarget : Trigger.new)
			{
				AW_AdviserTarget__c target = (AW_AdviserTarget__c)advTarget;
				String uacfId;

				User foundUser = (User)userId2User.get(target.OwnerId);

				if(foundUser != null)
				{
					uacfId = foundUser.AW_UACFID__c;
				}

				if(target.AW_Month__c != null && target.AW_Year__c != null && uacfId != null)
				{
					target.AW_AT_CompositeID__c = AW_DAL_AdviserTarget.constructTargetCompositeKey(target.AW_Month__c, target.AW_Year__c, uacfId);
				}
				else
				{
					target.addError(ERROR_MESSAGE);
				}
			}
		}
	}

	public override Boolean allowRecursion()
	{
		return false;
	}
}