objects/AW_Envelope__c.object
<CustomObject>
    <fields>
        <fullName>AW_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to lookup an Account to which this Envelope would be related to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Envelopes</relationshipLabel>
        <relationshipName>Envelopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_LeadAndReferral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to lookup a Lead to which this Envelope would be related to.</description>
        <label>Lead and Referral</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Envelopes</relationshipLabel>
        <relationshipName>Envelopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_MasterAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the Master Account Details</description>
        <label>MasterAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Envelopes (MasterAccount)</relationshipLabel>
        <relationshipName>Envelopes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to lookup an Opportunity to which this Envelope would be related to.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Envelopes</relationshipLabel>
        <relationshipName>Envelopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_PackageID__c</fullName>
        <description>This field will be used to store the Package Id of the Envelope being sent.</description>
        <externalId>true</externalId>
        <label>Package ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Status__c</fullName>
        <description>This field represents the lifecycle of an Envelope.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sent to Signing Portal</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Completed - Document Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_URL__c</fullName>
        <description>This field will be used to store the package URL returned from Signing Hub.</description>
        <label>URL</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Envelopes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AW_MasterAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the Master Account Details</description>
        <label>MasterAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (MasterAccount)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AW_DAL_Envelope.cls
/**
 * @description Public class to return the records of Envelopes
 *
 * @author Accenture
 *
 * @date 2021
 */
public inherited sharing class AW_DAL_Envelope
{
	private static final String FIELD_PACKAGE_ID = AW_Envelope__c.AW_PackageID__c.getDescribe().getLocalName();
	public static final String FIELD_OWNER_EMAIL = 'Owner.Email';
	public static final String FIELD_OPPORTUNITY_ACCOUNT = 'AW_Opportunity__r.AccountId';
	public static final String OBJECT_NAME = AW_Envelope__c.SObjectType.getDescribe().getLocalName();
	public static final String STATUS_AWAITING_SIGNATURE = 'Awaiting Signature';
	public static final String STATUS_COMPLETED = 'Completed - Document Signed';
	public static final String STATUS_DECLINED = 'Declined';
	public static final String STATUS_NEW = 'New';
	public static final String STATUS_SENT_FOR_SIGNING = 'Sent to Signing Portal';

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				AW_Envelope__c.AW_MasterAccount__c.getDescribe().getLocalName(),
				AW_Envelope__c.AW_Status__c.getDescribe().getLocalName(),
				AW_Envelope__c.AW_URL__c.getDescribe().getLocalName(),
				AW_Envelope__c.CreatedDate.getDescribe().getLocalName(),
				AW_Envelope__c.Id.getDescribe().getLocalName(),
				AW_Envelope__c.Name.getDescribe().getLocalName(),
				AW_Envelope__c.OwnerId.getDescribe().getLocalName(),
				AW_Envelope__c.AW_Account__c.getDescribe().getLocalName(),
				AW_Envelope__c.AW_LeadAndReferral__c.getDescribe().getLocalName(),
				AW_Envelope__c.AW_Opportunity__c.getDescribe().getLocalName(),
				FIELD_OPPORTUNITY_ACCOUNT,
				FIELD_OWNER_EMAIL,
				FIELD_PACKAGE_ID
		};
	}

	/**
	 * @description Will find an envelope by Id
	 *
	 * @param envelopeId The Id of the envelope
	 *
	 * @return Either the item found or null
	 */
	public static AW_Envelope__c findById(Id envelopeId)
	{
		List<AW_Envelope__c> envelopes = findById(new Set<Id> {envelopeId});

		return envelopes.isEmpty() ? null : envelopes[0];
	}

	/**
	 * @description Will find a list of envelope by Id
	 *
	 * @param envelopeIds The Set of envelope Ids to retrieve
	 *
	 * @return List of envelopes
	 */
	public static List<AW_Envelope__c> findById(Set<Id> envelopeIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, envelopeIds, getDefaultFields());
	}

	/**
	 * @description Will find an envelope by package Id
	 *
	 * @param packageId The Id of the package
	 *
	 * @return Either unique item, null (or throws an exception if not unique)
	 */
	public static AW_Envelope__c findByPackageId(String packageId)
	{
		return (AW_Envelope__c)CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_PACKAGE_ID, packageId, getDefaultFields(), true);
	}

	/**
	 * @description return all Envelopes created by test classes
	 *
	 * @return A list of items
	 */
	@TestVisible
	private static List<AW_Envelope__c> getAll()
	{
		return CMN_DAL_Search.getAll(AW_Envelope__c.SObjectType, getDefaultFields());
	}
}