objects/AW_Envelope__c.object
<CustomObject>
    <fields>
        <fullName>AW_ParentOwnerId__c</fullName>
        <description>Used to store the Parent Owner Id</description>
        <formula>IF(NOT(ISBLANK(AW_Opportunity__r.Id)), AW_Opportunity__r.AW_ParentAccountOwnerId__c,
IF((NOT(ISNULL(AW_Account__r.Id))), AW_Account__r.OwnerId, null))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Owner Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Status__c</fullName>
        <description>This field represents the lifecycle of an Envelope.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Sent to Signing Portal</fullName>
                </value>
                <value>
                    <fullName>Awaiting Signature</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Completed - Document Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Envelopes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AW_TH_Envelope.cls
/**
 * @description Trigger handler for the trigger AW_TRG_Envelope.
 *
 * @see AW_TH_Envelope_TEST
 *
 * @author Accenture
 *
 * @date 2021
 */
public inherited sharing class AW_TH_Envelope extends AW_TH_BaseLinkToMaster
{
	private User currentUser;
	private static final String ERROR_PREVENT_DELETE = 'Envelopes which have already been submitted to SigningHub may not be deleted';

	/**
	 * @description Before trigger will get the current user information
	 */
	public override void bulkBefore()
	{
		super.bulkBefore();
		currentUser = AW_DAL_User.getCurrentUser();
	}

	/**
	 * @description Context method overrides will be called before insertion of Object.
	 *
	 * @param so To store the Opportunity
	 */
	public override void beforeInsert(SObject so)
	{
		super.beforeInsert(so);
		setEnvelopeOwner((AW_Envelope__c)so);
	}

	/**
	 * @description React to object being deleted and check if it should be prevented
	 *
	 * @param so object being deleted
	 */
	public override void beforeDelete(SObject so)
	{
		super.beforeDelete(so);

		AW_Envelope__c envelope = (AW_Envelope__c)so;

		if(!AW_DAL_Envelope.STATUS_NEW.equalsIgnoreCase(envelope.AW_Status__c))
		{
			envelope.addError(ERROR_PREVENT_DELETE);
		}
	}

	/**
	 * @description Will update the owner of the object to MasterAccount Owner
	 *
	 * @param newEnvelope A Envelope that's needs to be assigned to MasterAccount Owner
	 */
	private void setEnvelopeOwner(AW_Envelope__c newEnvelope)
	{
		if(AW_DAL_Profile.PROFILE_PERSONAL_ASSISTANT.equalsIgnoreCase(currentUser.Profile.Name))
		{
			newEnvelope.OwnerId = newEnvelope.AW_ParentOwnerId__c;
		}
	}
}