objects/AW_Envelope__c.object
<CustomObject>
    <label>Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Envelopes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AW_EnvelopeRole__c.object
<CustomObject>
    <description>A junction object for displaying the different signatories on the Envelopes Page</description>
    <fields>
        <fullName>AW_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used to look up to a Contact field to which the Envelope relates to</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Envelope Roles (Contact)</relationshipLabel>
        <relationshipName>Envelope_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Email__c</fullName>
        <description>Used for the email address for the envelope role signatory</description>
        <formula>AW_Contact__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Envelope__c</fullName>
        <description>This is the master-detail relationship field for the Envelope object</description>
        <label>Envelope</label>
        <referenceTo>AW_Envelope__c</referenceTo>
        <relationshipLabel>Envelope Roles</relationshipLabel>
        <relationshipName>Envelope_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AW_Mobile__c</fullName>
        <description>Used for the mobile number of the envelope role signatory</description>
        <formula>AW_Contact__r.MobilePhone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile</label>
        <type>Text</type>
    </fields>
    <label>Envelope Role</label>
    <nameField>
        <displayFormat>ER-{00000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Envelope Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AW_DAL_EnvelopeRole.cls
/**
 * @description Public class to return the records of EnvelopeRoles
 *
 * @author Annu
 *
 * @date July 2021
 */
public inherited sharing class AW_DAL_EnvelopeRole
{
	private static final String OBJECT_NAME = AW_EnvelopeRole__c.SObjectType.getDescribe().getLocalName();
	private static final String FIELD_PARENT_RECORD_ID = AW_EnvelopeRole__c.AW_Envelope__c.getDescribe().getLocalName();
	public static final String FIELD_ROLE_NAME = 'AW_Contact__r.Name';

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				AW_EnvelopeRole__c.Name.getDescribe().getLocalName(),
				AW_EnvelopeRole__c.Id.getDescribe().getLocalName(),
				AW_EnvelopeRole__c.AW_Contact__c.getDescribe().getLocalName(),
				AW_EnvelopeRole__c.AW_Mobile__c.getDescribe().getLocalName(),
				AW_EnvelopeRole__c.AW_Email__c.getDescribe().getLocalName(),
				FIELD_PARENT_RECORD_ID,
				FIELD_ROLE_NAME
		};
	}

	/**
	 * @description This method is use to get the List of EnvelopeRoles with the particular ParenRecordId
	 *
	 * @param parentRecordId The record to which this item is associated
	 *
	 * @return A list of items
	 */
	public static List<AW_EnvelopeRole__c> findByParent(Id parentRecordId)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_PARENT_RECORD_ID, new Set<Id> {parentRecordId}, getDefaultFields());
	}
}