objects/AW_embeddedURL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains URLs to external services</description>
    <fields>
        <fullName>AW_External_Services__c</fullName>
        <description>Stored external services URLs that can be accesed from Apex classes</description>
        <label>External Services</label>
        <type>Url</type>
    </fields>
    <label>embedded URLs</label>
</CustomObject>

classes/AW_CTR_GetSigningHubURL.cls
/**
 * @description Used by Lightning Component to retrieve the SigningHub URL
 *
 * @see AW_CTR_GetSigningHubURL_TEST
 *
 * @author Annu Agarwal
 *
 * @date May 2021
 */
public inherited sharing class AW_CTR_GetSigningHubURL
{
	@TestVisible
	private static final String URL_NAME = 'SigningHub';

	/**
	 * @description Retrieves base login URL for Signing Hub
	 *
	 * @return Returns the base login URL for Signing Hub from custom settings
	 */
	@AuraEnabled(Cacheable=true)
	public static String getSigningHubBaseUrl()
	{
		//TODO: Can we look to shift to custom metadata instead; its deployable
		AW_embeddedURL__c signingHubURL = AW_embeddedURL__c.getValues(URL_NAME);
		return signingHubURL?.AW_External_Services__c;
	}
}