objects/AW_FeatureSwitches__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>A Hierarchical Custom setting that can be used by developers to switch off features (i.e. disable code, validation rules etc)</description>
    <fields>
        <fullName>AW_AdviserTargetsOn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This feature switch will toggle on or off code that manages Adviser Target and Performance objects</description>
        <label>Adviser Targets On</label>
        <type>Checkbox</type>
    </fields>
    <label>Feature Switches</label>
</CustomObject>

classes/AW_DAL_FeatureSwitches.cls
/**
 * @description Public class to return the record of Feature Switch
 *
 * @author Accenture
 *
 * @date 2019
 */
public inherited sharing class AW_DAL_FeatureSwitches
{

	/**
	 * @description This method is to get the record of Feature switch.
	 *
	 * @param instanceId
	 *
	 * @return instanceId
	 */
	public static AW_FeatureSwitches__c getFeatureSwitch(Id instanceId)
	{
		return instanceId == null ? AW_FeatureSwitches__c.getInstance() : AW_FeatureSwitches__c.getInstance(instanceId);
	}

	/**
	 * @description This method is to check the adviser targer
	 */
	public static Boolean adviserTargetsEnabled
	{
		get
		{
			return getFeatureSwitch(null).AW_AdviserTargetsOn__c == true ? true : false;
		}
	}
}