objects/AW_FNA__c.object
<CustomObject>
    <label>FNA</label>
    <nameField>
        <displayFormat>FNA-{0000}</displayFormat>
        <label>FNA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FNA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AW_Planned_Solution__c.object
<CustomObject>
    <fields>
        <fullName>AW_Opportunity_Name__c</fullName>
        <description>The related opportunity</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Planned Solutions</relationshipLabel>
        <relationshipName>Planned_Solutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Planned Solution</label>
    <nameField>
        <label>Planned Solution Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planned Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>AW_FNA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related FNA</description>
        <label>FNA</label>
        <referenceTo>AW_FNA__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AW_TEST_TH_Planned_Solution.cls
/**
 * @description Test class for AW_TH_Planned_Solution
 *
 * @see AW_TH_Planned_Solution
 *
 * @author Deloitte vishakha.saini@accenture.com
 *
 * @date 2020, February 2022
 */
@IsTest(SeeAllData=false IsParallel=true)
private class AW_TEST_TH_Planned_Solution
{
	private static final Integer NUMBER_OF_ITEMS_TO_CREATE = 1;

	/**
	 * @description This method will test whether Opportunity is getting populated on Planned Solution
	 */
	@IsTest
	private static void populateOpportunityOnSolutions()
	{
		Account newAccount = AW_DAL_TestDataFactory.createClientAccount().iterator().next();

		Opportunity newOpportunity = AW_DAL_TestDataFactory.createDefaultOpportunities(newAccount, NUMBER_OF_ITEMS_TO_CREATE).iterator().next();

		AW_FNA__c newFna = AW_DAL_TestDataFactory.createFNA(newAccount.Id, NUMBER_OF_ITEMS_TO_CREATE).iterator().next();

		FinServ__FinancialGoal__c objGoal = AW_DAL_TestDataFactory.createGoals(newAccount.Id, NUMBER_OF_ITEMS_TO_CREATE).iterator().next();
		objGoal.AW_FNA__c = newFna.Id;
		update objGoal;

		Test.startTest();

		AW_Planned_Solution__c newSolution = AW_DAL_TestDataFactory.createSolutions(objGoal.Id, NUMBER_OF_ITEMS_TO_CREATE).iterator().next();

		Test.stopTest();

		//TODO Priority 1: Query should be part of a DAL class
		newSolution =
		[
				SELECT Id,
						AW_Opportunity_Name__r.Id
				FROM AW_Planned_Solution__c
				WHERE Id = :newSolution.Id
		];

		System.assertEquals(newOpportunity.Id, newSolution.AW_Opportunity_Name__r.Id);
	}
}