objects/AW_FNA__c.object
<CustomObject>
    <label>FNA</label>
    <nameField>
        <displayFormat>FNA-{0000}</displayFormat>
        <label>FNA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FNA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AW_Planned_Solution__c.object
<CustomObject>
    <label>Planned Solution</label>
    <nameField>
        <label>Planned Solution Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planned Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>AW_ProductCategory__c</fullName>
        <description>This field  indicates if the product is investment or retirement</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Investment</fullName>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinServ__FinancialAccountNumber__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialGoal__c.object
<CustomObject>
    <description>Tracks a client&apos;s goal.</description>
    <fields>
        <fullName>AW_FNA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related FNA</description>
        <label>FNA</label>
        <referenceTo>AW_FNA__c</referenceTo>
        <relationshipLabel>Financial Goals</relationshipLabel>
        <relationshipName>Financial_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Goal</label>
    <nameField>
        <label>Financial Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/InsurancePolicy.object
<CustomObject>
    <fields>
        <fullName>AW_PolicyCategory__c</fullName>
        <description>Select Policy Category</description>
        <label>PolicyCategory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Protection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>AW_Contract_Numbers__c</fullName>
        <label>Contract Numbers</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AW_Planned_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planned Solution</label>
        <referenceTo>AW_Planned_Solution__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Quote_Solution_Number__c</fullName>
        <externalId>true</externalId>
        <label>Quote Solution Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AW_CTRL_BPOCanvasContainer_TEST.cls
/**
 * @description This class is the apex test class for the class AW_CTRL_BPOCanvasContainer
 *
 * @see AW_CTRL_BPOCanvasContainer
 *
 * @author vishakha.saini@accenture.com pavan.thammali@liberty.co.za
 *
 * @date October 2020, July 2022
 */
@IsTest(SeeAllData=false IsParallel=true)
private class AW_CTRL_BPOCanvasContainer_TEST
{
	/**
	 * @description This setup test method prepares the data for the test methods
	 */
	@TestSetup
	private static void setupData()
	{
		User adviser = AW_DAL_User.findRandomActiveAdviser();

		System.runAs(adviser)
		{
		Account newAccount = AW_DAL_TestDataFactory.createClientAccount().iterator().next();

		AW_DAL_TestDataFactory.createDefaultOpportunities(newAccount, 1);

		List<AW_FNA__c> listFNA = AW_DAL_TestDataFactory.createFNA(newAccount.Id, 1);

		List<FinServ__FinancialGoal__c> listGoals = AW_DAL_TestDataFactory.createGoals(newAccount.Id, 1);
		FinServ__FinancialGoal__c goal = listGoals[0];
		goal.AW_FNA__c = listFNA[0].Id;
		update goal;

		AW_DAL_TestDataFactory.createSolutions(goal.Id, 1);
			List<InsurancePolicy> insurancePolicyList = AW_DAL_TestDataFactory.createInsurancePolicies(newAccount, 1);
			InsurancePolicy insurancePolicy = insurancePolicyList[0];
			insurancePolicy.PolicyName = CMN_DAL_SObjectDomain.generateRandomName();
            update insurancePolicy;

			List<FinServ__FinancialAccount__c> financialAccList = AW_DAL_TestDataFactory.createFinancialAccounts(newAccount, 1);
			FinServ__FinancialAccount__c financialAcc = financialAccList[0];
			financialAcc.AW_ProductCategory__c = AW_DAL_FinancialAccount.PRODUCT_CATEGORY_INVESTMENT;
			update financialAcc;

		}
	}

	/**
	 * @description This test method tests the happy flow for the method createQuoteWithExternalId and checks
	 * 				that the method behaves correctly.
	 */
	@IsTest
	private static void createQuoteWithExternalId_successScenarioTest()
	{
		//Quote number which is returned in the mock response of AW_API_RestOutboundQuoteInfo
		String quoteExternalIdForTest = '49081032';
		Opportunity opp = AW_DAL_Opportunity.getAll().iterator().next();
		AW_Planned_Solution__c sol = AW_DAL_PlannedSolution.getAll().iterator().next();

		AW_API_RestOutboundQuoteInfo.responseType = AW_API_RestOutboundQuoteInfo.RESPONSE_MULTIPLE_QUOTES;

		Test.startTest();

		AW_CTRL_BPOCanvasContainer.createQuoteWithExternalId(quoteExternalIdForTest, opp.AccountId, sol.Id);

		Test.stopTest();

		Quote quoteToBeTested = AW_DAL_Quote.findByQuoteSolutionNumber(quoteExternalIdForTest);

		System.assertEquals(quoteToBeTested.AW_Quote_Solution_Number__c, quoteExternalIdForTest, 'Quote Solution Number not populated as expected');
		System.assertEquals(quoteToBeTested.AW_Planned_Solution__c, sol.Id, 'Planned Solution not set as expected');
		System.assertEquals(quoteToBeTested.OpportunityId, opp.Id, 'Opportunity Id not populated as expected');
	}

	/**
	 * @description This test method tests the empty id flow for the method createQuoteWithExternalId and checks
	 * 				that the method behaves correctly.
	 */
	@IsTest
	private static void createQuoteWithExternalId_emptyIdScenarioTest()
	{
		Test.startTest();

		AW_CTRL_BPOCanvasContainer.createQuoteWithExternalId(CMN_UTIL_String.EMPTY, CMN_UTIL_String.EMPTY, CMN_UTIL_String.EMPTY);

		Test.stopTest();

		List<Quote> quoteToBeTested = AW_DAL_Quote.getAll();

		System.assertEquals(quoteToBeTested.size(), 0);
	}

	/**
	 * @description This test method tests the happy flow for the method createQuoteWithExternalIdForContract and checks
	 * 				that the method behaves correctly.
	 */
	@IsTest
	private static void createQuoteWithExternalIdForContractInsurancePolicy_successScenarioTest()
	{
		String quoteExternalIdForTest = CMN_DAL_SObjectDomain.generateRandomNumber();

		Opportunity opp = AW_DAL_Opportunity.getAll().iterator().next();

		List<InsurancePolicy> insurancePolicyList = AW_DAL_InsurancePolicy.getAll();
		InsurancePolicy insPolicy = insurancePolicyList.iterator().next();
		AW_CTRL_BPOCanvasContainer.LifeAssured lifeAssured = new AW_CTRL_BPOCanvasContainer.LifeAssured();
		lifeAssured.LifeAssuredName = 'Sample';
		lifeAssured.ChangeTypes = new List<String> {'Sample'};
		String lifeAssuredJson = JSON.serialize(new List<AW_CTRL_BPOCanvasContainer.LifeAssured> {lifeAssured});

		Test.startTest();

		AW_CTRL_BPOCanvasContainer.createQuoteWithExternalIdForContract
				(quoteExternalIdForTest, 'pdf_Name', opp.Id, insPolicy.Name, '[]', lifeAssuredJson, 'Insurance Policy', 
                 insPolicy.AW_PolicyCategory__c,insPolicy.policyName);

		Test.stopTest();

		Quote quoteToBeTested = AW_DAL_Quote.findByQuoteSolutionNumber(quoteExternalIdForTest);

		System.assertEquals(quoteToBeTested.AW_Quote_Solution_Number__c, quoteExternalIdForTest, 'Quote Solution Number not populated as expected');
		System.assertEquals(quoteToBeTested.OpportunityId, opp.Id, 'Opportunity Id not populated as expected');
		System.assertEquals(quoteToBeTested.AW_Contract_Numbers__c, insPolicy.Name, 'Contract Numbers not populated as expected');
	}

	/**
	 * @description This test method tests the happy flow for the method createQuoteWithExternalIdForContract and checks
	 * 				that the method behaves correctly.
	 */
	@IsTest
	private static void createQuoteWithExternalIdForContractFinancialAccount_successScenarioTest()
	{
		String quoteExternalIdForTest = CMN_DAL_SObjectDomain.generateRandomNumber();

		Opportunity opp = AW_DAL_Opportunity.getAll().iterator().next();

		List<FinServ__FinancialAccount__c> financialAccountList = AW_DAL_FinancialAccount.getAll();
		FinServ__FinancialAccount__c financialAccount = financialAccountList.iterator().next();

		AW_CTRL_BPOCanvasContainer.LifeAssured lifeAssured = new AW_CTRL_BPOCanvasContainer.LifeAssured();
		lifeAssured.LifeAssuredName = 'Sample';
		lifeAssured.ChangeTypes = new List<String> {'Sample'};
		AW_CTRL_BPOCanvasContainer.LifeAssured lifeAssured2 = new AW_CTRL_BPOCanvasContainer.LifeAssured();
		lifeAssured2.LifeAssuredName = 'Sample2';
		lifeAssured2.ChangeTypes = new List<String> {'Sample2'};
		String lifeAssuredJson = JSON.serialize(new List<AW_CTRL_BPOCanvasContainer.LifeAssured> {lifeAssured, lifeAssured2});

		Test.startTest();

		AW_CTRL_BPOCanvasContainer.createQuoteWithExternalIdForContract
				(quoteExternalIdForTest, 'pdf_Name', opp.Id, financialAccount.FinServ__FinancialAccountNumber__c, '[]', lifeAssuredJson, 
                 'Financial Account', financialAccount.AW_ProductCategory__c,financialAccount.Name);

		Test.stopTest();

		Quote quoteToBeTested = AW_DAL_Quote.findByQuoteSolutionNumber(quoteExternalIdForTest);

		System.assertEquals(quoteToBeTested.AW_Quote_Solution_Number__c, quoteExternalIdForTest, 'Quote Solution Number not populated as expected');
		System.assertEquals(quoteToBeTested.OpportunityId, opp.Id, 'Opportunity Id not populated as expected');
		System.assertEquals(quoteToBeTested.AW_Product_Category__c, AW_DAL_Quote.PRODUCT_CATEGORY_INVESTMENT, 'product category not populated as expected');

	}

	/**
	 * @description This test method tests the empty id flow for the method createQuoteWithExternalIdForContract and checks
	 * 				that the method behaves correctly.
	 */
	@IsTest
	private static void createQuoteWithExternalIdForContract_emptyIdScenarioTest()
	{
		Test.startTest();

		AW_CTRL_BPOCanvasContainer.createQuoteWithExternalIdForContract('', '', '', '', '[]', '[]', '', '','');

		Test.stopTest();

		List<Quote> quoteToBeTested = AW_DAL_Quote.getAll();

		System.assertEquals(quoteToBeTested.size(), 0);
	}
}