objects/AW_Outstanding_Requirement__c.object
<CustomObject>
    <description>This is an object to store external workflow tasks retrieved from external system(s). These represent outstanding items requested by advisers to the fulfilment team.</description>
    <fields>
        <fullName>AW_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the related account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outstanding Requirements</relationshipLabel>
        <relationshipName>Outstanding_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_ContractNumber__c</fullName>
        <description>Contract Number for the requirement</description>
        <label>Contract Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Description__c</fullName>
        <description>Description of the requirement</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_IdentityNumber__c</fullName>
        <description>ID of the requirement</description>
        <label>Identity Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Key__c</fullName>
        <description>Key for the requirement</description>
        <label>Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_MasterAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the Master Account Details</description>
        <label>MasterAccount</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outstanding Requirements (MasterAccount)</relationshipLabel>
        <relationshipName>Outstanding_Requirements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Outstanding Requirements</relationshipLabel>
        <relationshipName>Outstanding_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Pinball_Code__c</fullName>
        <description>This field stores the Pinball Code Status.</description>
        <label>Pinball Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_RequirementDate__c</fullName>
        <description>Date in which the requirement was generated</description>
        <label>Requirement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AW_Role__c</fullName>
        <description>Role of the related account</description>
        <label>Role</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Source__c</fullName>
        <description>Source Name</description>
        <label>Source</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Status__c</fullName>
        <description>Status of the requirement</description>
        <label>Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_UpdateISN__c</fullName>
        <description>Update ISN (External ID)</description>
        <externalId>true</externalId>
        <label>Update ISN</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Outstanding Requirement</label>
    <nameField>
        <displayFormat>OR-{0000}</displayFormat>
        <label>Outstanding Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outstanding Requirements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AW_DAL_OutstandingRequirement.cls
/**
 * @description Public class to return the records of Outstanding Requirement
 *
 * @author Accenture, vishakha.saini@accenture.com
 *
 * @date May 2021, March 2023
 */
public inherited sharing class AW_DAL_OutstandingRequirement
{
	public static final String OBJECT_NAME = AW_Outstanding_Requirement__c.SObjectType.getDescribe().getLocalName();
	/**
	 * @description API Name of the field UpdateIsn
	 */
	public static final String FIELD_UPDATE_ISN = AW_Outstanding_Requirement__c.AW_UpdateISN__c.getDescribe().getLocalName();

	/**
	 * @description Method to define the fields to retrieve for most queries
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				AW_Outstanding_Requirement__c.AW_Account__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_ContractNumber__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_Description__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_IdentityNumber__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_Key__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_MasterAccount__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_Opportunity__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_Pinball_Code__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_RequirementDate__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_Role__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_Source__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_Status__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.AW_UpdateISN__c.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.Id.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.Name.getDescribe().getLocalName(),
				AW_Outstanding_Requirement__c.OwnerId.getDescribe().getLocalName(),
				FIELD_UPDATE_ISN
		};
	}

	/**
	 * @description This method is use to get a OustandingRequirement with the particular Id
	 *
	 * @param outstandingRequirementId The Id of the AW_Outstanding_Requirement__c
	 *
	 * @return A single AW_Outstanding_Requirement__c
	 */
	public static AW_Outstanding_Requirement__c findById(Id outstandingRequirementId)
	{
		return (AW_Outstanding_Requirement__c)CMN_DAL_SObjectSelector.findById(AW_Outstanding_Requirement__c.SObjectType, outstandingRequirementId, getDefaultFields());
	}

	/**
	 * @description Method to get the list of Outstanding Requirements by Owner
	 *
	 * @param ownerId The owner to filter the items by
	 *
	 * @return List of items
	 */
	public static List<AW_Outstanding_Requirement__c> findByOwnerId(Id ownerId)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, CMN_DAL_SObjectDomain.FIELD_OWNER_ID, new Set<Id> {ownerId}, getDefaultFields());
	}

	/**
	 * @description return all Outstanding requirements created by test classes
	 *
	 * @return A list of items
	 */
	@TestVisible
	private static List<AW_Outstanding_Requirement__c> getAll()
	{
		return CMN_DAL_Search.getAll(AW_Outstanding_Requirement__c.SObjectType, getDefaultFields());
	}
}