objects/AW_Planned_Solution__c.object
<CustomObject>
    <label>Planned Solution</label>
    <nameField>
        <label>Planned Solution Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planned Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AW_Quoted_Solution__c.object
<CustomObject>
    <fields>
        <fullName>AW_Quote_Name__c</fullName>
        <label>Quote Name</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quoted Solutions</relationshipLabel>
        <relationshipName>Quoted_Solutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quoted Solution</label>
    <nameField>
        <label>Quoted Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quoted Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AW_ProductInterest__c</fullName>
        <description>Used to select the type of product/products the client is interested in, if specified</description>
        <label>Product Interest</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AW_ProductInterest</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>AW_Contract_Numbers__c</fullName>
        <label>Contract Numbers</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AW_Planned_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planned Solution</label>
        <referenceTo>AW_Planned_Solution__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Risk</fullName>
                </value>
                <value>
                    <fullName>Investment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>436</fullName>
                    <label>GateWay ProductGroup</label>
                </value>
                <value>
                    <fullName>445</fullName>
                    <label>Liberty Retirement Annuity</label>
                </value>
                <value>
                    <fullName>432</fullName>
                    <label>Evolve Investment Plan</label>
                </value>
                <value>
                    <fullName>433</fullName>
                    <label>Evolve Retirement Annuity</label>
                </value>
                <value>
                    <fullName>435</fullName>
                    <label>Evolve Investment Plan(Sinking Fund)</label>
                </value>
                <value>
                    <fullName>405</fullName>
                    <label>Flexible Investment Plan</label>
                </value>
                <value>
                    <fullName>406</fullName>
                    <label>Flexible Investment Plan Sinking Fund</label>
                </value>
                <value>
                    <fullName>251</fullName>
                    <label>Investment Plan</label>
                </value>
                <value>
                    <fullName>252</fullName>
                    <label>Investment Plan with Income</label>
                </value>
                <value>
                    <fullName>258</fullName>
                    <label>Offshore Investment Plan</label>
                </value>
                <value>
                    <fullName>412</fullName>
                    <label>Investment Builder</label>
                </value>
                <value>
                    <fullName>413</fullName>
                    <label>Investment Linked Repayment Option</label>
                </value>
                <value>
                    <fullName>415</fullName>
                    <label>Retirement Annuity Builder</label>
                </value>
                <value>
                    <fullName>414</fullName>
                    <label>Education Builder</label>
                </value>
                <value>
                    <fullName>264</fullName>
                    <label>Lifestyle Protector</label>
                </value>
                <value>
                    <fullName>446</fullName>
                    <label>Liberty Pension/Provident Preserver</label>
                </value>
                <value>
                    <fullName>434</fullName>
                    <label>Evolve Pension/Provident Preserver</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Guaranteed Income Annuity</label>
                </value>
                <value>
                    <fullName>186</fullName>
                    <label>Guaranteed Investment Plan with Income</label>
                </value>
                <value>
                    <fullName>47</fullName>
                    <label>Life Annuity</label>
                </value>
                <value>
                    <fullName>239</fullName>
                    <label>Life Annuity with Inflation Protection</label>
                </value>
                <value>
                    <fullName>185</fullName>
                    <label>Guaranteed Investment Plan</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Quote_Solution_Number__c</fullName>
        <externalId>true</externalId>
        <label>Quote Solution Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>AW_NewBusiness</fullName>
        <active>true</active>
        <description>This record type is used to create a New Business type quote.</description>
        <label>New Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>AW_ServicingQuote</fullName>
        <active>true</active>
        <description>This record type is used to create a servicing type quote.</description>
        <label>Servicing Quote</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/AW_ProductInterest.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Retirement</fullName>
    </customValue>
    <customValue>
        <fullName>Investment</fullName>
    </customValue>
    <customValue>
        <fullName>Gap Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Aid</fullName>
    </customValue>
    <customValue>
        <fullName>Will</fullName>
    </customValue>
    <customValue>
        <fullName>Business Assurance</fullName>
    </customValue>
    <customValue>
        <fullName>Short Term Insurance</fullName>
    </customValue>
    <masterLabel>Product Interest</masterLabel>
</GlobalValueSet>

classes/AW_DAL_Quote.cls
/**
 * @description Public class to return the records of Quote
 *
 * @author vishakha.saini@accenture.com nihal.desai@accenture.com pavan.thammali@liberty.co.za
 *
 * @date 2020, May 2022 , Nov 2022
 */
public inherited sharing class AW_DAL_Quote
{
	private static final String FIELD_ACCOUNT_ID = Quote.AccountId.getDescribe().getLocalName();
	private static final String FIELD_CONTRACT_NUMBER = Quote.AW_Contract_Numbers__c.getDescribe().getLocalName();
	private static final String FIELD_NAME = Quote.Name.getDescribe().getLocalName();
	private static final String FIELD_OPPORTUNITY_ID = Quote.OpportunityId.getDescribe().getLocalName();
	private static final String FIELD_OPPORTUNITY_PRODUCT_INTEREST = 'Opportunity.AW_ProductInterest__c';
	private static final String FIELD_OPPORTUNITY_STAGE_NAME = 'Opportunity.StageName';
	private static final String FIELD_PLANNED_SOLUTION = Quote.AW_Planned_Solution__c.getDescribe().getLocalName();
	private static final String FIELD_SOLUTION_NUMBER = Quote.AW_Quote_Solution_Number__c.getDescribe().getLocalName();
	private static final String FIELD_STATUS = Quote.Status.getDescribe().getLocalName();
	private static final String OBJECT_NAME = Quote.SObjectType.getDescribe().getLocalName();
	/**
	 * @description Picklist Value for Product Type field
	 */
	@TestVisible
	private static final String PRODUCT_TYPE_LIFE_ANNUITY = 'Life Annuity';
	/**  
	 * @description Field name for Quote Product Type
	 */
	public static final String FIELD_PRODUCT_TYPE = Quote.AW_Product_Type__c.getDescribe().getLocalName();
	
	/**
	 * @description Record Type for new business quotes for adviser workbench
	 */
	public static final String RT_NEW_BUSINESS_QUOTE = 'AW_NewBusiness';
	/**
	 * @description Record Type for servicing quotes for adviser workbench
	 */
	public static final String RT_SERVICING_QUOTE = 'AW_ServicingQuote';
	/**
	 * @description Constant string representing Investment Product Category
	 */
	public static final String PRODUCT_CATEGORY_INVESTMENT = 'Investment';
	/**
	 * @description Constant string representing Risk Product Category
	 */
	public static final String PRODUCT_CATEGORY_RISK = 'Risk';
	/**
	 * @description Constant string representing Protection Product Sub Category
	 */
	public static final String PRODUCT_SUB_CATEGORY_PROTECTION = 'Protection';
	/**
	 * @description Constant string epresenting Risk Product Sub Category
	 */
	public static final String PRODUCT_SUB_CATEGORY_INVESTMENT = 'Investment';
	/**
	 * @description Constant string representing Retirement Annuity Product sub Category
	 */
	public static final String PRODUCT_SUB_CATEGORY_RETIREMENT_ANNUITY = 'Retirement Annuity';


	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				FIELD_ACCOUNT_ID,
				FIELD_CONTRACT_NUMBER,
				FIELD_NAME,
				FIELD_OPPORTUNITY_PRODUCT_INTEREST,
				FIELD_OPPORTUNITY_STAGE_NAME,
				FIELD_SOLUTION_NUMBER,
				Quote.AW_Planned_Solution__c.getDescribe().getLocalName(),
				Quote.AW_Product_Category__c.getDescribe().getLocalName(),
				Quote.Id.getDescribe().getLocalName(),
				Quote.Name.getDescribe().getLocalName(),
				Quote.OpportunityId.getDescribe().getLocalName(),
				Quote.Status.getDescribe().getLocalName(),
				new CMN_SOQL_Query.Field(FIELD_PRODUCT_TYPE).toLabelX().toSoql()
		};
	}

	/**
	 * @description Retrieves the quotes with the given Quote Numbers.
	 *
	 * @param quoteNumbers a list of numbers
	 *
	 * @return a list of quotes
	 */
	public static List<Quote> findByQuoteNumber(Set<String> quoteNumbers)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_SOLUTION_NUMBER, quoteNumbers, getDefaultFields());

	}

	/**
	 * @description Retrieves the quotes having the given ids.
	 *
	 * @param quoteIds a list of ids
	 *
	 * @return a list of items
	 */
	public static List<Quote> findById(Set<Id> quoteIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, quoteIds, getDefaultFields());
	}

	/**
	 * @description Gets a Quote based on Id
	 *
	 * @param quoteId Id of the account
	 *
	 * @return Null or Item
	 */
	public static Quote findById(Id quoteId)
	{
		return (Quote)CMN_DAL_SObjectSelector.findById(OBJECT_NAME, quoteId, getDefaultFields());
	}

	/**
	 * @description Retrieves the quotes with the given Quote Solution Number.
	 *
	 * @param quoteSolutionNumber The solution number of the quote
	 *
	 * @return Null or item
	 */
	public static Quote findByQuoteSolutionNumber(String quoteSolutionNumber)
	{
		return (Quote)CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_SOLUTION_NUMBER, quoteSolutionNumber, getDefaultFields(), true);
	}

	/**
	 * @description Retrieves the quotes with the given Planned Solution Id.
	 *
	 * @param plannedSolutionIds A list of solution Ids
	 *
	 * @return list of found items
	 */
	public static List<Quote> findByPlannedSolutionId(Set<Id> plannedSolutionIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_PLANNED_SOLUTION, plannedSolutionIds, getDefaultFields());
	}

	/**
	 * @description Retrieves the quotes with the given Account Id.
	 *
	 * @param accountId A list of account Id
	 *
	 * @return list of found items
	 */
	public static List<Quote> findByAccountId(Id accountId)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_ACCOUNT_ID, new Set<Id> {accountId}, getDefaultFields());
	}

	/**
	 * @description retrieves all Quotes in the system
	 *
	 * @return A list of Quotes
	 */
	@TestVisible
	private static List<Quote> getAll()
	{
		return CMN_DAL_Search.getAll(OBJECT_NAME, getDefaultFields());
	}
		
	/**
	 * @description Method to get the quote with inner select on quoted solution
	 *
	 * @param quoteSolutionNumber The solution number of the quote
	 *
	 * @return Null or the item found
	 */
	@TestVisible
	private static Quote selectQuoteWithChildSelect(String quoteSolutionNumber)
	{
		CMN_DAL_Search.SOQLSearchParameters outerParams = new CMN_DAL_Search.SOQLSearchParameters(OBJECT_NAME,
				new Set<String> {FIELD_STATUS, FIELD_OPPORTUNITY_ID, FIELD_NAME});

		outerParams.searchConditions.equalsX(FIELD_SOLUTION_NUMBER, quoteSolutionNumber);

		CMN_DAL_Search.SOQLSearchParameters childParams = new CMN_DAL_Search.SOQLSearchParameters(OBJECT_NAME,
				new Set<String> {CMN_DAL_SObjectDomain.FIELD_ID}, 'Quoted_Solutions__r');

		outerParams.childSearchParameters.addAll(new Set <CMN_DAL_Search.SOQLSearchParameters> {childParams});

		List<Quote> foundQuotes = CMN_DAL_Search.getObjects(outerParams);

		return foundQuotes.isEmpty() ? null : foundQuotes.iterator().next();
	}
}