objects/AW_Quoted_Solution__c.object
<CustomObject>
    <fields>
        <fullName>AW_Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_Contract_Status__c</fullName>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>Contract Downloaded Successfully</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Load/CC Outstanding</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Ready for Upload</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Upload Initiated</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Duplicate Contract. Already exists on NB files</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Invalid Product</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>Cons Code closed</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>Upload Unsuccessful</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>Invalid Contract Number</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>Cons Code Not found</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>Linked Life Contract not found</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>Contract found on Intermediate files</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>No Control Record found. Upload again</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>Repeat upload. PC file corrupt</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>Repeat upload. No records in upload file</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>System Error. Contact Hotseat</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <label>Upload Successful to Mainframe</label>
                </value>
                <value>
                    <fullName>17</fullName>
                    <label>Mainframe Process Too Far Advanced. Load New Set</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <label>Contract Number is Zero</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <label>Contract Not On Mainframe Master Files</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <label>No Client Role Specified</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <label>Logged</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <label>Upload not Allowed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_Quote_Name__c</fullName>
        <label>Quote Name</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quoted Solutions</relationshipLabel>
        <relationshipName>Quoted_Solutions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AW_TF_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>TF External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Quoted Solution</label>
    <nameField>
        <label>Quoted Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quoted Solutions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AW_DAL_QuotedSolution.cls
/**
 * @description Public class to return the records of AW_Quoted_Solution__c
 *
 * @author Paweł Czermiński, jason.van.beukering@accenture.com
 *
 * @date 2020, February 2022
 */
public inherited sharing class AW_DAL_QuotedSolution
{
	private static final String FIELD_CONTRACT_NUMBER = AW_Quoted_Solution__c.AW_Contract_Number__c.getDescribe().getLocalName();
	private static final String FIELD_EXTERNAL_ID = AW_Quoted_Solution__c.AW_TF_External_Id__c.getDescribe().getLocalName();
	private static final String FIELD_QUOTE_NAME = AW_Quoted_Solution__c.AW_Quote_Name__c.getDescribe().getLocalName();
	private static final String OBJECT_NAME = AW_Quoted_Solution__c.SObjectType.getDescribe().getLocalName();

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				AW_Quoted_Solution__c.AW_Contract_Status__c.getDescribe().getLocalName(),
				CMN_DAL_SObjectDomain.FIELD_NAME,
				FIELD_CONTRACT_NUMBER,
				FIELD_EXTERNAL_ID,
				FIELD_QUOTE_NAME
		};
	}

	/**
	 * @description Retrieves the quotes solutions corresponding to the given external ids.
	 *
	 * @param externalIds a list of external ids
	 *
	 * @return a list of items
	 */
	public static List<AW_Quoted_Solution__c> findByTfExternalId(Set<String> externalIds)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_EXTERNAL_ID, externalIds, getDefaultFields());
	}

	/**
	 * @description Retrieves the quote solutions corresponding to the given contract numbers.
	 *
	 * @param contractNumbers a  list of numbers
	 *
	 * @return a list of items
	 */
	public static List<AW_Quoted_Solution__c> findByContractNumber(Set<String> contractNumbers)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_CONTRACT_NUMBER, contractNumbers, getDefaultFields());
	}

	/**
	 * @description Will find a quote solutions based on name
	 *
	 * @param name The name against which to query
	 *
	 * @return A list of items
	 */
	public static List<AW_Quoted_Solution__c> findByQuoteName(String name)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_QUOTE_NAME, new Set<String> {name}, getDefaultFields());
	}
}