objects/Case.object
<CustomObject>
    <fields>
        <fullName>RSC_ServiceType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the type of service requested</description>
        <label>Service Type</label>
        <referenceTo>SC_ServiceType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>AW_Text__c</fullName>
        <description>Displays article content</description>
        <label>Text</label>
        <length>100168</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

objects/SC_ServiceType__c.object
<CustomObject>
    <description>Custom object created for Servicing Console app for the various service types</description>
    <fields>
        <fullName>SC_KnowledgeArticle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to relate the knowledge article for any service type.</description>
        <label>Knowledge Article</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Service Types</relationshipLabel>
        <relationshipName>ServiceTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SC_CTRL_Script.cls
/**
 * @description Controller to get the required information for Knowledge Script components
 *
 * @see SC_CTRL_Script_TEST @story 297812
 *
 * @author bhaskar.arora@accenture.com uttpal.chandra@accenture.com
 *
 * @date July 2022, March 2023
 */
public inherited sharing class SC_CTRL_Script
{
	/**
	 * @description Method used to get the case details
	 *
	 * @param caseId record id of the case
	 *
	 * @return script linked to service type of the given case
	 */
	@AuraEnabled(Cacheable=true)
	public static DTO_Script getScriptForCase(Id caseId)
	{
		Case foundCase = SC_DAL_Case.findById(caseId);

		DTO_Script dtoScript;

		if(foundCase != null)
		{
			dtoScript = new DTO_Script();
			dtoScript.serviceTypeName = foundCase?.RSC_ServiceType__r.Name;

			Knowledge__kav foundArticle = SC_DAL_Knowledge.findByPublishedKnowledgeArticleId(foundCase.RSC_ServiceType__r?.SC_KnowledgeArticle__r.KnowledgeArticleId);

			if(foundArticle != null)
			{
				dtoScript.title = foundArticle.Title;
				dtoScript.content = foundArticle.AW_Text__c;
				dtoScript.scriptId = foundArticle.Id;
			}
		}

		return dtoScript;
	}

	/**
	 * @description DTO containing details of script
	 */
	public class DTO_Script
	{
		/**
		 * @description The id of the script
		 */
		@AuraEnabled
		public Id scriptId;
		/**
		 * @description The title of the script
		 */
		@AuraEnabled
		public String title;
		/**
		 * @description The content in the script
		 */
		@AuraEnabled
		public String content;
		/**
		 * @description The service type name of the case
		 */
		@AuraEnabled
		public String serviceTypeName;
	}

}