objects/Case.object
<CustomObject>
    <fields>
        <fullName>RSC_ServiceType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the type of service requested</description>
        <label>Service Type</label>
        <referenceTo>SC_ServiceType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SC_CaseExtension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Case Extension object.</description>
        <label>Case Extension</label>
        <referenceTo>SC_CaseExtension__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SC_CaseExtension__c.object
<CustomObject>
    <description>Custom object to associate with Case to extend case details.</description>
    <label>Case Extension</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Case Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Extensions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SC_ServiceType__c.object
<CustomObject>
    <description>Custom object created for Servicing Console app for the various service types</description>
    <fields>
        <fullName>RSC_CaseExtensionFieldSet__c</fullName>
        <description>Text field to store the API name of Case Extension Field Set name related to service type.</description>
        <label>Case Extension FieldSet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RSC_CTRL_CaseExtensionDetails.cls
/**
 * @description Controller used to get the case extension details.
 *
 * @see RSC_CTRL_CaseExtensionDetails_TEST @story ST-316918
 *
 * @author vikrant.goswami@accenture.com
 *
 * @date July 2022
 */
public inherited sharing class RSC_CTRL_CaseExtensionDetails
{
	/**
	 * @description Method used to get case extension fieldset based on case record Id
	 *
	 * @param caseId record Id of the case
	 *
	 * @return case extension record id and associated fieldset name corresponding to the service type of the case
	 */
	@AuraEnabled(Cacheable=true)
	public static DTO_CaseExtensionDetails getCaseExtensionDetails(Id caseId)
	{
		Case foundCase = SC_DAL_Case.findById(caseId);

		DTO_CaseExtensionDetails dtoDetails = new DTO_CaseExtensionDetails();

		if(foundCase != null)
		{
			dtoDetails.caseExtensionId = foundCase?.SC_CaseExtension__c;

			List<String> listOfFieldSetNames = foundCase.RSC_ServiceType__r?.RSC_CaseExtensionFieldSet__c.replaceAll('\\s+', '').split(',');

			for(String fieldSetName : listOfFieldSetNames)
			{
				dtoDetails.fieldSetNames.add(fieldSetName);
			}
		}

		return dtoDetails;
	}

	/**
	 * @description DTO containing the details for a case extension
	 */
	public class DTO_CaseExtensionDetails
	{
		/**
		 * @description field to store case extension record id
		 */
		@AuraEnabled
		public String caseExtensionId;

		/**
		 * @description field to store case extension field set name
		 */
		@AuraEnabled
		public List<String> fieldSetNames = new List<String>();
	}

}