objects/Case.object
<CustomObject>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMN_SharingEvent__e.object
<CustomObject>
    <fields>
        <fullName>CMN_IsCreate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Specifies whether Share record is to be created or deleted</description>
        <label>isCreate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CMN_ObjectName__c</fullName>
        <description>API name of the object to which the record belongs</description>
        <label>Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_PublicGroupId__c</fullName>
        <description>Public Group Id with which sharing has to be created</description>
        <label>Public Group Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Record_Id__c</fullName>
        <description>Record for which sharing has to be created</description>
        <label>Record Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Sharing Event</label>
    <pluralLabel>Sharing Events</pluralLabel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccountTransaction__c.object
<CustomObject>
    <description>Represents information about financial account transactions.</description>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Transactions</relationshipLabel>
        <relationshipName>FinancialAccountTranslations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CMN_FLOW_CreateShareRecord.cls
/**
 * @description Used to create share records from Sharing Event platform event
 *
 * @author Futureform
 *
 * @date 2022
 */
public without sharing class CMN_FLOW_CreateShareRecord {
    /**
     * @description Creates Share records when Sharing Event platform event is fired
     *
     * @return void
     */
    @InvocableMethod(label='Create Share Record' description='Creates sharing record')
    public static void createShare(List<CMN_SharingEvent__e> sharingEventRecord) {
        List<CaseShare> caseSharesInsert = new List<CaseShare>();
        List<AccountShare> accountSharesInsert = new List<AccountShare>();
        List<FinServ__FinancialAccount__Share> financialAccountSharesInsert = new List<FinServ__FinancialAccount__Share>();
        List<FinServ__FinancialAccountTransaction__Share> financialAccountTransactionSharesInsert = new List<FinServ__FinancialAccountTransaction__Share>();
        
        for(CMN_SharingEvent__e shareEvent : sharingEventRecord){
                                   
            if(shareEvent.CMN_IsCreate__c){
                if(shareEvent.CMN_ObjectName__c == 'Case'){
                    CaseShare shareRecord = new CaseShare();
                    shareRecord.CaseId = shareEvent.CMN_Record_Id__c;
                    shareRecord.UserOrGroupId = shareEvent.CMN_PublicGroupId__c;
                    shareRecord.CaseAccessLevel = 'Read';
                        
                    caseSharesInsert.add(shareRecord);                
                }       
                if(shareEvent.CMN_ObjectName__c == 'Account'){
                    AccountShare shareRecord = new AccountShare();
                    shareRecord.AccountId = shareEvent.CMN_Record_Id__c;
                    shareRecord.UserOrGroupId = shareEvent.CMN_PublicGroupId__c;
                    shareRecord.AccountAccessLevel = 'Read';
                    shareRecord.OpportunityAccessLevel = 'None';
                    shareRecord.CaseAccessLevel = 'None';
                        
                    accountSharesInsert.add(shareRecord);                       
                }
                if(shareEvent.CMN_ObjectName__c == 'FinServ__FinancialAccount__c'){
                    FinServ__FinancialAccount__Share shareRecord = new FinServ__FinancialAccount__Share();
                    shareRecord.ParentId = shareEvent.CMN_Record_Id__c;
                    shareRecord.UserOrGroupId = shareEvent.CMN_PublicGroupId__c;
                    shareRecord.AccessLevel = 'Read';
                    shareRecord.RowCause = Schema.FinServ__FinancialAccount__Share.RowCause.SLC_CodeShare__c;
                        
                    financialAccountSharesInsert.add(shareRecord);                           
                }
                if(shareEvent.CMN_ObjectName__c == 'FinServ__FinancialAccountTransaction__c'){
                    FinServ__FinancialAccountTransaction__Share shareRecord = new FinServ__FinancialAccountTransaction__Share();
                    shareRecord.ParentId = shareEvent.CMN_Record_Id__c;
                    shareRecord.UserOrGroupId = shareEvent.CMN_PublicGroupId__c;
                    shareRecord.AccessLevel = 'Read';
                    shareRecord.RowCause = Schema.FinServ__FinancialAccountTransaction__Share.RowCause.SLC_CodeShare__c;
                        
                    financialAccountTransactionSharesInsert.add(shareRecord);                      
                }
            }  
        }
        
        if(caseSharesInsert.size() > 0){
            insert caseSharesInsert;
        }
        if(accountSharesInsert.size() > 0){
            insert accountSharesInsert;
        }
        if(financialAccountSharesInsert.size() > 0){
            insert financialAccountSharesInsert;
        }
        if(financialAccountTransactionSharesInsert.size() > 0){
            insert financialAccountTransactionSharesInsert;
        }
    }

}