objects/Case.object
<CustomObject>
    <fields>
        <fullName>RSC_ServiceType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the type of service requested</description>
        <label>Service Type</label>
        <referenceTo>SC_ServiceType__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SC_AssociatedContract__c.object
<CustomObject>
    <description>Junction Object to associate Cases with the Financial Accounts &amp; Insurance Policies.</description>
    <fields>
        <fullName>SC_AssociatedContractExtension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Contract Lookup field</description>
        <label>Associated Contract Extension</label>
        <referenceTo>SC_AssociatedContractExtension__c</referenceTo>
        <relationshipLabel>Associated Contracts</relationshipLabel>
        <relationshipName>Associated_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SC_Case__c</fullName>
        <description>Contains the servicing case number associated to a particular contract.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Policies</relationshipLabel>
        <relationshipName>Associated_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Associated Contract</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Associated Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SC_AssociatedContractExtension__c.object
<CustomObject>
    <description>Custom object to associated with Associated Contract to extend its details.</description>
    <label>Associated Contract Extension</label>
    <nameField>
        <label>Associated Contract Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Contract Extensions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SC_ServiceType__c.object
<CustomObject>
    <description>Custom object created for Servicing Console app for the various service types</description>
    <fields>
        <fullName>RSC_AssociatedContractExtensionFieldSet__c</fullName>
        <description>Field used to store the name of Associated Contract Extension fieldset.</description>
        <label>Associated Contract Extension FieldSet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RSC_CTRL_ContractExtensionDetails.cls
/**
 * @description Controller used to get the associated contract extension details.
 *
 * @see RSC_CTRL_ContractExtensionDetails_TEST  @story 320305
 *
 * @author vikrant.goswami@accenture.com
 *
 * @date July 2022
 */
public inherited sharing class RSC_CTRL_ContractExtensionDetails
{
	/**
	 * @description method to get associated contract extension field set based on associated contract id
	 *
	 * @param associatedContractId record Id of associated contract
	 *
	 * @return DTO with associated contract extension id and field set names
	 */
	@AuraEnabled(Cacheable=true)
	public static DTO_ContractExtensionDetails getContractExtensionDetails(Id associatedContractId)
	{
		SC_AssociatedContract__c associatedContract = SC_DAL_AssociatedContract.findById(new Set<Id>{associatedContractId}).iterator().next();
		DTO_ContractExtensionDetails dtoContractExtensionDetails = new DTO_ContractExtensionDetails();
		if(associatedContract != null)
		{
			dtoContractExtensionDetails.contractExtensionId = associatedContract.SC_AssociatedContractExtension__c;
			List<String> listOfFieldSetNames =
					associatedContract.SC_Case__r?.RSC_ServiceType__r?.RSC_AssociatedContractExtensionFieldSet__c.replaceAll('\\s+', '').split(',');
			for (String fieldSetName : listOfFieldSetNames)
			{
				dtoContractExtensionDetails.fieldSetNames.add(fieldSetName);
			}
		}
		return dtoContractExtensionDetails;
	}

	/**
	 * @description DTO containing the details for a case extension
	 */
	public class DTO_ContractExtensionDetails
	{
		/**
		 * @description field to store associated contract extension record Id
		 */
		@AuraEnabled
		public String contractExtensionId;

		/**
		 * @description List to store associated contract extension fieldset names
		 */
		@AuraEnabled
		public List<String> fieldSetNames = new List<String>();
	}
}