objects/CMN_ObjectShareConfiguration__c.object
<CustomObject>
    <description>Will store configuration that is used by the Apex Sharing Framework to determine which records (owned by a user) to share with other users.</description>
    <fields>
        <fullName>CMN_AccessLevel__c</fullName>
        <description>This denotes that access level to set the Apex Share too. i.e. An access level of read will ensure the user gets read access to the object</description>
        <inlineHelpText>Specify the Access Level to be granted: Read, Edit, All</inlineHelpText>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                    <default>true</default>
                    <label>Read</label>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMN_ObjectAPIName__c</fullName>
        <description>API Name of the object for which sharing is being configured</description>
        <inlineHelpText>API Name of the object for which sharing is being configured</inlineHelpText>
        <label>Object API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ShareFromId__c</fullName>
        <description>Id of the user who is granting access to the records. This field will be set by a flow and will be used in Matching / Duplicate Rule.</description>
        <inlineHelpText>Id of the user who is granting access to the records. This field will be set by a flow and will be used in Matching / Duplicate Rule.</inlineHelpText>
        <label>Share From Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ShareFrom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specify the user who is granting access to the records</description>
        <inlineHelpText>Specify the user who is granting access to the records</inlineHelpText>
        <label>Share From</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ShareFrom</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMN_ShareWithId__c</fullName>
        <description>If of the user who should be granted access to the records. This field will be set by a flow and will be used in Matching / Duplicate Rule.</description>
        <inlineHelpText>If of the user who should be granted access to the records. This field will be set by a flow and will be used in Matching / Duplicate Rule.</inlineHelpText>
        <label>Share With Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ShareWith__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specify the user who should be granted access to the records</description>
        <inlineHelpText>Specify the user who should be granted access to the records</inlineHelpText>
        <label>Share With</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ShareWith</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Object Share Configuration</label>
    <nameField>
        <displayFormat>OSC-{000000}</displayFormat>
        <label>Object Share Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Shares Configuration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMN_ObjectShareInstruction__e.object
<CustomObject>
    <description>This platform event will be fired when an Object Share Configuration record(s) is created, updated or deleted.</description>
    <fields>
        <fullName>CMN_AccessLevel__c</fullName>
        <description>Specify the Access Level to be granted: Read, Edit, All</description>
        <label>Access Level</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ObjectAPIName__c</fullName>
        <description>API Name of the object to be shared</description>
        <label>Object API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ObjectShareConfigurationId__c</fullName>
        <description>Specify the id of the Object Share Configuration record</description>
        <label>Object Share Configuration Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Operation__c</fullName>
        <description>Specify the Operation to be performed on the Apex Share, i.e. Insert, Update, Delete</description>
        <label>Operation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ShareFrom__c</fullName>
        <description>Specify the user id whose records need to be shared</description>
        <label>Share From</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ShareWith__c</fullName>
        <description>Specify the user id who should be granted access to the records</description>
        <label>Share With</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Object Share Instruction</label>
    <pluralLabel>Object Share Instructions</pluralLabel>
</CustomObject>

classes/CMN_TRA_ObjectShareConfiguration.cls
/**
 * @description Trigger action that will be responsible for evaluating changes to the configuration for an object share and fire necessary platform events
 *
 * @see CMN_TRG_ObjectShareConfiguration
 * @see CMN_TRA_ObjectShareConfiguration_TEST
 *
 * @author jason.van.beukering@accenture.com prashant.k.jain@accenture.com
 *
 * @date July 2022
 */
public inherited sharing class CMN_TRA_ObjectShareConfiguration extends CMN_TRA_ObjectShareEventPublisher
		implements CMN_TRA_Interfaces.CMN_INT_AfterInsert, CMN_TRA_Interfaces.CMN_INT_AfterUpdate,
				CMN_TRA_Interfaces.CMN_INT_AfterDelete, CMN_TRA_Interfaces.CMN_INT_AfterUndelete
{
	private static final String CLASS_METHOD = 'CMN_TRA_ObjectShareConfiguration/createAndPublishInstructions';

	// Expose the instructions via static list so that we can check processing in a Unit Test
	@TestVisible
	private static List<CMN_ObjectShareInstruction__e> instructions = new List<CMN_ObjectShareInstruction__e>();

	/**
	 * @description Will process a list of newly inserted items
	 *
	 * @param newItems inserted configuration items
	 */
	public void afterInsert(List<CMN_ObjectShareConfiguration__c> newItems)
	{
		createAndPublishInstructions(newItems, CMN_DAL_ObjectShareInstruction.OPERATION_INSERT);
	}

	/**
	 * @description Will process updates to existing items
	 *
	 * @param changedItems A list of items with their changes
	 * @param oldItems A list of items with their prior values
	 */
	public void afterUpdate(List<CMN_ObjectShareConfiguration__c> changedItems, List<CMN_ObjectShareConfiguration__c> oldItems)
	{
		createAndPublishInstructions(changedItems, CMN_DAL_ObjectShareInstruction.OPERATION_UPDATE);
	}

	/**
	 * @description Will process deletion of a list of items
	 *
	 * @param deletedItems The items that were deleted
	 */
	public void afterDelete(List<CMN_ObjectShareConfiguration__c> deletedItems)
	{
		createAndPublishInstructions(deletedItems, CMN_DAL_ObjectShareInstruction.OPERATION_DELETE);
	}

	/**
	 * @description Will process un-deletion of a list of items
	 *
	 * @param undeletedItems The items that were deleted
	 */
	public void afterUndelete(List<CMN_ObjectShareConfiguration__c> undeletedItems)
	{
		afterInsert(undeletedItems);
	}

	/**
	 * @description Will ensure that relevant share instruction platform events are created and published
	 *
	 * @param shareConfigurations The updated or inserted configuration items
	 * @param operation Indicates what operation was performed; either Insert, Update or Delete
	 */
	private void createAndPublishInstructions(List<CMN_ObjectShareConfiguration__c> shareConfigurations, String operation)
	{
		//We don't want to use the same valid share configurations for every chunk, we want to re-calculate valid shares
		validShareConfigurations = null;

		extractValidConfigurations(shareConfigurations, operation);

		if(!validShareConfigurations.isEmpty())
		{
			instructions.clear();

			for(CMN_ObjectShareConfiguration__c shareConfiguration : validShareConfigurations)
			{
				CMN_ObjectShareInstruction__e instruction = new CMN_ObjectShareInstruction__e();

				instruction.CMN_AccessLevel__c = shareConfiguration.CMN_AccessLevel__c;
				instruction.CMN_ObjectAPIName__c = shareConfiguration.CMN_ObjectAPIName__c;
				instruction.CMN_ObjectShareConfigurationId__c = shareConfiguration.Id;
				instruction.CMN_Operation__c = operation;
				instruction.CMN_ShareFrom__c = shareConfiguration.CMN_ShareFromId__c;
				instruction.CMN_ShareWith__c = shareConfiguration.CMN_ShareWithId__c;

				instructions.add(instruction);
			}

			publish(instructions, CLASS_METHOD);
		}

		//Since object is changing make sure we clear out the cache
		CMN_DAL_ObjectShareConfiguration.clearCache();
	}
}