objects/CMN_CommunicationTemplate__c.object
<CustomObject>
    <description>Represents a Communication Template, provides friendly name and maps to the a template in Papyrus.</description>
    <label>Communication Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMN_CommunicationTemplateObjectMap__c.object
<CustomObject>
    <description>Junction linking an Object Definition to a template. this will be used to ensure correct data is provided on the Communication API when requesting comms generation for particular template</description>
    <fields>
        <fullName>CMN_CommunicationTemplate__c</fullName>
        <description>Used to link with Communication Template.</description>
        <label>Template</label>
        <referenceTo>CMN_CommunicationTemplate__c</referenceTo>
        <relationshipLabel>Communication Template Object Maps</relationshipLabel>
        <relationshipName>Communication_Template_Object_Maps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CMN_ObjectDefinition__c</fullName>
        <description>Used to link with Object Definition.</description>
        <label>Object Definition</label>
        <referenceTo>CMN_CommunicationTemplateObjectDef__c</referenceTo>
        <relationshipLabel>Communication Template Object Maps</relationshipLabel>
        <relationshipName>Communication_Template_Object_Maps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Communication Template Object Map</label>
    <nameField>
        <displayFormat>TN - {0000}</displayFormat>
        <label>Template Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Template Object Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CMN_DAL_CommTemplateObjectMap.cls
/**
 * @description Provides Query methods related to Communication Template Object Map object
 *
 * @author aakriti.a.goyal@accenture.com
 *
 * @date Sept 2021
 */
public inherited sharing class CMN_DAL_CommTemplateObjectMap
{
	private static final String FIELD_COMMUNICATION_TEMPLATE = CMN_CommunicationTemplateObjectMap__c.CMN_CommunicationTemplate__c.getDescribe().getLocalName();
	private static final String OBJECT_NAME = CMN_CommunicationTemplateObjectMap__c.SObjectType.getDescribe().getLocalName();
	public static final String FIELD_OBJECT_DEFINITION = CMN_CommunicationTemplateObjectMap__c.CMN_ObjectDefinition__c.getDescribe().getLocalName();

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				CMN_CommunicationTemplateObjectMap__c.CMN_ObjectDefinition__c.getDescribe().getLocalName(),
				CMN_CommunicationTemplateObjectMap__c.Id.getDescribe().getLocalName(),
				CMN_CommunicationTemplateObjectMap__c.Name.getDescribe().getLocalName(),
				FIELD_COMMUNICATION_TEMPLATE
		};
	}

	/**
	 * @description This method is use to retrieve the template object Maps by the the communication template
	 *
	 * @param templateId Id of the Communication Template
	 *
	 * @return List of items
	 */
	public static List<CMN_CommunicationTemplateObjectMap__c> findByCommunicationTemplate(String templateId)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_COMMUNICATION_TEMPLATE, new Set<String> {templateId}, getDefaultFields());
	}
}