objects/CMN_WebserviceCallQueue__c.object
<CustomObject>
    <description>A object which is used to orchestrate and track webservices (inbound and outbound). By injecting an item into this object will asynchronously manage a call to external web service.</description>
    <fields>
        <fullName>CMN_TriggeringObjectId__c</fullName>
        <description>Triggering Object ID</description>
        <label>Triggering Object Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Webservice Call Queue</label>
    <nameField>
        <displayFormat>WCQ-{0000000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Calls Queue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__FinancialAccountNumber__c</fullName>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AW_CTR_PolicySummary.cls
/**
 * @description Used for Quick action to retrieve the policy summary from Mulesoft
 *
 * @see AW_CTR_PolicySummary_TEST
 * @see AW_API_RestOutboundPolicySummary
 *
 * @author Thiru
 *
 * @date June 2021
 */
public inherited sharing class AW_CTR_PolicySummary
{
	/**
	 * @description Retrieves response from callqueue
	 *
	 * @param recordId The id of a contract, either a Financial Account or Insurance policy
	 *
	 * @return A string containing the policy document
	 */
	@AuraEnabled
	public static Map<String,Object> getPolicySummary(Id recordId)
	{
        String contractNumber;
        Map<String,Object> returnValues = new Map<String,Object>();
		CMN_WebserviceCallQueue__c queueItem = CMN_DAL_DataFactory.newOutboundWebserviceQueue(AW_API_RestOutboundPolicySummary.SERVICE_NAME, recordId);
		List<CMN_API_HttpBase> handlers = CMN_FACTORY_WebserviceManager.execute(new List<CMN_WebserviceCallQueue__c> {queueItem});
		AW_API_RestOutboundPolicySummary policySummaryHandler = (AW_API_RestOutboundPolicySummary)handlers.iterator().next();

		if(!policySummaryHandler.callResult.completed)
		{
			List<String> errors = policySummaryHandler.callResult.errors;
			String errorMessage = String.join(errors, CMN_UTIL_String.LF);
			throw new CMN_API_HttpBaseOutbound.HttpOutboundRequestException(errorMessage);

		}
        SObjectType objectType = CMN_UTIL_System.getSObjectTypeById(queueItem.CMN_TriggeringObjectId__c);
        
        if(objectType == FinServ__FinancialAccount__c.SObjectType)
        {
            FinServ__FinancialAccount__c financialAccount = AW_DAL_FinancialAccount.findById(queueItem.CMN_TriggeringObjectId__c);
            contractNumber = financialAccount?.FinServ__FinancialAccountNumber__c;
        }
        else if(objectType == InsurancePolicy.SObjectType)
        {
            InsurancePolicy policy = AW_DAL_InsurancePolicy.findByInsurancePolicyId(queueItem.CMN_TriggeringObjectId__c);
            contractNumber = policy?.Name;
        }
        
		returnValues.put('fileByteStream',((AW_API_RestOutboundPolicySummary.DTO_Response)policySummaryHandler.baseResponseDTO).fileByteStream);
        returnValues.put('contractNumbers',contractNumber);
        
		return returnValues;
	}
}