objects/CMN_JobScheduler__c.object
<CustomObject>
    <description>An object that can be used to manage CronTriggers (Scheduled Jobs) in a managed manager. Only accessible by Administrators.</description>
    <fields>
        <fullName>CMN_ScheduledJobId__c</fullName>
        <description>The Salesforce Id for the Job that was initiated for the current Job Schedular row.</description>
        <label>Scheduled Job Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Job Scheduler</label>
    <nameField>
        <displayFormat>SCHED-{0000}</displayFormat>
        <label>Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/RSC_SCHED_DeleteContentDocument_TEST.cls
/**
 * @description Test Class for RSC_SCHED_DeleteContentDocument
 *
 * @see RSC_SCHED_DeleteContentDocument @story 146054
 *
 * @author rajpal.singh@accenture.com
 *
 * @date September 2021
 */
@IsTest(SeeAllData=false IsParallel=false)
private class RSC_SCHED_DeleteContentDocument_TEST
{
	/**
	 * @description Test method to test the Schedule job
	 */
	@IsTest
	private static void runSchedule()
	{
		Test.startTest();

		CMN_JobScheduler__c scheduler = CMN_DAL_DataFactory.insertJobScheduler(RSC_SCHED_DeleteContentDocument.class.getName());

		scheduler = CMN_DAL_JobSchedule.findById(scheduler.Id);

		Test.stopTest();

		System.assertNotEquals(null, scheduler.CMN_ScheduledJobId__c, 'RSC_SCHED_DeleteContentDocument was not started');
	}
}