objects/CMN_WebserviceCallQueue__c.object
<CustomObject>
    <description>A object which is used to orchestrate and track webservices (inbound and outbound). By injecting an item into this object will asynchronously manage a call to external web service.</description>
    <fields>
        <fullName>CMN_TriggeringObjectId__c</fullName>
        <description>Triggering Object ID</description>
        <label>Triggering Object Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Webservice Call Queue</label>
    <nameField>
        <displayFormat>WCQ-{0000000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Calls Queue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>SLSC_EntityNumber__c</fullName>
        <label>Entity Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SLSC_API_RestOutboundHoldingsInfo_TEST.cls
@IsTest(SeeAllData=false IsParallel=true)
private class SLSC_API_RestOutboundHoldingsInfo_TEST {

    private static final Integer NUM_RECORDS_TO_CREATE = 1;

    @TestSetup
    static void insertTestData()
    {
        AW_DAL_TestDataFactory.createClientAccount(NUM_RECORDS_TO_CREATE);
    }

    private static List<CMN_WebserviceCallQueue__c> setup()
    {
        List<Account> accounts = AW_DAL_Account.getAll();
        FinServ__FinancialAccount__c finAcc = AW_DAL_TestDataFactory.createFinancialAccounts(accounts[0], NUM_RECORDS_TO_CREATE)[0];
        finAcc.SLSC_EntityNumber__c = CMN_DAL_SObjectDomain.generateRandomNumber();
        update finAcc;

        CMN_WebserviceCallQueue__c queueItem = CMN_DAL_DataFactory.newOutboundWebserviceQueue(SLSC_API_RestOutboundHoldingsInfo.SERVICE_NAME, finAcc.Id);

        return new List<CMN_WebserviceCallQueue__c> {queueItem};
    }

    /**
     * @description Test Method to validate the scenario wherein successful outbound API call is made
     */
    @IsTest
    static void successfulCall()
    {
        CMN_API_RestBaseOutboundTestHelper.successfulCall(setup());
    }

    /**
     * @description test triggering object is not found scenario
     */
    @IsTest
    static void failedNoTriggeringObjectId()
    {
        List<CMN_WebserviceCallQueue__c> queueItems = setup();
        FinServ__FinancialAccount__c finAccount = AW_DAL_FinancialAccount.findById(queueItems[0].CMN_TriggeringObjectId__c);
        delete finAccount;

        validateResponse(queueItems, SLSC_API_RestOutboundHoldingsInfo.EXC_FINANCIAL_ACCOUNT_ID_NOT_FOUND);
    }

    /**
     * @description test Financial Account has Entity Number not set scenario
     */
    @IsTest
    static void failedNoFinancialAccountEntityNumber()
    {
        List<CMN_WebserviceCallQueue__c> queueItems = setup();
        FinServ__FinancialAccount__c finAccount = AW_DAL_FinancialAccount.findById(queueItems[0].CMN_TriggeringObjectId__c);
        finAccount.SLSC_EntityNumber__c = null;
        update finAccount;

        validateResponse(queueItems, SLSC_API_RestOutboundHoldingsInfo.EXC_ACCOUNT_ENTITY_NUMBER_NOT_FOUND);
    }

    private static void validateResponse(List<CMN_WebserviceCallQueue__c> queueItems, String excMessage)
    {
        Test.startTest();

        List<CMN_API_HttpBase> responses = CMN_FACTORY_WebserviceManager.execute(queueItems);

        Test.stopTest();

        for(CMN_API_HttpBase response : responses)
        {
            System.assertNotEquals(true, response.callResult.errors.isEmpty(), 'No errors thrown');
            System.assert(response.callResult.errors[0].contains(excMessage));
            System.assertEquals(true, response.callResult.aborted, 'Expected Request to have aborted.');
        }
    }
}