objects/CMN_WebserviceCallQueue__c.object
<CustomObject>
    <description>A object which is used to orchestrate and track webservices (inbound and outbound). By injecting an item into this object will asynchronously manage a call to external web service.</description>
    <fields>
        <fullName>CMN_Request_Parameters__c</fullName>
        <description>Name value pair of parameters used when passing values between the controller and front end</description>
        <label>Request Parameters</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMN_Retries__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of retries</description>
        <label>Retries</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CMN_TriggeringObjectId__c</fullName>
        <description>Triggering Object ID</description>
        <label>Triggering Object Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Webservice Call Queue</label>
    <nameField>
        <displayFormat>WCQ-{0000000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Calls Queue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMN_WebserviceSetting__mdt.object
<CustomObject>
    <description>Use this to register various web service handlers and their settings such as endpoint, named credentials etc.</description>
    <fields>
        <fullName>CMN_AddStackTraceToExceptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, then when an error is encountered, the system will add the stack track to the errors lists on Queue Item and in responses.</description>
        <label>Add Stack Trace to Exceptions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CMN_AdditionalKey__c</fullName>
        <description>Depending on API; some API&apos;s require an additional key to be sent in the payload or added as a header. Use this field to store that value</description>
        <label>Additional Key</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMN_BackoffPeriod__c</fullName>
        <description>The field refers to a delay or waiting period implemented by a client when communicating with a web service</description>
        <label>Backoff Period (sec)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CMN_ClientID__c</fullName>
        <description>OAuth Client ID</description>
        <label>ClientID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Client_Secret__c</fullName>
        <description>OAuth Client Secret</description>
        <label>Client Secret</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_MaxRetriesNo__c</fullName>
        <description>Number of retries allowed</description>
        <label>Max Retries No.</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CMN_NamedCredential__c</fullName>
        <description>The field is used to store or reference a named credential related to web service</description>
        <label>Named Credential</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Password__c</fullName>
        <description>The field is used to store password related to web service</description>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Path__c</fullName>
        <description>Relative path for a service call; prefixed by the URL provided either by a Named Credential or the Endpoint URL field</description>
        <label>Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Username__c</fullName>
        <description>The field represents a username associated with a webservice</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Webservice Setting</label>
    <pluralLabel>Webservice Settings</pluralLabel>
</CustomObject>

classes/CMN_API_HttpBaseOutbound.cls
/**
 * @description The Base class for all API Web Service Calls (outbound, either SOAP or REST)
 *
 * @author Accenture, jason.van.beukering@accenture.com
 *
 * @date 2019, July 2023
 */
@SuppressWarnings('PMD.CognitiveComplexity,PMD.CyclomaticComplexity')
public virtual inherited sharing class CMN_API_HttpBaseOutbound extends CMN_API_HttpBase
{
	private static final Integer DEFAULT_TIMEOUT = 120000;//120 seconds
	@TestVisible
	private static final String ERROR_INVALID_TYPE = 'Invalid Class Type provided';
	private static final String ERROR_NO_TRIGGERING_OBJECT = 'A Valid Triggering Object Id is Required.';
	private static final String ERROR_PARAMETERS_NOT_PROVIDED = 'All required parameters {0} were not provided';
	private static final String NAMED_CREDENTIAL_URL_FORMAT = 'callout:{0}{1}';

	/**
	 * @description Base table DTO type to use, use if you want to transform API response DTO to a table structure
	 *
	 * @see CMN_API_HttpBaseOutbound.DTO_BaseTable
	 */
	protected Type baseTableDTOType {get; set;}
	/**
	 * @description The DTO that should be serialised for the request body
	 */
	protected CMN_DTO_Base baseRequestDTO {get; set;}
	/**
	 * @description The DTO that will deserialize the response body
	 */
	public CMN_DTO_Base baseResponseDTO {get; set;}

	/**
	 * @description DTO contain a set of parameters that were passed to the API
	 */
	protected CMN_DTO_NameValues requestParameters
	{
		get
		{
			if(requestParameters == null)
			{
				requestParameters = new CMN_DTO_NameValues();
			}

			return requestParameters;
		}
		set;
	}

	/**
	 * @description The request that will be used by the API handler to make an outbound call
	 *
	 * @see HttpRequest
	 */
	@TestVisible
	protected HttpRequest request
	{
		get
		{
			if(request == null)
			{
				request = new HttpRequest();
			}

			return request;
		}
		private set;
	}

	/**
	 * @description The response object that contains the results of the HTTP call out made
	 *
	 * @see HttpResponse
	 */
	@TestVisible
	protected HttpResponse response
	{
		get;
		private set;
	}

	/**
	 * @description The HTTP client that will be used to make a request (using the request object) and return a response object
	 *
	 * @see Http
	 */
	protected Http httpObject
	{
		get
		{
			if(httpObject == null)
			{
				httpObject = new Http();
			}

			return httpObject;
		}
		private set;
	}

	/**
	 * @description Object stores settings for each webservice, like base endpoint, backoff period, max number of calls allowed etc.
	 */
	protected CMN_WebserviceSetting__mdt settings
	{
		get
		{
			if(settings == null)
			{
				settings = CMN_DAL_WebserviceSetting.getMetadata(getServiceName());
			}

			return settings;
		}
		private set;
	}

	/**
	 * @description Represents an exception generated when doing an outbound API call
	 */
	public class HttpOutboundRequestException extends Exception
	{

	}

	/**
	 * @description Ensure you override this on descendant classes if you need to initialise global variables
	 */
	protected override virtual void initialise()
	{
		super.initialise();

		baseRequestDTO = new CMN_DTO_Base();
		baseResponseDTO = new CMN_DTO_Base();
		baseTableDTOType = DTO_BaseTable.class;

		setServiceSettings();
	}

	/**
	 * @description Will return token type as well as token
	 *
	 * @return Authorisation Header value
	 */
	protected virtual String getAuthorisationToken()
	{
		String userName = getUserName();

		return String.isBlank(userName) ?
				CMN_UTIL_String.EMPTY :
				HTTP_HEADER_AUTH_BASIC + EncodingUtil.base64Encode(Blob.valueOf(userName + ':' + getPassword()));
	}

	/**
	 * @description Method is use to get the base URL of a webservice, resolves named credential base URL
	 *
	 * @return A URL without named credential details for query params etc.
	 */
	public String getBaseUrl()
	{
		String endPoint;

		if(settings != null && String.isNotBlank(settings.CMN_NamedCredential__c))
		{
			NamedCredential credential = CMN_DAL_NamedCredential.findByName(getServiceName());
			endPoint = credential == null ? endPoint : credential.Endpoint;
		}

		return endPoint;
	}

	/**
	 * @description Retrieves current Service Client Id
	 *
	 * @return The client id
	 */
	protected virtual String getClientId()
	{
		return settings != null ? settings.CMN_ClientID__c : null;
	}

	/**
	 * @description Retrieves current Service Client Secret
	 *
	 * @return The client id
	 */
	protected virtual String getClientSecret()
	{
		return settings != null ? settings.CMN_Client_Secret__c : null;
	}

	/**
	 * @description Retrieves current Service Additional Key; this service will require a client certificate stored in this field
	 *
	 * @return The Additional Key
	 */
	protected String getAdditionalKey()
	{
		return settings != null ? settings.CMN_AdditionalKey__c : null;
	}

	/**
	 * @description Method is use to return the endpoint URL using in HTTP response.
	 *
	 * @return endpoint
	 */
	@TestVisible
	protected virtual String getWebServiceEndPoint()
	{
		String endPoint;

		if(settings != null && String.isNotBlank(settings.CMN_NamedCredential__c))
		{
			endPoint = String.format
					(
							NAMED_CREDENTIAL_URL_FORMAT,
							new List<String> {settings.CMN_NamedCredential__c, String.isNotBlank(settings.CMN_Path__c) ? settings.CMN_Path__c : CMN_UTIL_String.EMPTY}
					);
		}

		return endPoint;
	}

	/**
	 * @description Override this method to inject relevant query parameters
	 *
	 * @return A list of query parameters
	 */
	protected virtual String getQueryParameters()
	{
		return null;
	}

	/**
	 * @description Adds additional behaviour when item is set; specifically parsing the parameters
	 *
	 * @param queueItem The queue item used by the service calls to initiate an outbound calls
	 */
	protected override virtual void setQueueItem(CMN_WebserviceCallQueue__c queueItem)
	{
		super.setQueueItem(queueItem);
		requestParameters = String.isBlank(queueItem.CMN_Request_Parameters__c) ?
				new CMN_DTO_NameValues() : (CMN_DTO_NameValues)requestParameters.deserialize(queueItem.CMN_Request_Parameters__c);
	}

	/**
	 * @description HTTP Character encoding, override if you want to define custom content encoding for service
	 *
	 * @return result
	 */
	public override virtual String getEncoding()
	{
		return HTTP_ENCODING_JSON;
	}

	/**
	 * @description The HTTP Service Timeout, override if you want to set a longer or short timeout
	 *
	 * @return result
	 */
	protected virtual Integer getTimeout()
	{
		return DEFAULT_TIMEOUT;
	}

	/**
	 * @description Method will retrieve data from SF (if necessary) and populate Request DTO with Data
	 */
	protected virtual void populateRequestDTO()
	{
		baseRequestDTO.populate(queueItem.CMN_TriggeringObjectId__c, requestParameters);
	}

	/**
	 * @description Will generate the request body using the type of the baseRequestDTO
	 *
	 * @return result
	 *
	 * @see CMN_DTO_Base
	 * @see CMN_API_HttpBaseOutbound.initialise
	 */
	protected virtual override String getBody()
	{
		super.getBody();

		populateRequestDTO();

		return baseRequestDTO.serialize();
	}

	/**
	 * @description use this method to retrieve current response body; override this method if you want to manipulate response body first
	 *
	 * @return the response that will be parsed
	 */
	protected virtual String getResponseBody()
	{
		return response.getBody();
	}

	/**
	 * @description This method will be called if request is successful, ensure you override
	 * This method on descendant classes to consume response.
	 */
	protected virtual void parseResponse()
	{
		String responseBody = getResponseBody();

		if(CMN_UTIL_String.isNotBlank(responseBody))
		{
			baseResponseDTO = baseResponseDTO.deserialize(responseBody);
		}
	}

	/**
	 * @description Implement this method to provide a the service response in a table structure
	 *
	 * @return A table structure DTO with columns and rows
	 */
	public DTO_BaseTable getResponseAsTable()
	{
		return (DTO_BaseTable)transformResponse(baseTableDTOType);
	}

	/**
	 * @description Will transform response into alternative structure
	 *
	 * @param dtoBase the object that will be populated with the transformed version of the responseDTo
	 *
	 * @see CMN_API_HttpBaseOutbound.baseResponseDTO
	 * @see CMN_DTO_Base.populate
	 */
	public virtual void transformResponse(CMN_DTO_Base dtoBase)
	{
		dtoBase.transform(baseResponseDTO);
	}

	/**
	 * @description Retrieves current Service username
	 *
	 * @return result
	 */
	protected String getUserName()
	{
		return settings != null ? settings.CMN_Username__c : null;
	}

	/**
	 * @description Retrieves current Service password
	 *
	 * @return result
	 */
	protected String getPassword()
	{
		String password = settings != null ? settings.CMN_Password__c : null;
		return String.isNotBlank(password) ? password : CMN_UTIL_String.EMPTY;
	}

	/**
	 * @description The HTTP Verb that the service will use when making a request, override this if you want to change this for
	 * Descendant class
	 *
	 * @return result
	 */
	protected override virtual String getVerb()
	{
		String verb = super.getVerb();

		return String.isNotBlank(verb) ? verb : HTTP_VERB_POST;
	}

	/**
	 * @description Will transform response into alternative structure
	 *
	 * @param dtoType The type of the class to which the response should be transformed
	 *
	 * @return The transformed response object
	 */
	public CMN_DTO_Base transformResponse(Type dtoType)
	{
		Object dto = dtoType.newInstance();

		if(dto instanceof CMN_DTO_Base)
		{
			CMN_DTO_Base dtoBase = (CMN_DTO_Base)dto;
			transformResponse(dtoBase);
			return dtoBase;
		}
		else
		{
			throw new TypeException(ERROR_INVALID_TYPE);
		}

	}

	/**
	 * @description Will transform response into alternative structure
	 *
	 * @param dtoClassName A CMN_DTO_Base class name
	 *
	 * @return The transformed response object
	 */
	public CMN_DTO_Base transformResponse(String dtoClassName)
	{
		Type dtoType = Type.forName(dtoClassName);

		if(dtoType == null)
		{
			throw new IllegalArgumentException(ERROR_INVALID_TYPE);
		}

		return transformResponse(dtoType);
	}

	/**
	 * @description Method will return relevant webservice custom setting for the current Service Name
	 */
	protected void setServiceSettings()
	{
		settings = CMN_DAL_WebserviceSetting.getMetadata(getServiceName());
	}

	/**
	 * @description Will read web service settings to determine if stack track should be added to exceptions
	 *
	 * @return A boolean; true will add stack track to exceptions
	 */
	protected override Boolean addStackTraceToExceptions()
	{
		Boolean addTrace = super.addStackTraceToExceptions();
		return settings != null ? settings.CMN_AddStackTraceToExceptions__c : addTrace;
	}

	/**
	 * @description Sets relevant HTTP headers, override if you need to add service specific headers
	 */
	protected virtual void setHeaders()
	{
		request.setMethod(getVerb());

		if(!HTTP_VERB_GET.equalsIgnoreCase(request.getMethod()))
		{
			request.setHeader(HTTP_CONTENT_TYPE, getEncoding());
		}
		request.setTimeout(getTimeout());

		String authorisationToken = getAuthorisationToken();

		if(String.isNotEmpty(authorisationToken))
		{
			request.setHeader(HTTP_HEADER_AUTHORIZATION, authorisationToken);
		}

		String clientId = getClientId();

		if(String.isNotBlank(clientId))
		{
			request.setHeader(HTTP_HEADER_CLIENT_ID, clientId);
		}

		String clientSecret = getClientSecret();
		if(String.isNotBlank(clientSecret))
		{
			request.setHeader(HTTP_HEADER_CLIENT_SECRET, clientSecret);
		}
	}

	/**
	 * @description Method will set headers, body and endpoint, override this method on descendant
	 * if you need to change how this is done. Rarely necessary.
	 *
	 * @param body as input
	 *
	 * @return request
	 */
	protected virtual HttpRequest createRequest(String body)
	{
		setHeaders();

		if(String.isNotBlank(body) && !HTTP_VERB_GET.equalsIgnoreCase(request.getMethod()))
		{
			request.setBody(body);
		}

		String endPoint = getWebServiceEndPoint();
		String queryParams = getQueryParameters();

		endPoint = String.isNotBlank(queryParams) ? endPoint + '?' + queryParams : endPoint;

		callResult.url = endPoint;

		request.setEndpoint(endPoint);

		callResult.requestBody = request.getBody();

		return request;
	}

	/**
	 * @description To get the endpoint from mock request
	 *
	 * @return CMN_API_HttpBaseOutboundMock
	 */
	protected virtual CMN_API_HttpBaseOutboundMock getEndpointMock()
	{
		return new CMN_API_HttpBaseOutboundMock();
	}

	/**
	 * @description Indicate if a triggering object id is required
	 *
	 * @return Boolean indicating requirement
	 *
	 * @see CMN_API_HttpBaseOutbound.abortRequest
	 */
	protected virtual Boolean triggeringObjectRequired()
	{
		return true;
	}

	/**
	 * @description If the service call requires parameters to be provided, then implement this virtual method to indicate this
	 * This will then be used to determine whether service can run
	 *
	 * @return A list of required service parameters
	 *
	 * @see CMN_API_HttpBaseOutbound.abortRequest
	 */
	protected virtual Set<String> getRequiredParameters()
	{
		return new Set<String>();
	}

	/**
	 * @description Method checks to see if the web service should be allowed to run
	 *
	 * @return If true then the web service will be processed else aborted
	 */
	protected override virtual Boolean abortRequest()
	{
		Boolean abort = super.abortRequest();

		if(triggeringObjectRequired() && CMN_UTIL_String.validateId(queueItem.CMN_TriggeringObjectId__c) == null)
		{
			callResult.errors.add(ERROR_NO_TRIGGERING_OBJECT);
			abort = true;
		}

		Set<String> parameters = getRequiredParameters();

		if(!requestParameters.allExists(parameters))
		{
			callResult.errors.add(String.format(ERROR_PARAMETERS_NOT_PROVIDED, new List<String> {JSON.serialize(parameters)}));
			abort = true;
		}

		return abort;
	}

	/**
	 * @description Method will send request to endpoint, and record whether successful or not
	 *
	 * @param request The HttpRequest object contain body and headers
	 *
	 * @see HttpRequest
	 */
	protected virtual void sendRequest(HttpRequest request)
	{
		if(Test.isRunningTest())
		{
			Test.setMock(HttpCalloutMock.class, getEndpointMock());
		}

		callResult.mocking = isMocking();

		response = callResult.mocking ? getEndpointMock().respond(request) : httpObject.send(request);

		callResult.statusCode = String.valueOf(response.getStatusCode());
		callResult.responseBody = response.getBody();

		if(HTTP_VALID_CODES.contains(response.getStatusCode()))
		{
			callResult.completed = true;
		}
		else
		{
			callResult.failed = true;
		}
	}

	/**
	 * @description Once a call is completed this method is called to persist call results back to Queue Item
	 * Override this on descendant classes if you want to update other data in the system
	 * This method will also initiate retry if necessary
	 */
	public override virtual void setQueueItemDetails()
	{
		queueItem.CMN_Request_Parameters__c = requestParameters.serialize();

		super.setQueueItemDetails();

		// if callResult was successful, determine do we need to make another call in chain
		// else retry current call
		if(callResult.failed)
		{
			retry();
		}
	}

	/**
	 * @description This method will also initiate retry if necessary
	 */
	private void retry()
	{
		Decimal maxRetryCount = settings != null && settings.CMN_MaxRetriesNo__c != null ? settings.CMN_MaxRetriesNo__c : 0;

		if(queueItem.CMN_Retries__c < maxRetryCount)
		{
			Decimal backoffSecs = settings != null && settings.CMN_BackoffPeriod__c != null ? settings.CMN_BackoffPeriod__c : 0;
			backoffSecs = queueItem.CMN_Retries__c <= 0 ? backoffSecs : backoffSecs * queueItem.CMN_Retries__c;
			Datetime nextRetry = backoffSecs > 0 ? Datetime.now().addSeconds(backoffSecs.intValue()) : null;

			if(nextRetry != null)
			{
				CMN_DAL_WebserviceCallQueue.updateNextRetryInfo(queueItem, nextRetry);
			}
		}
	}

	/**
	 * @description Main process loop which controls the processing of outbound request and ensure result of call is logged
	 *
	 * @param queueItem The queueItem which will ultimately saved to record activity of webservice object
	 */
	public override virtual void process(CMN_WebserviceCallQueue__c queueItem)
	{
		super.process(queueItem);

		if(abortRequest())
		{
			callResult.aborted = true;
		}
		else
		{
			//Make the service call
			sendRequest(createRequest(getBody()));

			//Save the results of the service call

			if(callResult.completed)
			{
				parseResponse();
				registerDatabaseChanges();
			}
		}

		// Update the QueueItem
		setQueueItemDetails();
	}

	/**
	 * @description A DTO used to transform the native response of a webservice handler into a common table structure
	 */
	public virtual class DTO_BaseTable extends CMN_DTO_JsonBase
	{
		/**
		 * @description List of table columns within this table
		 */
		transient protected List<DTO_Column> tableColumns;
		/**
		 * @description List of table rows within this table
		 */
		transient protected List<Object> tableRows = new List<Object>();

		/**
		 * @description List of the defined columns in the table
		 */
		public List<DTO_Column> columns
		{
			get
			{
				return tableColumns;
			}
		}

		/**
		 * @description All the data rows for the table
		 */
		public List<Object> rows
		{
			get
			{
				return tableRows;
			}
		}

		/**
		 * @description Add a column to the table response
		 *
		 * @param label The text to render for a column
		 * @param fieldName The name of the field to match row data to column
		 * @param type The type contained in the column, see documentation for types
		 * [here:](https://developer.salesforce.com/docs/component-library/bundle/lightning-datatable/documentation)
		 */
		public virtual void addColumn(String label, String fieldName, String type)
		{
			addColumn(label, fieldName, type, false);
		}

		/**
		 * @description Add a column to the table response
		 *
		 * @param label The text to render for a column
		 * @param fieldName The name of the field to match row data to column
		 * @param type The type contained in the column, see documentation for types here:
		 * https://developer.salesforce.com/docs/component-library/bundle/lightning-datatable/documentation
		 * @param sortable Indicates whether a column should be sortable
		 */
		public virtual void addColumn(String label, String fieldName, String type, Boolean sortable)
		{
			if(tableColumns == null)
			{
				tableColumns = new List<DTO_Column>();
			}

			DTO_Column column = new DTO_Column();

			column.label = label;
			column.fieldName = fieldName;
			column.type = type;
			column.sortable = sortable;

			tableColumns.add(column);
		}

		/**
		 * @description Override this if you want to do specific handling of a data
		 *
		 * @param anObject The object to be used as source of data for the row
		 */
		public virtual void addRow(Object anObject)
		{
			tableRows.add(anObject);
		}
	}

	/**
	 * @description Defines a column
	 */
	public class DTO_Column
	{
		String label;
		String fieldName;
		String type;
		Boolean sortable;
	}

}