objects/CMN_JobScheduler__c.object
<CustomObject>
    <description>An object that can be used to manage CronTriggers (Scheduled Jobs) in a managed manager. Only accessible by Administrators.</description>
    <fields>
        <fullName>CMN_ScheduledJobId__c</fullName>
        <description>The Salesforce Id for the Job that was initiated for the current Job Schedular row.</description>
        <label>Scheduled Job Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Job Scheduler</label>
    <nameField>
        <displayFormat>SCHED-{0000}</displayFormat>
        <label>Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AW_SCHED_AccountReallocation_TEST.cls
/**
 * @description Test Class for AW_SCHED_AccountReallocation
 *
 * @see AW_SCHED_AccountReallocation @story ST-82904
 *
 * @author kiran.kumaryelisetti@lntinfotech.com
 *
 * @date July 2021
 */
@IsTest(SeeAllData=false IsParallel=false)
private class AW_SCHED_AccountReallocation_TEST
{
	/**
	 * @description Test method to test the Schedule job
	 */
	@IsTest
	private static void runSchedule()
	{
		Test.startTest();

		CMN_JobScheduler__c scheduler = CMN_DAL_DataFactory.insertJobScheduler(AW_SCHED_AccountReallocation.class.getName());

		scheduler = CMN_DAL_JobSchedule.findById(scheduler.Id);

		Test.stopTest();

		System.assertNotEquals(null, scheduler.CMN_ScheduledJobId__c, 'AW_SCHED_AccountReallocation was not started');

	}
}