objects/CMN_CommunicationTemplateObjectDef__c.object
<CustomObject>
    <description>Represents an Object or Section of data that can be provided to a template.</description>
    <fields>
        <fullName>CMN_ApiName__c</fullName>
        <description>The Api Name of the custom object</description>
        <label>API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Code__c</fullName>
        <description>The Template Code for the object</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Communication Template Object Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Template Object Definition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMN_CommunicationTemplateObjectField__c.object
<CustomObject>
    <description>Defines the field for an object that should be provided to associated templates.</description>
    <fields>
        <fullName>CMN_Code__c</fullName>
        <description>Code of fields to be mapped with Communication API request body.</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ObjectDefinition__c</fullName>
        <description>Used to link with Object Definition.</description>
        <label>Object Definition</label>
        <referenceTo>CMN_CommunicationTemplateObjectDef__c</referenceTo>
        <relationshipLabel>Communication Template Object Field</relationshipLabel>
        <relationshipName>Communication_Template_Object_Field</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Communication Template Object Field</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Template Object Field</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CMN_DAL_CommTemplateObjectField.cls
/**
 * @description Provides Query methods related to Communication Template Object Field object
 *
 * @author aakriti.a.goyal@accenture.com
 *
 * @date Sept 2021
 */
public inherited sharing class CMN_DAL_CommTemplateObjectField
{
	private static final String FIELD_OBJECT_DEFINITION = CMN_CommunicationTemplateObjectField__c.CMN_ObjectDefinition__c.getDescribe().getLocalName();
	private static final String FIELD_OBJECT_DEFINITION_NAME = 'CMN_ObjectDefinition__r.CMN_ApiName__c';
	public static final String OBJECT_NAME = CMN_CommunicationTemplateObjectField__c.SObjectType.getDescribe().getLocalName();

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				CMN_CommunicationTemplateObjectField__c.Id.getDescribe().getLocalName(),
				CMN_CommunicationTemplateObjectField__c.CMN_Code__c.getDescribe().getLocalName(),
				CMN_CommunicationTemplateObjectField__c.Name.getDescribe().getLocalName(),
				FIELD_OBJECT_DEFINITION,
				FIELD_OBJECT_DEFINITION_NAME
		};
	}

	/**
	 * @description This method is use to retrieve the communication template object fields by the the object definitions
	 *
	 * @param objectDefinitionIds Set of object definition Ids
	 *
	 * @return List of items
	 */
	public static List<CMN_CommunicationTemplateObjectField__c> findByObjectDefinitions(Set<Id> objectDefinitionIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_OBJECT_DEFINITION, objectDefinitionIds, getDefaultFields());
	}
}