objects/CMN_CommunicationAttachmentDefinition__c.object
<CustomObject>
    <description>Defines a “Form” that can be attached to a template. To be used when communications need one or more forms attached.</description>
    <fields>
        <fullName>SC_Code__c</fullName>
        <description>Server based code to be attached to the standard forms of a communication</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Communication Attachment Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Attachment Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMN_CommunicationTemplateAttachment__c.object
<CustomObject>
    <description>Junction to associate on or more attachment definitions to a template. Will be used both in automated or optional comms to either automatically request an attachment to be associated to a communication.</description>
    <fields>
        <fullName>SC_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to link with Communication Attachment Definition.</description>
        <label>Definition</label>
        <referenceTo>CMN_CommunicationAttachmentDefinition__c</referenceTo>
        <relationshipLabel>Communication Template Attachments</relationshipLabel>
        <relationshipName>Communication_Template_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SC_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to link with Communication Template.</description>
        <label>Template</label>
        <referenceTo>CMN_CommunicationTemplate__c</referenceTo>
        <relationshipLabel>Communication Template Attachments</relationshipLabel>
        <relationshipName>Communication_Template_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Communication Template Attachment</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>Attachment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Template Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CMN_DAL_CommunicationTemplateAttachment.cls
/**
 * @description Provides Query methods related to Account object
 *
 * @author aakriti.a.goyal@accenture.com jason.van.beukering@accenture.com
 *
 * @date September 2021, April 2022
 */
public inherited sharing class CMN_DAL_CommunicationTemplateAttachment
{
	private static final String FIELD_DEFINITION = CMN_CommunicationTemplateAttachment__c.SC_Definition__c.getDescribe().getLocalName();
	private static final String FIELD_TEMPLATE = CMN_CommunicationTemplateAttachment__c.SC_Template__c.getDescribe().getLocalName();
	private static final String OBJECT_NAME = CMN_CommunicationTemplateAttachment__c.SObjectType.getDescribe().getLocalName();
	/**
	 * @description Template Definition Unique Id
	 */
	public static final String FIELD_DEFINITION_CODE = 'SC_Definition__r.SC_Code__c';
	/**
	 * @description Template Definition Name
	 */
	public static final String FIELD_DEFINITION_NAME = 'SC_Definition__r.Name';

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				CMN_CommunicationTemplateAttachment__c.Name.getDescribe().getLocalName(),
				CMN_CommunicationTemplateAttachment__c.SC_Definition__c.getDescribe().getLocalName(),
				CMN_CommunicationTemplateAttachment__c.SC_Template__c.getDescribe().getLocalName(),
				FIELD_DEFINITION,
				FIELD_DEFINITION_CODE,
				FIELD_DEFINITION_NAME
		};
	}

	/**
	 * @description This method is use to return the list of Communication Template Attachments with Template Id
	 *
	 * @param templateId Id of the Communication Template
	 *
	 * @return List of Communication Template Attachments
	 */
	public static List<CMN_CommunicationTemplateAttachment__c> findByTemplateId(String templateId)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_TEMPLATE, new Set<String> {templateId}, getDefaultFields());
	}

	/**
	 * @description This method is use to return the list of Communication Template Attachments with Template Id
	 *
	 * @param attachmentIds Id of the Communication Template
	 *
	 * @return List of Communication Template Attachments
	 */
	public static List<CMN_CommunicationTemplateAttachment__c> findByAttachmentId(Set<Id> attachmentIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, attachmentIds, getDefaultFields());
	}

	/**
	 * @description Will return all Communication Template Attachments created by unit tests
	 *
	 * @return A list of Communication Template Attachments
	 */
	@TestVisible
	private static List<CMN_CommunicationTemplateAttachment__c> getAll()
	{
		return CMN_DAL_Search.getAll(OBJECT_NAME, getDefaultFields());
	}
}