objects/CMN_CaseComment__c.object
<CustomObject>
    <description>Custom Object used to store all the comments on the case which will be used for integration purpose</description>
    <fields>
        <fullName>CMN_Case__c</fullName>
        <description>Custom field used to relate the comments with Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Comments</relationshipLabel>
        <relationshipName>Case_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CMN_CommentCreateDate__c</fullName>
        <description>Field used to store either the date sent by the target source system or the date when the comment was created in salesforce</description>
        <formula>IF( CMN_IsExternalComment__c,  CMN_ExternalCommentCreatedDate__c,  CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Comment Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CMN_Comment__c</fullName>
        <description>Custom field used to store the comments used for integration</description>
        <label>Comment</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CMN_CreatedUser__c</fullName>
        <description>Used to store the user information who created the case comment in url format, so agent can view the created user information</description>
        <formula>IF(NOT(CMN_IsExternalComment__c) , HYPERLINK(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))&amp;CreatedBy.Id, (CreatedBy.FirstName +&quot; &quot;+ CreatedBy.LastName)),IF(LEN(CMN_CommentCreatedByInformation__c) = 18 , HYPERLINK(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))&amp;CMN_CommentCreatedBy__r.Id, (CMN_CommentCreatedBy__r.FirstName +&quot; &quot;+ CMN_CommentCreatedBy__r.LastName)), CMN_CommentCreatedByInformation__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Created User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ExternalCommentId__c</fullName>
        <description>Custom field used to store the external comment Id received from the external systems via integration</description>
        <label>External Comment Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_IsExternalComment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to identify if the Comment was created from the external system or from Salesforce</description>
        <label>Is External Comment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CMN_IsPrivate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Custom field used to identify if the comments are visible for the user</description>
        <label>Is Private</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Comment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CMN_DAL_CaseComments.cls
/**
 * @description Public class to return the records of Custom CaseComment
 *
 * @see CMN_CaseComment__c
 *
 * @author jayanth.kumar.s@accenture.com
 *
 * @date July 2022
 */
public with sharing class CMN_DAL_CaseComments
{
	private static final String FIELD_CREATED_BY_UACFID = 'CreatedBy.AW_UACFID__c';
	private static final String FIELD_RELATED_CASE_NUMBER = 'CMN_Case__r.CaseNumber';
	private static final String OBJECT_NAME = CMN_CaseComment__c.SObjectType.getDescribe().getLocalName();
	/**
	 * @description Field used to store the api name of Case related to Case Comment.
	 */
	public static final String FIELD_CASE = CMN_CaseComment__c.CMN_Case__c.getDescribe().getLocalName();
	/**
	 * @description Field used to store the api name of External Comment ID
	 */
	public static final String FIELD_EXTERNAL_COMMENT_ID = CMN_CaseComment__c.CMN_ExternalCommentId__c.getDescribe().getLocalName();

	/**
	 * @description Field used to store the api name of ID
	 */
	public static final String FIELD_ID = CMN_CaseComment__c.Id.getDescribe().getLocalName();

	/**
	 * @description Method to define the fields to retrieve for most query's
	 *
	 * @return A list of fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				CMN_CaseComment__c.CMN_CommentCreateDate__c.getDescribe().getLocalName(),
				CMN_CaseComment__c.CMN_Comment__c.getDescribe().getLocalName(),
				CMN_CaseComment__c.CMN_CreatedUser__c.getDescribe().getLocalName(),
				CMN_CaseComment__c.CMN_IsExternalComment__c.getDescribe().getLocalName(),
				CMN_CaseComment__c.CMN_IsPrivate__c.getDescribe().getLocalName(),
				CMN_CaseComment__c.CreatedDate.getDescribe().getLocalName(),
				CMN_CaseComment__c.Name.getDescribe().getLocalName(),
				FIELD_CASE,
				FIELD_CREATED_BY_UACFID,
				FIELD_EXTERNAL_COMMENT_ID,
				FIELD_RELATED_CASE_NUMBER
		};
	}

	/**
	 * @description This method is use to get the List of Case Comments with the given case ids
	 *
	 * @param caseIds The cases for which to retrieve comments
	 *
	 * @return A list of found Case Comments
	 */
	public static List<CMN_CaseComment__c> findByCaseId(Set<Id> caseIds)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_CASE, caseIds, getDefaultFields());
	}

	/**
	 * @description This method is use to get the List of Case Comments with the given case id
	 *
	 * @param caseId The case for which to retrieve comments
	 *
	 * @return A list of found Case Comments
	 */
	public static List<CMN_CaseComment__c> findByCaseId(Id caseId)
	{
		return CMN_DAL_SObjectSelector.findById(OBJECT_NAME, FIELD_CASE, new Set<Id> {caseId}, getDefaultFields());
	}

	/**
	 * @description Will find a list of Case Comments by the external comment Id's
	 *
	 * @param externalCommentIds The Set of Comments to be retrieved
	 *
	 * @return List of CMN_CaseComment__c
	 */
	public static List<CMN_CaseComment__c> findByExternalCommentId(Set<String> externalCommentIds)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_EXTERNAL_COMMENT_ID, externalCommentIds, getDefaultFields());
	}

	/**
	 * @description This method is use to get a Case Comment with the particular Id
	 *
	 * @param recordId The record of the Case Comment
	 *
	 * @return A single Case Comment
	 */
	public static CMN_CaseComment__c findById(Id recordId)
	{
		return (CMN_CaseComment__c)CMN_DAL_SObjectSelector.findById(OBJECT_NAME, recordId, getDefaultFields());
	}

	/**
	 * @description Will return all Case Comments created by unit tests
	 *
	 * @return A list of Case Comments
	 */
	@TestVisible
	private static List<CMN_CaseComment__c> getAll()
	{
		return CMN_DAL_Search.getAll(OBJECT_NAME, getDefaultFields());
	}
}