objects/CMN_Foobar__c.object
<CustomObject>
    <description>Part of CMN Libary to demonstrate how the library functions
Should only be used as part of unit tests
See https://en.m.wikipedia.org/wiki/Foobar for more information about Foobar</description>
    <label>Foobar</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foobars</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CMN_ObjectShareChangeInstruction__e.object
<CustomObject>
    <description>This platform event will be fired when a record is created or updated for which Object Share configuration exists.</description>
    <fields>
        <fullName>CMN_AccessLevel__c</fullName>
        <description>Specify the Access Level to be granted: Read, Edit, All</description>
        <label>Access Level</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ObjectId__c</fullName>
        <description>Specify the record Id  of the object which needs to be shared, i.e. Account, Case, etc</description>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ShareWith__c</fullName>
        <description>Specify the user id who should be granted access to the records</description>
        <label>Share With</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Object Share Change Instruction</label>
    <pluralLabel>Object Share Change Instructions</pluralLabel>
</CustomObject>

objects/CMN_ObjectShareConfiguration__c.object
<CustomObject>
    <description>Will store configuration that is used by the Apex Sharing Framework to determine which records (owned by a user) to share with other users.</description>
    <fields>
        <fullName>CMN_AccessLevel__c</fullName>
        <description>This denotes that access level to set the Apex Share too. i.e. An access level of read will ensure the user gets read access to the object</description>
        <inlineHelpText>Specify the Access Level to be granted: Read, Edit, All</inlineHelpText>
        <label>Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Read</fullName>
                    <default>true</default>
                    <label>Read</label>
                </value>
                <value>
                    <fullName>Edit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMN_ShareFrom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specify the user who is granting access to the records</description>
        <inlineHelpText>Specify the user who is granting access to the records</inlineHelpText>
        <label>Share From</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ShareFrom</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMN_ShareWith__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Specify the user who should be granted access to the records</description>
        <inlineHelpText>Specify the user who should be granted access to the records</inlineHelpText>
        <label>Share With</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ShareWith</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Object Share Configuration</label>
    <nameField>
        <displayFormat>OSC-{000000}</displayFormat>
        <label>Object Share Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Shares Configuration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CMN_TRA_ObjectShareOwnerChanged_TEST.cls
/**
 * @description Tests the behaviour of the Object Share Owner Changed Trigger Action
 *
 * @see CMN_TRA_ObjectShareOwnerChanged
 *
 * @author jason.van.beukering@accenture.com prashant.k.jain@accenture.com
 *
 * @date July 2022
 */
@IsTest(SeeAllData=false IsParallel=false)
private class CMN_TRA_ObjectShareOwnerChanged_TEST
{
	private static final Integer NUMBER_OF_USERS = 2;

	/**
	 * @description Will create required unit test data
	 */
	@TestSetup
	private static void setup()
	{
		List<User> newUsers;
		User adminUser = CMN_DAL_DataFactory.newUser(CMN_DAL_Profile.PROFILE_SYSTEM_ADMIN);
		System.runAs(adminUser)
		{
			// Create users with Standard User profile
			newUsers = CMN_DAL_DataFactory.insertUsers(CMN_DAL_Profile.PROFILE_STANDARD_USER, NUMBER_OF_USERS);
			CMN_DAL_DataFactory.createPermissionSetAssignments(newUsers, CMN_DAL_PermissionSet.OBJECT_SHARE_PERMISSION_SET_API_NAME);
		}

		System.runAs(adminUser)
		{
			// newUser0 granting access to newUser1
			List<CMN_ObjectShareConfiguration__c> objectShareConfigurations = new List<CMN_ObjectShareConfiguration__c>();

			CMN_ObjectShareConfiguration__c objectShareConfiguration = CMN_DAL_DataFactory.newObjectShareConfiguration
					(
							CMN_DAL_Foobar.OBJECT_NAME,
							CMN_DAL_ObjectShareConfiguration.ACCESS_LEVEL_READ,
							newUsers[0].Id,
							newUsers[1].Id
					);
			objectShareConfigurations.add(objectShareConfiguration);

			CMN_ObjectShareConfiguration__c invalidObjectShareConfiguration = CMN_DAL_DataFactory.newObjectShareConfiguration
					(
							CMN_DAL_SObjectDomain.generateRandomName(),
							CMN_DAL_ObjectShareConfiguration.ACCESS_LEVEL_READ,
							newUsers[0].Id,
							newUsers[1].Id
					);
			objectShareConfigurations.add(invalidObjectShareConfiguration);

			insert objectShareConfigurations;
		}
	}

	/**
	 * @description Will confirm that records are processed correctly after they were inserted
	 *
	 * @see CMN_TRA_ObjectShareOwnerChanged.afterInsert
	 */
	@IsTest
	private static void afterInsert()
	{
		User standardUser = CMN_DAL_DataFactory.newUser(CMN_DAL_Profile.PROFILE_STANDARD_USER);
		CMN_ObjectShareConfiguration__c objectShareConfiguration = CMN_DAL_ObjectShareConfiguration.getAllFromCache().iterator().next();

		System.runAs(standardUser)
		{
			List<CMN_Foobar__c> newFoobars = newFoobars(objectShareConfiguration.CMN_ShareFrom__c, objectShareConfiguration.CMN_ShareWith__c);

			Test.startTest();

			insert newFoobars;

			assertPlatformEventPublishedCorrectly();
		}
	}

	/**
	 * @description Will confirm that records are processed correctly after they were inserted
	 *
	 * @see CMN_TRA_ObjectShareOwnerChanged.afterInsert
	 */
	@IsTest
	private static void afterUpdate()
	{
		CMN_ObjectShareConfiguration__c objectShareConfiguration = CMN_DAL_ObjectShareConfiguration.getAllFromCache().iterator().next();
		User runAsUser = new User(Id = objectShareConfiguration.CMN_ShareWith__c);

		System.runAs(runAsUser)
		{
			List<CMN_Foobar__c> newFoobars = newFoobars(objectShareConfiguration.CMN_ShareFrom__c, objectShareConfiguration.CMN_ShareWith__c);

			insert newFoobars;

			Test.startTest();

			CMN_Foobar__c newFoobar = newFoobars[1];

			newFoobar.OwnerId = objectShareConfiguration.CMN_ShareFrom__c;
			update newFoobar;

			assertPlatformEventPublishedCorrectly();
		}
	}

	/**
	 * @description Method to create 2 new Foobar records with specified owners
	 *
	 * @param ownerId1 Owner Id for 1st Foobar records
	 * @param ownerId2 Owner Id for 2nd Foobar records
	 *
	 * @return List of newly created Foobar records, not committed
	 */
	private static List<CMN_Foobar__c> newFoobars(Id ownerId1, Id ownerId2)
	{
		List<CMN_Foobar__c> newFoobars = new List<CMN_Foobar__c>();
		CMN_Foobar__c newFoobar1 = CMN_DAL_DataFactory.newFoobar();
		newFoobar1.OwnerId = ownerId1;
		newFoobars.add(newFoobar1);

		CMN_Foobar__c newFoobar2 = CMN_DAL_DataFactory.newFoobar();
		newFoobar2.OwnerId = ownerId2;
		newFoobars.add(newFoobar2);
		return newFoobars;
	}

	/**
	 * @description This will check the number of platform events published and the operation on the platform event
	 */
	private static void assertPlatformEventPublishedCorrectly()
	{
		//2 DML statements expected. 1 for explicit DML on Foobar object in the test method and 1 for platform event publish.
		System.assertEquals(2, Limits.getDmlStatements(), 'Incorrect number of DML statements executed');

		Test.stopTest();

		List<CMN_ObjectShareChangeInstruction__e> instructions = CMN_TRA_ObjectShareOwnerChanged.instructions;
		System.assertEquals(1, instructions.size(), 'Platform event records not created as expected');

		for(CMN_ObjectShareChangeInstruction__e instruction : instructions)
		{
			System.assertNotEquals(null, instruction.CMN_AccessLevel__c, 'Access Level not set correctly on the platform event');
			System.assertNotEquals(null, instruction.CMN_ObjectId__c, 'Object Id not set correctly on the platform event');
			System.assertNotEquals(null, instruction.CMN_ShareWith__c, 'Share With not set correctly on the platform event');
		}
	}

	/**
	 * @description Will confirm that Object Share Configuration records are returned when user doesn't have permission to Object Share Configuration
	 *
	 * @see CMN_DAL_ObjectShareConfiguration.getAllFromCache
	 */
	@IsTest
	private static void getAllFromCache()
	{
		List<User> newUsers;

		System.runAs(CMN_DAL_DataFactory.newUser(CMN_DAL_Profile.PROFILE_SYSTEM_ADMIN))
		{
			// Advisers without object share permission set
			newUsers = CMN_DAL_DataFactory.insertUsers(CMN_DAL_Profile.PROFILE_STANDARD_USER, NUMBER_OF_USERS);

			// advisers0 granting access to advisers1
			CMN_ObjectShareConfiguration__c objectShareConfiguration = CMN_DAL_DataFactory.newObjectShareConfiguration
					(
							CMN_DAL_Foobar.OBJECT_NAME,
							CMN_DAL_ObjectShareConfiguration.ACCESS_LEVEL_READ,
							newUsers[0].Id,
							newUsers[1].Id
					);
			insert objectShareConfiguration;
		}

		System.runAs(newUsers[0])
		{
			Test.startTest();

			List<CMN_ObjectShareConfiguration__c> objectShareConfiguration = CMN_DAL_ObjectShareConfiguration.getAllFromCache();

			Test.stopTest();

			System.assertEquals(false, objectShareConfiguration.isEmpty(), 'Object Share Configuration not retrieved as expected');
		}
	}
}