objects/CMN_JobScheduler__c.object
<CustomObject>
    <description>An object that can be used to manage CronTriggers (Scheduled Jobs) in a managed manager. Only accessible by Administrators.</description>
    <fields>
        <fullName>CMN_ScheduledJobId__c</fullName>
        <description>The Salesforce Id for the Job that was initiated for the current Job Schedular row.</description>
        <label>Scheduled Job Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Job Scheduler</label>
    <nameField>
        <displayFormat>SCHED-{0000}</displayFormat>
        <label>Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AW_TEST_SCHED_QuoteInfo.cls
/**
 * @description Will retrieve quotes performed for clients at regular intervals
 *
 * @see AW_SCHED_RestOutboundQuoteInfo @story ST-3089
 *
 * @author prashant.k.jain@accenture.com, jason.van.beukering@accenture.com
 *
 * @date 2019, July 2023
 */
@IsTest(SeeAllData=false IsParallel=false)
private class AW_TEST_SCHED_QuoteInfo
{
	//By creating 6 account scheduler will create 5 batches, one with 2 records
	private static final Integer NUMBER_OF_ACCOUNT_ROWS = 6;
	private static final Integer NUMBER_OF_OPPORTUNITY_ROWS = 1;

	@TestSetup
	private static void setup()
	{
		User adviser = AW_DAL_User.findRandomActiveAdviser();

		System.runAs(adviser)
		{
			for(Account newAccount : AW_DAL_TestDataFactory.createClientAccount(NUMBER_OF_ACCOUNT_ROWS))
			{
				AW_DAL_TestDataFactory.createDefaultOpportunities(newAccount, NUMBER_OF_OPPORTUNITY_ROWS);
			}
		}
	}

	/**
	 * @description Method to test the schedule job class
	 */
	@IsTest
	private static void runSchedule()
	{
		Test.startTest();

		CMN_JobScheduler__c scheduler = CMN_DAL_DataFactory.insertJobScheduler(AW_SCHED_RestOutboundQuoteInfo.class.getName());

		scheduler = CMN_DAL_JobSchedule.findById(scheduler.Id);

		Assert.isNotNull(scheduler.CMN_ScheduledJobId__c, 'AW_SCHED_RestOutboundQuoteInfo was not started');

		Test.stopTest();
	}
}