objects/CMN_CommunicationAttachmentDefinition__c.object
<CustomObject>
    <description>Defines a “Form” that can be attached to a template. To be used when communications need one or more forms attached.</description>
    <label>Communication Attachment Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communication Attachment Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CMN_CommunicationTemplateAttachment__c.object
<CustomObject>
    <description>Junction to associate on or more attachment definitions to a template. Will be used both in automated or optional comms to either automatically request an attachment to be associated to a communication.</description>
    <fields>
        <fullName>SC_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to link with Communication Attachment Definition.</description>
        <label>Definition</label>
        <referenceTo>CMN_CommunicationAttachmentDefinition__c</referenceTo>
        <relationshipLabel>Communication Template Attachments</relationshipLabel>
        <relationshipName>Communication_Template_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Communication Template Attachment</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>Attachment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Template Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RSC_CTRL_GetCommunicationAttachment.cls
/**
 * @description Controller to get the communication attachments
 *
 * @see RSC_CTRL_GetCommunicationAttachment_TEST @story ST-146941
 *
 * @author Accenture - aakriti.a.goyal@accenture.com
 *
 * @date September 2021
 */
public inherited sharing class RSC_CTRL_GetCommunicationAttachment
{
	/**
	 * @description Will retrieve the communication template attachments for specific Template Id
	 *
	 * @param templateId The Id of the selected communication template
	 *
	 * @return A list of Communication Template Attachment Wrapper
	 */
	@AuraEnabled(Cacheable=true)
	public static List<CMN_DTO_CommunicationAttachment> getAttachmentsByTemplateId(String templateId)
	{
		List<CMN_CommunicationTemplateAttachment__c> templateAttachments = CMN_DAL_CommunicationTemplateAttachment.findByTemplateId(templateId);

		List<CMN_DTO_CommunicationAttachment> communicationAttachments = new List<CMN_DTO_CommunicationAttachment>();

		for(CMN_CommunicationTemplateAttachment__c attachment : templateAttachments)
		{
			CMN_DTO_CommunicationAttachment dtoCommunicationAttachment = new CMN_DTO_CommunicationAttachment();

			dtoCommunicationAttachment.attachmentId = attachment.Id;
			dtoCommunicationAttachment.attachmentDefinitionId = attachment.SC_Definition__c;
			dtoCommunicationAttachment.definitionName = attachment.SC_Definition__r.Name;
			dtoCommunicationAttachment.isSelected = false;
			dtoCommunicationAttachment.reason = CMN_UTIL_String.EMPTY;

			communicationAttachments.add(dtoCommunicationAttachment);
		}

		return communicationAttachments;
	}
}