objects/CMN_AppLog__c.object
<CustomObject>
    <description>The object stores all the logs generated from either Apex Code or process builder invocation class</description>
    <fields>
        <fullName>CMN_ClassMethod__c</fullName>
        <description>Source class and/or method event occured e.g. &lt;Class&gt;.&lt;Method&gt;</description>
        <label>Class Method</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ExceptionType__c</fullName>
        <description>Exception Class Type</description>
        <label>Exception Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_Limits__c</fullName>
        <label>Limits</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMN_LineNumber__c</fullName>
        <description>Line Number of Exception</description>
        <label>Line Number</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CMN_LogLevel__c</fullName>
        <description>Generally, INFO and ERROR are used</description>
        <label>LogLevel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>WARN</fullName>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CMN_Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMN_RecordId__c</fullName>
        <description>Id of object related to log event</description>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_RecordLink__c</fullName>
        <description>Convenient link to access the affected record directly from the record Id</description>
        <formula>HYPERLINK(&quot;/&quot; + CMN_RecordId__c , &quot;Open&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>View Record</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_ShortMessage__c</fullName>
        <description>A logical short message or could be First 255 characters of the message. Should not contain sensitive data. Useful for SOQL WHERE clauses, and possibly GROUP BY</description>
        <label>Short Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_StackTrace__c</fullName>
        <label>StackTrace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMN_UserId__c</fullName>
        <description>The active user when the event occurred</description>
        <label>UserId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_UserLink__c</fullName>
        <description>Link to User Record which caused the event</description>
        <formula>HYPERLINK(&quot;/&quot; + CMN_UserId__c , &quot;Open&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>View User</label>
        <type>Text</type>
    </fields>
    <label>App Log</label>
    <nameField>
        <displayFormat>L-{00000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CMN_DAL_AppLog.cls
/**
 * @description Provides Query methods related to the AppLog object
 *
 * @author jason.van.beukering@accenture.com prashant.k.jain@accenture.com
 *
 * @date 2020, July 2022
 */
public inherited sharing class CMN_DAL_AppLog
{
	private static final String FIELD_CLASS_METHOD = CMN_AppLog__c.CMN_ClassMethod__c.getDescribe().getLocalName();
	private static final String FIELD_LOG_LEVEL = CMN_AppLog__c.CMN_LogLevel__c.getDescribe().getLocalName();
	private static final String OBJECT_NAME = CMN_AppLog__c.SObjectType.getDescribe().getLocalName();

	/**
	 * @description Will return base fields to return on a query
	 *
	 * @return A list of AppLog fields
	 */
	private static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				CMN_AppLog__c.CMN_ExceptionType__c.getDescribe().getLocalName(),
				CMN_AppLog__c.CMN_Limits__c.getDescribe().getLocalName(),
				CMN_AppLog__c.CMN_LineNumber__c.getDescribe().getLocalName(),
				CMN_AppLog__c.CMN_Message__c.getDescribe().getLocalName(),
				CMN_AppLog__c.CMN_RecordId__c.getDescribe().getLocalName(),
				CMN_AppLog__c.CMN_RecordLink__c.getDescribe().getLocalName(),
				CMN_AppLog__c.CMN_ShortMessage__c.getDescribe().getLocalName(),
				CMN_AppLog__c.CMN_StackTrace__c.getDescribe().getLocalName(),
				CMN_AppLog__c.CMN_UserId__c.getDescribe().getLocalName(),
				CMN_AppLog__c.CMN_UserLink__c.getDescribe().getLocalName(),
				CMN_AppLog__c.Name.getDescribe().getLocalName(),
				FIELD_CLASS_METHOD,
				FIELD_LOG_LEVEL
		};
	}

	/**
	 * @description Will find a Single AppLog object based on method
	 *
	 * @param classMethod The class method to use in the query
	 *
	 * @return Either null or a single AppLog Object
	 */
	@TestVisible
	private static CMN_AppLog__c findByMethod(String classMethod)
	{
		List<CMN_AppLog__c> logs = findAllByMethod(classMethod);
		return logs.isEmpty() ? null : logs.iterator().next();
	}

	/**
	 * @description Will find all AppLog objects based on method
	 *
	 * @param classMethod The class method to use in the query
	 *
	 * @return Either null or a single AppLog Object
	 */
	@TestVisible
	private static List<CMN_AppLog__c> findAllByMethod(String classMethod)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_CLASS_METHOD, new Set<String> {CMN_UTIL_String.trim(classMethod)}, getDefaultFields());
	}

	/**
	 * @description Will return all the AppLog objects in the system
	 *
	 * @return A list of AppLog objects
	 */
	@TestVisible
	private static List<CMN_AppLog__c> getAll()
	{
		return CMN_DAL_Search.getAll(OBJECT_NAME, getDefaultFields());
	}

	/**
	 * @description Will find all AppLog objects based on logging level
	 *
	 * @param logLevel The level to filter on
	 *
	 * @return A list of AppLog objects
	 */
	@TestVisible
	private static List<CMN_AppLog__c> findByLogLevel(String logLevel)
	{
		return CMN_DAL_SObjectSelector.findByField(OBJECT_NAME, FIELD_LOG_LEVEL, new Set<String> {logLevel}, getDefaultFields());
	}

	/**
	 * @description Retrieve the count of app logs
	 *
	 * @return Integer - The number of records
	 */
	@TestVisible
	private static Integer getRecordCount()
	{
		return CMN_DAL_Search.getObjectCount(new CMN_DAL_Search.SOQLSearchParameters(OBJECT_NAME));
	}
}