objects/CMN_WebserviceCallQueue__c.object
<CustomObject>
    <description>A object which is used to orchestrate and track webservices (inbound and outbound). By injecting an item into this object will asynchronously manage a call to external web service.</description>
    <fields>
        <fullName>CMN_ClientIDNumber__c</fullName>
        <description>Client ID Number</description>
        <label>Client ID Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMN_PartnerIDNumber__c</fullName>
        <description>Partner ID Number for webservice call queue</description>
        <label>Partner ID Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Webservice Call Queue</label>
    <nameField>
        <displayFormat>WCQ-{0000000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Calls Queue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SC_CTRL_GetAllFinanzUrl.cls
/**
 * @description Used by a Lightning Component to retrieve an Interview Url from the AllFinanz system,
 * will be used by Nurses during underwriting
 *
 * @see SC_CTRL_GetAllFinanzUrl_TEST
 * @see SC_API_GetAllFinanzUrl
 *
 * @author jason.van.beukering@accenture.com
 *
 * @date August 2021
 */
public inherited sharing class SC_CTRL_GetAllFinanzUrl
{
	/**
	 * @description Will get an interview Url from AllFinanz
	 *
	 * @param identityNumber The Identification number of the client (could be either passport or national identification number)
	 * @param contractNumber The number of the contract being underwritten
	 *
	 * @return A dto indicating whether the call was successful and either interviewUrl or Error message
	 */
	@AuraEnabled
	public static DTO_Response getUrl(String identityNumber, String contractNumber)
	{
		CMN_WebserviceCallQueue__c queueItem = CMN_DAL_DataFactory.newOutboundWebserviceQueue(SC_API_GetAllFinanzUrl.SERVICE_NAME);

		queueItem.CMN_ClientIDNumber__c = identityNumber;
		queueItem.CMN_PartnerIDNumber__c = contractNumber;

		SC_API_GetAllFinanzUrl service = (SC_API_GetAllFinanzUrl)CMN_FACTORY_WebserviceManager.execute(new List<CMN_WebserviceCallQueue__c> {queueItem}).iterator().next();

		DTO_Response dtoResponse = new DTO_Response();
		dtoResponse.callSuccessful = service.callResult.completed;
		dtoResponse.interviewUrlOrErrorMessage = dtoResponse.callSuccessful ? service.interviewUrl : service.errorMessage;

		return dtoResponse;
	}

	/**
	 * @description Provides the outcome of the request to AllFinanz to get an interview Url for a client
	 */
	public class DTO_Response
	{
		@AuraEnabled
		public Boolean callSuccessful;
		@AuraEnabled
		public String interviewUrlOrErrorMessage;
	}
}