objects/CMN_JobScheduler__c.object
<CustomObject>
    <description>An object that can be used to manage CronTriggers (Scheduled Jobs) in a managed manager. Only accessible by Administrators.</description>
    <fields>
        <fullName>CMN_ScheduledJobId__c</fullName>
        <description>The Salesforce Id for the Job that was initiated for the current Job Schedular row.</description>
        <label>Scheduled Job Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Job Scheduler</label>
    <nameField>
        <displayFormat>SCHED-{0000}</displayFormat>
        <label>Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AW_TEST_SCHED_RestAdviserPerformance.cls
/**
 * @description Test class for AW_SCHED_RestOutboundAdviserPerformance
 *
 * @see AW_SCHED_RestOutboundAdviserPerformance ST-3495
 *
 * @author Accenture, jason.van.beukering@accenture.com
 *
 * @date 2019, July 2023
 */
@IsTest(SeeAllData=false IsParallel=false)
private class AW_TEST_SCHED_RestAdviserPerformance
{
	@IsTest
	private static void runSchedule()
	{
		Test.startTest();

		CMN_JobScheduler__c scheduler = CMN_DAL_DataFactory.insertJobScheduler(AW_SCHED_RestOutboundAdviserPerformance.class.getName());

		scheduler = CMN_DAL_JobSchedule.findById(scheduler.Id);

		Assert.isNotNull(scheduler.CMN_ScheduledJobId__c, 'AW_SCHED_RestOutboundAdviserPerformance was not started');

		Test.stopTest();
	}
}