objects/CMN_JobScheduler__c.object
<CustomObject>
    <description>An object that can be used to manage CronTriggers (Scheduled Jobs) in a managed manager. Only accessible by Administrators.</description>
    <fields>
        <fullName>CMN_ScheduledJobId__c</fullName>
        <description>The Salesforce Id for the Job that was initiated for the current Job Schedular row.</description>
        <label>Scheduled Job Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Job Scheduler</label>
    <nameField>
        <displayFormat>SCHED-{0000}</displayFormat>
        <label>Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Schedulers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/CMN_ScheduleSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for Scheduled Apex classes; such as the last successful run time of the Schedule</description>
    <fields>
        <fullName>CMN_LastSuccessfulRunTime__c</fullName>
        <description>Holds the last successful run time of the schedule.</description>
        <label>Last Successful Run Time</label>
        <type>DateTime</type>
    </fields>
    <label>CMN Schedule Setting</label>
</CustomObject>

classes/CMN_SCHED_LoginFrequency_TEST.cls
/**
 * @description Test Class for CMN_SCHED_LoginFrequency
 *
 * @see CMN_SCHED_LoginFrequency
 *
 * @author latika.kharbanda@accenture.com
 *
 * @date November 2022
 */
@IsTest(SeeAllData=false IsParallel=false)
private class CMN_SCHED_LoginFrequency_TEST
{
	@TestSetup
	private static void setup()
	{
		CMN_ScheduleSetting__c settings = new CMN_ScheduleSetting__c();
		settings.Name = CMN_SCHED_LoginFrequency.class.getName();
		settings.CMN_LastSuccessfulRunTime__c = CMN_DAL_SObjectDomain.generateRandomDateTime();
		insert settings;
	}

	/**
	 * @description Test method to test the Schedule job
	 */
	@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
	@IsTest
	private static void runSchedule()
	{
		Test.startTest();

		CMN_JobScheduler__c scheduler = CMN_DAL_DataFactory.insertJobScheduler(CMN_SCHED_LoginFrequency.class.getName());

		scheduler = CMN_DAL_JobSchedule.findById(scheduler.Id);

		Test.stopTest();

		Assert.isNotNull(scheduler.CMN_ScheduledJobId__c, 'CMN_SCHED_LoginFrequency was not started');
	}
}