objects/CMN_FeatureSwitches__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>A Hierarchical Custom setting that can be used by developers to switch off features (i.e. disable code, validation rules etc)</description>
    <fields>
        <fullName>CMN_DisableAllOutboundAPICalls__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When switched on for a user or profile then every outbound API Call will be disabled</description>
        <label>Disable All Outbound API Calls</label>
        <type>Checkbox</type>
    </fields>
    <label>CMN Feature Switches</label>
</CustomObject>

classes/CMN_SPC_DisableApiCalls.cls
/**
 * @description Public class to as part of post copy action to disable api calls from custom setting
 *
 * @author Accenture
 *
 * @date 2020
 */
public with sharing class CMN_SPC_DisableApiCalls extends CMN_SPC_BaseWorker
{
	/**
	 * @description Method to override run class to disable feature switch org record
	 */
	protected override void internalRun()
	{
		CMN_FeatureSwitches__c orgDefaultFeatureSwitch = CMN_DAL_FeatureSwitches.getOrgFeatureSwitchRecord();

		if(orgDefaultFeatureSwitch != null)
		{
			orgDefaultFeatureSwitch.CMN_DisableAllOutboundAPICalls__c = true;

			CMN_DAL_SObjectDomain.updateDBObject(orgDefaultFeatureSwitch);
		}
	}
}