objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialHolding__c.object
<CustomObject>
    <description>A holding within a client&apos;s investment account.</description>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Holdings</relationshipLabel>
        <relationshipName>FinancialHoldings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>IndustriesIndividual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Financial Holdings</relationshipLabel>
        <relationshipName>ClientFinancialHoldings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Holding</label>
    <nameField>
        <label>Financial Holding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Holdings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/dlrs_FinServ_FinancialHoldingTest.cls
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_FinServ_FinancialHoldingTest
{
    @IsTest
    private static void testTrigger()
    {
        //Create Account
        Account priOwner = new Account();
        priOwner.Name = 'test account';
        insert priOwner;
        
        //Create Financial Account
        FinServ__FinancialAccount__c finAcct = new FinServ__FinancialAccount__c();
        finAcct.Name = 'test finAccount';
        finAcct.FinServ__PrimaryOwner__c = priOwner.id;
        insert finAcct;
            
        // Force the dlrs_FinServ_FinancialHoldingTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new FinServ__FinancialHolding__c(
        FinServ__FinancialAccount__c = finAcct.id
        ));
    }
}