objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

objects/SC_ServiceType__c.object
<CustomObject>
    <description>Custom object created for Servicing Console app for the various service types</description>
    <fields>
        <fullName>SC_KnowledgeArticle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to relate the knowledge article for any service type.</description>
        <label>Knowledge Article</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Service Types</relationshipLabel>
        <relationshipName>ServiceTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SC_ServiceType__c</fullName>
        <description>This field stores the Service Type Code</description>
        <label>Service Type</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SC_FLOW_UpdateServiceTypeArticle.cls
/**
 * @description Flow Class containing invocable methods to fetch the data of Knowledge Article Id
 * and Service Type Record Id
 *
 * @see SC_FLOW_UpdateServiceTypeArticle_TEST @story ST-425625
 *
 * @author uttpal.chandra@accenture.com
 *
 * @date March 2023
 */
public inherited sharing class SC_FLOW_UpdateServiceTypeArticle
{
	/**
	 * @description Method use to call the Queueable Apex with the parameters received from the flow
	 *
	 * @param dtoRequests List of request DTOs
	 */
	@InvocableMethod(Label='Update Service Type on Knowledge Article Publish' Description='Method is used to update the related Service Type on Knowledge Article publish')
	public static void updateServiceTypes(List<DTO_Request> dtoRequests)
	{
		System.enqueueJob(new SC_QUE_UpdateServiceType(dtoRequests));
	}

	/**
	 * @description Request DTO
	 */
	public class DTO_Request
	{
		/**
		 * @description Contains the Service Type recordId which is linked to the Published Articles
		 */
		@InvocableVariable(Label='Service Type Id' Description='List of Service Associated with the Published Article')
		public List<Id> serviceTypeIds;
		/**
		 * @description Contain the knowledgeArticleId
		 */
		@InvocableVariable(Label='Knowledge Article Id' Description='Knowledge Article Id of Knowledge Article')
		public Id knowledgeArticleId;
	}

	/**
	 * @description Inner class to update Service type with the Latest Knowledge Article
	 */
	public class SC_QUE_UpdateServiceType implements Queueable
	{
		private final Map<Id, Set<Id>> knowledgeArticleIdToServiceTypesMap;
		private final Set<Id> serviceTypeRecordIds;

		/**
		 * @description Constructor to initialize the variables
		 *
		 * @param knowledgeArticleServiceTypeIds DTO contains List of knowledge Article Id and List of Service type Ids
		 */
		public SC_QUE_UpdateServiceType(List<SC_FLOW_UpdateServiceTypeArticle.DTO_Request> knowledgeArticleServiceTypeIds)
		{
			knowledgeArticleIdToServiceTypesMap = new Map<Id, Set<Id>>();
			serviceTypeRecordIds = new Set<Id>();

			for(SC_FLOW_UpdateServiceTypeArticle.DTO_Request knowledgeArticleServiceTypeId : knowledgeArticleServiceTypeIds)
			{
				knowledgeArticleIdToServiceTypesMap.put(knowledgeArticleServiceTypeId.knowledgeArticleId, new Set<Id>(knowledgeArticleServiceTypeId.serviceTypeIds));
				serviceTypeRecordIds.addAll(knowledgeArticleServiceTypeId.serviceTypeIds);
			}
		}

		/**
		 * @description Method to Update the Service Type
		 *
		 * @param param1 Default Parameter
		 */
		public void execute(QueueableContext param1)
		{
			Map<Id, SC_ServiceType__c> serviceTypeMap = new Map<Id, SC_ServiceType__c>(SC_DAL_ServiceType.findById(serviceTypeRecordIds));

			List<Knowledge__kav> foundArticles = SC_DAL_Knowledge.findByPublishedKnowledgeArticleId(knowledgeArticleIdToServiceTypesMap.keySet());

			for(Knowledge__kav foundArticle : foundArticles)
			{
				Set<Id> serviceTypeIds = knowledgeArticleIdToServiceTypesMap.get(foundArticle.KnowledgeArticleId);

				for(Id serviceTypeId : serviceTypeIds)
				{
					SC_ServiceType__c foundServiceType = serviceTypeMap.get(serviceTypeId);
					foundServiceType.SC_KnowledgeArticle__c = foundArticle.Id;
				}
			}

			CMN_DAL_SObjectDomain.updateDBObjects(serviceTypeMap.values());
		}
	}
}