objects/PersonLifeEvent.object
<CustomObject>
    <fields>
        <fullName>AW_ClientCommunityIcon__c</fullName>
        <description>Used to calculate lightning icon to display on community based on event type.</description>
        <formula>CASE
    (
        EventType, 
        &quot;Birth&quot;, &quot;standard:people&quot;, 
        &quot;Car&quot;, &quot;custom:custom31&quot;,
        &quot;Graduation&quot;, &quot;standard:reward&quot;,
        &quot;Job&quot;, &quot;standard:case&quot;,
        &quot;Marriage&quot;, &quot;custom:custom1&quot;,
        &quot;Relocation&quot;, &quot;custom:custom106&quot;,
        &quot;Home&quot;, &quot;standard:home&quot;,
        &quot;Baby&quot;, &quot;standard:bot&quot;,
        &quot;Diagnosis&quot;, &quot;standard:feed&quot;,
        &quot;Retirement&quot;, &quot;standard:goals&quot;,
        &quot;standard:lightning_component&quot;
    )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Community Icon</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AW_ImpactOnOutcomeGoals__c</fullName>
        <description>What is the outcome of this event on the goals?</description>
        <label>Impact on outcome/goals</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AW_Impact__c</fullName>
        <description>Please select impact</description>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Positive</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_MasterAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the Master Account Details</description>
        <label>Master Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Person Life Events (MasterAccount)</relationshipLabel>
        <relationshipName>AW_PersonLifeEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AW_PriorityLevel__c</fullName>
        <description>Select Priority Level</description>
        <label>Priority Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AW_SortingDate__c</fullName>
        <description>Used by lightning component to sort life events and goals</description>
        <formula>DATEVALUE(EventDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sorting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AW_VisibleToClient__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this event visible to client?</description>
        <label>Visible to client</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AW_DAL_PersonLifeEvent.cls
/**
 * @description Public class to return the record of Person Life Event
 *
 * @author Accenture
 *
 * @date May 2021
 */
public inherited sharing class AW_DAL_PersonLifeEvent
{
	private static final String FIELD_EVENT_DATE = PersonLifeEvent.EventDate.getDescribe().getLocalName();
	private static final String FIELD_PRIMARY_PERSON_ID = PersonLifeEvent.PrimaryPersonId.getDescribe().getLocalName();
	private static final String FIELD_VISIBLE_TO_CLIENT = PersonLifeEvent.AW_VisibleToClient__c.getDescribe().getLocalName();
	private static final String OBJECT_NAME = PersonLifeEvent.SObjectType.getDescribe().getLocalName();
	public static final String MARRIAGE_EVENT_TYPE = 'Marriage';

	/**
	 * @description Method to define the fields to retrieve for most queries
	 *
	 * @return A list of fields
	 */
	public static Set<String> getDefaultFields()
	{
		return new Set<String>
		{
				FIELD_EVENT_DATE,
				PersonLifeEvent.AW_ClientCommunityIcon__c.getDescribe().getLocalName(),
				PersonLifeEvent.AW_ImpactOnOutcomeGoals__c.getDescribe().getLocalName(),
				PersonLifeEvent.AW_Impact__c.getDescribe().getLocalName(),
				PersonLifeEvent.AW_MasterAccount__c.getDescribe().getLocalName(),
				PersonLifeEvent.AW_PriorityLevel__c.getDescribe().getLocalName(),
				PersonLifeEvent.AW_SortingDate__c.getDescribe().getLocalName(),
				PersonLifeEvent.EventDate.getDescribe().getLocalName(),
				PersonLifeEvent.EventDescription.getDescribe().getLocalName(),
				PersonLifeEvent.Id.getDescribe().getLocalName(),
				PersonLifeEvent.OwnerId.getDescribe().getLocalName(),
				PersonLifeEvent.Name.getDescribe().getLocalName()
		};
	}

	/**
	 * @description Method to get the list of Person Life Event of Contact
	 *
	 * @param contactId
	 *
	 * @return List of PersonLifeEvent
	 */
	public static List<PersonLifeEvent> findByPrimaryPerson(Id contactId)
	{
		CMN_DAL_Search.SOQLSearchParameters searchParameters = CMN_DAL_SObjectSelector.initialiseParameters(OBJECT_NAME, FIELD_PRIMARY_PERSON_ID, new Set<String> {String.valueOf(contactId)}, getDefaultFields());

		CMN_SOQL_Query.AndCondition andCondition = new CMN_SOQL_Query.AndCondition();

		andCondition.add(new CMN_SOQL_Query.FieldCondition(FIELD_VISIBLE_TO_CLIENT, CMN_SOQL_Query.Operator.EQUALS, true));
		searchParameters.searchConditions.add(andCondition);

		CMN_SOQL_Query.OrderBy orderBy = searchParameters.addOrderByField(FIELD_EVENT_DATE);
		orderBy.nullsFirst = true;

		return CMN_DAL_Search.getObjects(searchParameters);
	}

	/**
	 * @description Method to get the a Person Life Event
	 *
	 * @param eventId Id of the event
	 *
	 * @return Null of the item
	 */
	@TestVisible
	private static PersonLifeEvent findById(Id eventId)
	{
		return (PersonLifeEvent)CMN_DAL_SObjectSelector.findById(OBJECT_NAME, eventId, getDefaultFields());
	}
}